Repository ansible-collections/azure, pull requests merged in 2020-10, with the labels that each got.

#276 Add new module azure_rm_openshiftmanagedcluster
  plugins/modules/azure_rm_openshiftmanagedcluster.py
  pr-pipelines.yml
  tests/integration/targets/azure_rm_openshiftmanagedcluster/aliases
  tests/integration/targets/azure_rm_openshiftmanagedcluster/meta/main.yml
  tests/integration/targets/azure_rm_openshiftmanagedcluster/tasks/main.yml
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.11.txt
Labels: medium_priority

#280 Azure rm subscription info
  plugins/module_utils/azure_rm_common.py
  plugins/modules/azure_rm_subscription_info.py
  pr-pipelines.yml
  tests/integration/targets/azure_rm_subscription/aliases
  tests/integration/targets/azure_rm_subscription/meta/main.yml
  tests/integration/targets/azure_rm_subscription/tasks/main.yml
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.11.txt
Labels: medium_priority, new_module_pr, ready_for_review

#278 added no_log to protected_settings variable
  plugins/modules/azure_rm_virtualmachineextension.py
Labels: medium_priority, ready_for_review

#296 Fix azure_rm_roleassignment idempotence error
  plugins/modules/azure_rm_roleassignment.py
Labels: medium_priority, ready_for_review

#302 Manageddisk info managed by
  plugins/modules/azure_rm_manageddisk_info.py
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.11.txt
  tests/sanity/ignore-2.9.txt
Labels: medium_priority, ready_for_review

#295 fix azure_rm_keyvault idempotency
  plugins/modules/azure_rm_keyvault.py
Labels: medium_priority, ready_for_review

#294 Add vnet_subnet_id for agent pool
  plugins/modules/azure_rm_aks.py
  tests/integration/targets/azure_rm_aks/tasks/main.yml
Labels: documentation-pr, ready_for_review

#273 Added force deletion capability to log analytics module and updated requirements.txt
  plugins/modules/azure_rm_loganalyticsworkspace.py
  plugins/modules/azure_rm_loganalyticsworkspace_info.py
  pr-pipelines.yml
  requirements-azure.txt
  tests/integration/targets/azure_rm_loganalyticsworkspace/aliases
  tests/integration/targets/azure_rm_loganalyticsworkspace/meta/main.yml
  tests/integration/targets/azure_rm_loganalyticsworkspace/tasks/main.yml
Labels: medium_priority, ready_for_review

#271 Azure Recovery Services VM Backup Policy
  plugins/modules/azure_rm_vmbackuppolicy.py
  plugins/modules/azure_rm_vmbackuppolicy_info.py
  pr-pipelines.yml
  tests/integration/targets/azure_rm_vmbackuppolicy/aliases
  tests/integration/targets/azure_rm_vmbackuppolicy/meta/main.yml
  tests/integration/targets/azure_rm_vmbackuppolicy/tasks/main.yml
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.11.txt
Labels: medium_priority, new_module_pr, ready_for_review

#286 Added new module for supporting DNS recordset operations in Private DNS zone and Resolved issue #265
  plugins/modules/azure_rm_privatednsrecordset.py
  plugins/modules/azure_rm_privatednsrecordset_info.py
  pr-pipelines.yml
  tests/integration/targets/azure_rm_privatednsrecordset/aliases
  tests/integration/targets/azure_rm_privatednsrecordset/meta/main.yml
  tests/integration/targets/azure_rm_privatednsrecordset/tasks/main.yml
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.11.txt
Labels: medium_priority, new_module_pr, ready_for_review, work in

#264 resolved issue #142
  plugins/modules/azure_rm_subnet.py
  plugins/modules/azure_rm_subnet_info.py
  tests/integration/targets/azure_rm_subnet/tasks/main.yml
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.11.txt
Labels: medium_priority, ready_for_review
