Repository ansible-collections/azure, pull requests merged in 2020-09, with the labels that each got.

#195 Support azure cli credentials with multiple `subscription_id`s
  plugins/doc_fragments/azure.py
  plugins/module_utils/azure_rm_common.py
Labels: medium_priority, work in

#244 Add 10.3 version for azure_rm_mariadbserver module
  plugins/modules/azure_rm_mariadbserver.py
  tests/integration/targets/azure_rm_mariadbserver/tasks/main.yml
Labels: medium_priority, ready_for_review

#226 Update azure_rm_storageaccount yaml
  pr-pipelines.yml
  tests/integration/targets/azure_rm_storageaccount/tasks/main.yml
Labels: work in

#247 Update azure_rm_aks test yaml
  plugins/modules/azure_rm_aks.py
  tests/integration/targets/azure_rm_aks/tasks/main.yml
Labels: ready_for_review

#246 Update requirement file
  pr-pipelines.yml
  requirements-azure.txt
Labels: medium_priority, ready_for_review

#125 Support static IPv6 address
  plugins/modules/azure_rm_publicipaddress.py
  tests/integration/targets/azure_rm_publicipaddress/tasks/main.yml
Labels: ready_for_review

#248 Resolved #234
  plugins/modules/azure_rm_backupazurevm.py
  plugins/modules/azure_rm_backupazurevm_info.py
  pr-pipelines.yml
  tests/integration/targets/azure_rm_backupazurevm/aliases
  tests/integration/targets/azure_rm_backupazurevm/meta/main.yml
  tests/integration/targets/azure_rm_backupazurevm/tasks/main.yml
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.11.txt
Labels: medium_priority, new_module_pr, work in

#256 Add new feature for azure_rm_subnet
  plugins/module_utils/azure_rm_common.py
  plugins/modules/azure_rm_subnet.py
  plugins/modules/azure_rm_subnet_info.py
  tests/integration/targets/azure_rm_subnet/tasks/main.yml
Labels: medium_priority, ready_for_review

#243 updated code to fetch availability zone info into hostvars
  plugins/inventory/azure_rm.py
Labels: medium_priority, ready_for_review

#254 Recovery Services Vault #210
  plugins/modules/azure_rm_recoveryservicesvault.py
  plugins/modules/azure_rm_recoveryservicesvault_info.py
  pr-pipelines.yml
  tests/integration/targets/azure_rm_recoveryservicesvault/aliases
  tests/integration/targets/azure_rm_recoveryservicesvault/meta/main.yml
  tests/integration/targets/azure_rm_recoveryservicesvault/tasks/main.yml
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.11.txt
Labels: new_module_pr, work in

#261 Move azure_rm inventory Documentation to Fragment
  plugins/doc_fragments/azure_rm.py
  plugins/inventory/azure_rm.py
Labels: ready_for_review

#105 Make inventory_hostname configurable with hostvar_expressions
  plugins/doc_fragments/azure_rm.py
  plugins/inventory/azure_rm.py
Labels: medium_priority, new_featrue
