Repository ansible-collections/azure, pull requests merged in 2020-08, with the labels that each got.

#229 Update new pr-pipeline for weekly test
  pr-pipelines.yml
Labels: ready_for_review

#219 Storage account allow blob public access parameter
  plugins/modules/azure_rm_storageaccount.py
  plugins/modules/azure_rm_storageaccount_info.py
  tests/integration/targets/azure_rm_storageaccount/tasks/main.yml
Labels: medium_priority, new_featrue

#208 Update azure_rm_virtualmachine boot_diagnostics resource group config…
  plugins/modules/azure_rm_virtualmachine.py
  plugins/modules/azure_rm_virtualmachine_info.py
Labels: ready_for_review

#237 Fix the problem of azure_rm_manageddisk lun self-increment
  plugins/modules/azure_rm_manageddisk.py
Labels: ready_for_review

#99 Fixing rule_type reference
  plugins/modules/azure_rm_appgateway.py
Labels: medium_priority, ready_for_review

#199 add load_balancer_sku option for aks
  plugins/modules/azure_rm_aks.py
  tests/integration/targets/azure_rm_aks/tasks/main.yml
Labels: ready_for_review

#197 Improve OS detection when VM has no osProfile
  plugins/inventory/azure_rm.py
Labels: medium_priority, ready_for_review

#240 Add IPv6 address for azure_rm_subnet
  plugins/modules/azure_rm_subnet.py
  plugins/modules/azure_rm_subnet_info.py
  tests/integration/targets/azure_rm_subnet/tasks/main.yml
Labels: new_featrue, ready_for_review

#239 Get address_prefixes info from virtualnetwork
  plugins/modules/azure_rm_networkinterface.py
  plugins/modules/azure_rm_virtualnetwork_info.py
  tests/integration/targets/azure_rm_networkinterface/tasks/main.yml
  tests/integration/targets/azure_rm_virtualnetwork/tasks/main.yml
Labels: documentation-pr, ready_for_review
