Repository ansible-collections/azure, pull requests merged in 2021-05, with the labels that each got.

#520 Bump version to v1.5.1
  CHANGELOG.md
  galaxy.yml
Labels: medium_priority, ready_for_review

#510 Optimizing ado.sh
  pr-pipelines.yml
  sanity-requirements-azure.txt
  tests/utils/ado/ado.sh
Labels: medium_priority, ready_for_review

#507 azure_rm_securitygroup - idempotent when args are lists
  plugins/modules/azure_rm_securitygroup.py
  tests/integration/targets/azure_rm_securitygroup/tasks/main.yml
Labels: medium_priority, ready_for_review

#523 Add availability zones to azure_rm_virtualmachine_info module
  plugins/modules/azure_rm_virtualmachine_info.py
Labels: medium_priority, work in

#540 Add log_mode and log_path to azure.py
  plugins/doc_fragments/azure.py
  plugins/module_utils/azure_rm_common.py
  plugins/modules/azure_rm_aduser.py
  plugins/modules/azure_rm_aduser_info.py
  plugins/modules/azure_rm_backuppolicy.py
  plugins/modules/azure_rm_backuppolicy_info.py
  plugins/modules/azure_rm_iotdevice.py
  plugins/modules/azure_rm_iotdevicemodule.py
  plugins/modules/azure_rm_roledefinition.py
  plugins/modules/azure_rm_roledefinition_info.py
  plugins/modules/azure_rm_virtualmachine_info.py
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.11.txt
  tests/sanity/ignore-2.12.txt
Labels: medium_priority, ready_for_review

#215 New module: azure_rm_adapplication
  plugins/modules/azure_rm_adapplication.py
  plugins/modules/azure_rm_adapplication_info.py
  pr-pipelines.yml
  tests/integration/targets/azure_rm_adapplication/aliases
  tests/integration/targets/azure_rm_adapplication/meta/main.yml
  tests/integration/targets/azure_rm_adapplication/tasks/main.yml
Labels: medium_priority, new_module_pr, work in

#423 New module: azure_rm_adgroup
  plugins/modules/azure_rm_adgroup.py
  plugins/modules/azure_rm_adgroup_info.py
  pr-pipelines.yml
  tests/integration/targets/azure_rm_adgroup/aliases
  tests/integration/targets/azure_rm_adgroup/meta/main.yml
  tests/integration/targets/azure_rm_adgroup/tasks/main.yml
Labels: medium_priority, ready_for_review

#322 New Module [API Management]
  plugins/modules/azure_rm_apimanagement.py
  plugins/modules/azure_rm_apimanagement_info.py
  pr-pipelines.yml
  requirements-azure.txt
  tests/integration/targets/azure_rm_apimanagement/aliases
  tests/integration/targets/azure_rm_apimanagement/meta/main.yml
  tests/integration/targets/azure_rm_apimanagement/tasks/main.yml
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.11.txt
  tests/sanity/ignore-2.12.txt
Labels: medium_priority, new_module_pr, ready_for_review

#549 increase integration testing timeout
  pr-pipelines.yml
Labels: medium_priority, ready_for_review

#528 New module: azure_rm_ipgroup
  plugins/modules/azure_rm_ipgroup.py
  plugins/modules/azure_rm_ipgroup_info.py
  pr-pipelines.yml
  tests/integration/targets/azure_rm_ipgroup/aliases
  tests/integration/targets/azure_rm_ipgroup/meta/main.yml
  tests/integration/targets/azure_rm_ipgroup/tasks/main.yml
Labels: medium_priority, new_module_pr, ready_for_review

#519 New module: azure_rm_eventhub
  plugins/module_utils/azure_rm_common.py
  plugins/modules/azure_rm_eventhub.py
  plugins/modules/azure_rm_eventhub_info.py
  pr-pipelines.yml
  requirements-azure.txt
  tests/integration/targets/azure_rm_eventhub/aliases
  tests/integration/targets/azure_rm_eventhub/meta/main.yml
  tests/integration/targets/azure_rm_eventhub/tasks/main.yml
Labels: medium_priority, new_module_pr, ready_for_review

#501 New module: azure_rm_proximityplacementgroup
  plugins/modules/azure_rm_proximityplacementgroup.py
  plugins/modules/azure_rm_proximityplacementgroup_info.py
  pr-pipelines.yml
  tests/integration/targets/azure_rm_proximityplacementgroup/aliases
  tests/integration/targets/azure_rm_proximityplacementgroup/meta/main.yml
  tests/integration/targets/azure_rm_proximityplacementgroup/tasks/main.yml
Labels: medium_priority, new_module_pr, ready_for_review

#495 New module: azure_rm_privatednszonelink
  plugins/modules/azure_rm_privatednszonelink.py
  plugins/modules/azure_rm_privatednszonelink_info.py
  pr-pipelines.yml
  tests/integration/targets/azure_rm_privatednszonelink/aliases
  tests/integration/targets/azure_rm_privatednszonelink/meta/main.yml
  tests/integration/targets/azure_rm_privatednszonelink/tasks/main.yml
Labels: medium_priority, new_module_pr, ready_for_review
