Repository ansible-collections/azure, pull requests merged in 2021-04, with the labels that each got.

#485 Paultaiton 20210409 requirements doc
  plugins/doc_fragments/azure.py
Labels: documentation-pr, medium_priority, ready_for_review

#482 Allow storage account type Premium_ZRS for FileStorage and BlockBlobStorage
  plugins/modules/azure_rm_storageaccount.py
Labels: medium_priority, ready_for_review

#480 Add 2.11 to test matrix, add ignore-2.12.txt
  pr-pipelines.yml
  tests/sanity/ignore-2.12.txt
Labels: medium_priority, ready_for_review

#451 Support subnet lookup for app gateway
  plugins/modules/azure_rm_appgateway.py
  tests/integration/targets/azure_rm_appgateway/tasks/main.yml
Labels: medium_priority, ready_for_review, work in

#372 Add new module to deploy Azure Cognitive Search 'azure_rm_cognitivesearch'
  plugins/module_utils/azure_rm_common.py
  plugins/modules/azure_rm_cognitivesearch.py
  plugins/modules/azure_rm_cognitivesearch_info.py
  pr-pipelines.yml
  requirements-azure.txt
  tests/integration/targets/azure_rm_cognitivesearch/aliases
  tests/integration/targets/azure_rm_cognitivesearch/meta/main.yml
  tests/integration/targets/azure_rm_cognitivesearch/tasks/main.yml
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.11.txt
  tests/sanity/ignore-2.9.txt
Labels: new_module_pr, ready_for_review

#333 Added new module for Azure API management service.
  plugins/modules/azure_rm_apimanagementservice.py
  plugins/modules/azure_rm_apimanagementservice_info.py
  pr-pipelines.yml
  tests/integration/targets/azure_rm_apimanagementservice/aliases
  tests/integration/targets/azure_rm_apimanagementservice/meta/main.yml
  tests/integration/targets/azure_rm_apimanagementservice/tasks/main.yml
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.11.txt
  tests/sanity/ignore-2.9.txt
Labels: medium_priority, new_module_pr, ready_for_review

#329 Add new module relate with Virtual WAN
  plugins/module_utils/azure_rm_common.py
  plugins/modules/azure_rm_virtualwan.py
  plugins/modules/azure_rm_virtualwan_info.py
  pr-pipelines.yml
  requirements-azure.txt
  tests/integration/targets/azure_rm_virtualwan/aliases
  tests/integration/targets/azure_rm_virtualwan/meta/main.yml
  tests/integration/targets/azure_rm_virtualwan/tasks/main.yml
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.11.txt
  tests/sanity/ignore-2.9.txt
Labels: medium_priority, ready_for_review

#488 Update azure_rm_storageaccount relate test yml
  plugins/module_utils/azure_rm_common.py
  tests/integration/targets/azure_rm_cognitivesearch/aliases
  tests/integration/targets/azure_rm_storageaccount/tasks/main.yml
Labels: high_priority, ready_for_review

#328 Add new module relate with VPN site
  plugins/modules/azure_rm_vpnsite.py
  plugins/modules/azure_rm_vpnsite_info.py
  plugins/modules/azure_rm_vpnsitelink_info.py
  pr-pipelines.yml
  tests/integration/targets/azure_rm_vpnsite/aliases
  tests/integration/targets/azure_rm_vpnsite/meta/main.yml
  tests/integration/targets/azure_rm_vpnsite/tasks/main.yml
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.11.txt
Labels: medium_priority, ready_for_review

#402 Add new module for AD Users
  plugins/modules/azure_rm_aduser.py
  plugins/modules/azure_rm_aduser_info.py
  pr-pipelines.yml
  tests/integration/targets/azure_rm_aduser/aliases
  tests/integration/targets/azure_rm_aduser/meta/main.yml
  tests/integration/targets/azure_rm_aduser/tasks/main.yml
Labels: medium_priority, new_module_pr, work in
