Repository ansible-collections/azure, pull requests merged in 2021-11, with the labels that each got.

#694 Allow module-level subscription id to be used for cross-subscription resource management
  plugins/module_utils/azure_rm_common.py
Labels: medium_priority, work in, plugin

#693 Correct idempotency for `azure_rm_appserviceplan` and premium SKU plans
  plugins/modules/azure_rm_appserviceplan.py
  tests/integration/targets/azure_rm_appserviceplan/tasks/main.yml
Labels: enhancement, ready_for_review, medium_priority, new_featrue

#695 Add additional parameters for webapp site config
  plugins/modules/azure_rm_webapp.py
  plugins/modules/azure_rm_webapp_info.py
  tests/integration/targets/azure_rm_webapp/tasks/main.yml
Labels: ready_for_review, medium_priority, new_featrue

#696 Update ignore file
  plugins/modules/azure_rm_adapplication.py
  plugins/modules/azure_rm_containerregistryreplication_info.py
  plugins/modules/azure_rm_containerregistrywebhook_info.py
  plugins/modules/azure_rm_dnsrecordset_info.py
  plugins/modules/azure_rm_eventhub.py
  plugins/modules/azure_rm_expressroute.py
  plugins/modules/azure_rm_manageddisk.py
  plugins/modules/azure_rm_manageddisk_info.py
  plugins/modules/azure_rm_networkinterface_info.py
  plugins/modules/azure_rm_notificationhub.py
  plugins/modules/azure_rm_privateendpoint.py
  plugins/modules/azure_rm_privateendpoint_info.py
  plugins/modules/azure_rm_publicipaddress.py
  plugins/modules/azure_rm_subnet.py
  plugins/modules/azure_rm_virtualmachine.py
  plugins/modules/azure_rm_virtualmachineextension.py
  plugins/modules/azure_rm_virtualmachinescaleset.py
  plugins/modules/azure_rm_virtualmachinescaleset_info.py
  plugins/modules/azure_rm_virtualnetwork.py
  plugins/modules/azure_rm_virtualnetwork_info.py
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.11.txt
  tests/sanity/ignore-2.12.txt
  tests/sanity/ignore-2.13.txt
Labels: documentation-pr, ready_for_review, high_priority

#698 Misc typo fixes
  plugins/modules/azure_rm_publicipaddress.py
  plugins/modules/azure_rm_virtualmachine.py
  plugins/modules/azure_rm_virtualmachinescaleset.py
Labels: documentation-pr, ready_for_review, medium_priority

#687 Add managed disks list to dynamic inventory hostvars
  plugins/inventory/azure_rm.py
Labels: ready_for_review, inventory, medium_priority

#683 Add ability to connect network interface to application gateway backend pool
  plugins/modules/azure_rm_networkinterface.py
  plugins/modules/azure_rm_networkinterface_info.py
  tests/integration/targets/azure_rm_networkinterface/tasks/main.yml
Labels: enhancement, ready_for_review, medium_priority, new_featrue, work in
