Repository ansible-collections/azure, pull requests merged in 2021-03, with the labels that each got.

#440 add creation and deletion of nodepools
  plugins/modules/azure_rm_aks.py
  tests/integration/targets/azure_rm_aks/tasks/main.yml
Labels: medium_priority, ready_for_review

#434 Add tags for azure_rm_loganalyticsworkspace
  plugins/modules/azure_rm_loganalyticsworkspace.py
  tests/integration/targets/azure_rm_loganalyticsworkspace/tasks/main.yml
Labels: ready_for_review

#373 Add new module to manage backup policies
  plugins/module_utils/azure_rm_common.py
  plugins/modules/azure_rm_backuppolicy.py
  plugins/modules/azure_rm_backuppolicy_info.py
  pr-pipelines.yml
  requirements-azure.txt
  tests/integration/targets/azure_rm_backuppolicy/aliases
  tests/integration/targets/azure_rm_backuppolicy/meta/main.yml
  tests/integration/targets/azure_rm_backuppolicy/tasks/main.yml
Labels: medium_priority, new_module_pr, ready_for_review

#356 Conditionally call MSI auth when interacting with keyvault
  plugins/modules/azure_rm_keyvaultkey.py
  plugins/modules/azure_rm_keyvaultkey_info.py
  plugins/modules/azure_rm_keyvaultsecret.py
  plugins/modules/azure_rm_keyvaultsecret_info.py
Labels: ready_for_review

#449 Update azure_rm_backupolicy add version
  plugins/modules/azure_rm_backuppolicy.py
  plugins/modules/azure_rm_backuppolicy_info.py
Labels: ready_for_review

#307 resolve issue (#268)
  plugins/modules/azure_rm_openshiftmanagedcluster.py
Labels: medium_priority, ready_for_review

#428 New module azure_rm_managementgroup_info
  plugins/module_utils/azure_rm_common.py
  plugins/modules/azure_rm_managementgroup_info.py
  pr-pipelines.yml
  requirements-azure.txt
  tests/integration/targets/azure_rm_managementgroup/aliases
  tests/integration/targets/azure_rm_managementgroup/meta/main.yml
  tests/integration/targets/azure_rm_managementgroup/tasks/main.yml
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.11.txt
Labels: ready_for_review

#463 Set the default value of enable_soft_delete to true
  plugins/modules/azure_rm_keyvault.py
  plugins/modules/azure_rm_keyvault_info.py
  tests/integration/targets/azure_rm_keyvault/tasks/main.yml
Labels: medium_priority, ready_for_review

#462 Unrestrict the virtual network of multiple DNS servers when I(purge_a…
  plugins/modules/azure_rm_virtualnetwork.py
Labels: medium_priority, ready_for_review

#456 Correct doc for storageaccount network_acls options
  plugins/modules/azure_rm_storageaccount.py
Labels: documentation-pr, medium_priority, ready_for_review

#458 Update azure_rm_storageaccount.py
  .gitignore
  plugins/modules/azure_rm_storageaccount.py
  tests/integration/targets/azure_rm_storageaccount/tasks/main.yml
Labels: medium_priority, ready_for_review

#352 Add new module azure_rm_datalakestore
  plugins/module_utils/azure_rm_common.py
  plugins/modules/azure_rm_datalakestore.py
  plugins/modules/azure_rm_datalakestore_info.py
  pr-pipelines.yml
  requirements-azure.txt
  tests/integration/targets/azure_rm_datalakestore/aliases
  tests/integration/targets/azure_rm_datalakestore/meta/main.yml
  tests/integration/targets/azure_rm_datalakestore/tasks/main.yml
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.11.txt
  tests/sanity/ignore-2.9.txt
Labels: new_module_pr, ready_for_review

#465 Transfer azure_rm_datalakestore test group 10
  tests/integration/targets/azure_rm_datalakestore/aliases
  tests/integration/targets/azure_rm_datalakestore/tasks/main.yml
Labels: high_priority, ready_for_review

#466 Delete datalake resource group after pipeline test
  pr-pipelines.yml
  tests/integration/targets/azure_rm_keyvault/tasks/main.yml
Labels: ready_for_review

#472 Exclude/ignore developer artifacts
  .gitignore
  galaxy.yml
Labels: medium_priority, ready_for_review
