Repository ansible-collections/azure, pull requests merged in 2021-01, with the labels that each got.

#384 Update azure_rm_deployment document
  plugins/modules/azure_rm_deployment.py
Labels: documentation-pr, ready_for_review

#360 added support for tags in exec_module
  plugins/modules/azure_rm_azurefirewall.py
Labels: medium_priority, ready_for_review

#334 Add azure_rm_route_info module
  plugins/modules/azure_rm_route_info.py
  tests/integration/targets/azure_rm_routetable/aliases
  tests/integration/targets/azure_rm_routetable/tasks/main.yml
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.11.txt
Labels: medium_priority, ready_for_review

#393 Change tasks password to generate key
  tests/integration/targets/azure_rm_autoscale/tasks/main.yml
  tests/integration/targets/azure_rm_deployment/aliases
  tests/integration/targets/azure_rm_gallery/tasks/main.yml
  tests/integration/targets/azure_rm_image/tasks/main.yml
  tests/integration/targets/azure_rm_virtualmachine/tasks/azure_test_deallocate.yml
  tests/integration/targets/azure_rm_virtualmachine/tasks/azure_test_dual_nic.yml
  tests/integration/targets/azure_rm_virtualmachine/tasks/azure_test_ephemeral_os.yml
  tests/integration/targets/azure_rm_virtualmachine/tasks/azure_test_minimal.yml
  tests/integration/targets/azure_rm_virtualmachine/tasks/azure_test_no_public_ip.yml
  tests/integration/targets/azure_rm_virtualmachine/tasks/azure_test_public_ip.yml
  tests/integration/targets/azure_rm_virtualmachineextension/tasks/main.yml
  tests/integration/targets/azure_rm_virtualmachinescaleset/tasks/main.yml
  tests/integration/targets/inventory_azure/playbooks/test_inventory.yml
Labels: high_priority, ready_for_review

#389 Fix doc on returned field name
  plugins/modules/azure_rm_keyvaultsecret_info.py
Labels: documentation-pr, ready_for_review

#387 added storage_autogrow option to postgresqlserver
  plugins/modules/azure_rm_postgresqlserver.py
  plugins/modules/azure_rm_postgresqlserver_info.py
  requirements-azure.txt
  tests/integration/targets/azure_rm_postgresqlserver/tasks/main.yml
Labels: medium_priority, new_featrue, ready_for_review

#400 azure_rm_virtualnetworkpeering: Fix unable to remove non-existing pee…
  plugins/modules/azure_rm_virtualnetworkpeering.py
Labels: medium_priority, ready_for_review

#319 Add missing Mysql version 8.0
  plugins/modules/azure_rm_mysqlserver.py
Labels: medium_priority, ready_for_review

#316 check mode for loadbalancer
  plugins/modules/azure_rm_loadbalancer.py
  tests/integration/targets/azure_rm_loadbalancer/tasks/main.yml
Labels: medium_priority, ready_for_review

#404 Add function that azure_rm_backupazurevm resource in different resour…
  plugins/modules/azure_rm_backupazurevm.py
  plugins/modules/azure_rm_backupazurevm_info.py
Labels: medium_priority, ready_for_review, work in
