Repository ansible-collections/azure, pull requests merged in 2021-07, with the labels that each got.

#577 add new paramter node_labels for agent_pool
  plugins/modules/azure_rm_aks.py
  tests/integration/targets/azure_rm_aks/tasks/main.yml
Labels: enhancement, medium_priority, ready_for_review

#578 Add return value for azure_rm_containerregistry idempotent test
  plugins/modules/azure_rm_containerregistry.py
  plugins/modules/azure_rm_containerregistry_info.py
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.11.txt
  tests/sanity/ignore-2.12.txt
  tests/sanity/ignore-2.9.txt
Labels: enhancement, medium_priority, ready_for_review

#464 azure_rm_roleassignment bugfix
  plugins/modules/azure_rm_roleassignment.py
  plugins/modules/azure_rm_roleassignment_info.py
  tests/integration/targets/azure_rm_roleassignment/aliases
  tests/integration/targets/azure_rm_roleassignment/tasks/main.yml
Labels: medium_priority, ready_for_review

#514 azure_rm_aks: support system-assigned (managed) identity,
  CONTRIBUTING.md
  plugins/modules/azure_rm_aks.py
  requirements-azure.txt
  tests/integration/targets/azure_rm_aks/tasks/minimal-cluster.yml
Labels: medium_priority, work in

#585 Upddate test case
  tests/integration/targets/azure_rm_aks/tasks/main.yml
  tests/integration/targets/azure_rm_aks/tasks/minimal-cluster.yml
  tests/integration/targets/azure_rm_cosmosdbaccount/tasks/main.yml
Labels: ready_for_review

#563 Add new feature storage_profile
  plugins/modules/azure_rm_apimanagementservice.py
  plugins/modules/azure_rm_mysqlserver.py
  plugins/modules/azure_rm_mysqlserver_info.py
  tests/integration/targets/azure_rm_mysqlserver/tasks/main.yml
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.11.txt
  tests/sanity/ignore-2.12.txt
  tests/sanity/ignore-2.9.txt
Labels: medium_priority, new_featrue, ready_for_review
