Repository ansible-collections/azure, pull requests merged in 2021-06, with the labels that each got.

#558 Disable azure_rm_appgateway relate test
  tests/integration/targets/azure_rm_appgateway/aliases
Labels: medium_priority, ready_for_review

#561 Bump version to v1.7.0
  CHANGELOG.md
  galaxy.yml
Labels: ready_for_review

#565 Add name to return data_disks
  plugins/modules/azure_rm_virtualmachine_info.py
  tests/integration/targets/azure_rm_apimanagement/aliases
Labels: ready_for_review

#560 enable_floating_ip is for SQL AlwaysOn not SNAT
  plugins/modules/azure_rm_loadbalancer.py
Labels: documentation-pr, medium_priority, ready_for_review

#496 New module: azure_rm_notificationhub
  plugins/module_utils/azure_rm_common.py
  plugins/modules/azure_rm_notificationhub.py
  plugins/modules/azure_rm_notificationhub_info.py
  pr-pipelines.yml
  requirements-azure.txt
  tests/integration/targets/azure_rm_notificationhub/aliases
  tests/integration/targets/azure_rm_notificationhub/meta/main.yml
  tests/integration/targets/azure_rm_notificationhub/tasks/main.yml
Labels: medium_priority, new_module_pr, ready_for_review

#484 New module: azure_rm_expressroute
  plugins/modules/azure_rm_expressroute.py
  plugins/modules/azure_rm_expressroute_info.py
  pr-pipelines.yml
  tests/integration/targets/azure_rm_expressroute/aliases
  tests/integration/targets/azure_rm_expressroute/meta/main.yml
  tests/integration/targets/azure_rm_expressroute/tasks/main.yml
Labels: new_module_pr, ready_for_review

#497 azure_rm_aks: cluster client & models API version
  plugins/module_utils/azure_rm_common.py
  plugins/modules/azure_rm_aks.py
  tests/integration/targets/azure_rm_aks/tasks/main.yml
Labels: medium_priority, new_featrue, ready_for_review
