Repository ansible-collections/azure, pull requests merged in 2021-08, with the labels that each got.

#586 Bump version to v1.8.0
  CHANGELOG.md
  galaxy.yml
Labels: ready_for_review

#592 Add resource tags
  galaxy.yml
Labels: high_priority, ready_for_review

#574 Update contributing notes for dev/testing
  .gitignore
  CONTRIBUTING.md
  galaxy.yml
Labels: documentation-pr, medium_priority, ready_for_review

#582 Allow IPv6 with NetworkInterfaceIPConfiguration
  plugins/modules/azure_rm_networkinterface.py
  plugins/modules/azure_rm_networkinterface_info.py
  tests/integration/targets/azure_rm_networkinterface/tasks/main.yml
Labels: ready_for_review, medium_priority, new_featrue

#566 postgres server backup-support
  plugins/modules/azure_rm_postgresqlserver.py
  plugins/modules/azure_rm_postgresqlserver_info.py
  tests/integration/targets/azure_rm_postgresqlserver/tasks/main.yml
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.11.txt
  tests/sanity/ignore-2.12.txt
  tests/sanity/ignore-2.9.txt
Labels: ready_for_review, medium_priority, new_featrue

#559 Addition of Spot instance support for VM and VMSS
  plugins/modules/azure_rm_virtualmachine.py
  plugins/modules/azure_rm_virtualmachinescaleset.py
  tests/integration/targets/azure_rm_virtualmachine/tasks/azure_test_spot.yml
  tests/integration/targets/azure_rm_virtualmachinescaleset/tasks/main.yml
Labels: ready_for_review, medium_priority, new_featrue

#493 New module: azure_rm_ddosprotectionplan
  plugins/modules/azure_rm_ddosprotectionplan.py
  plugins/modules/azure_rm_ddosprotectionplan_info.py
  pr-pipelines.yml
  tests/integration/targets/azure_rm_ddosprotectionplan/aliases
  tests/integration/targets/azure_rm_ddosprotectionplan/meta/main.yml
  tests/integration/targets/azure_rm_ddosprotectionplan/tasks/main.yml
Labels: ready_for_review, new_module_pr, medium_priority

#452 Add support for application gateway path-based routing
  plugins/modules/azure_rm_appgateway.py
  tests/integration/targets/azure_rm_appgateway/tasks/main.yml
Labels: ready_for_review, medium_priority

#450 Allow application gateway probe to use host header from HTTP settings
  plugins/modules/azure_rm_appgateway.py
  tests/integration/targets/azure_rm_appgateway/tasks/main.yml
Labels: ready_for_review, medium_priority

#593 Azure rm privateendpoint
  plugins/modules/azure_rm_privateendpoint.py
  plugins/modules/azure_rm_privateendpoint_info.py
  pr-pipelines.yml
  tests/integration/targets/azure_rm_privateendpoint/aliases
  tests/integration/targets/azure_rm_privateendpoint/meta/main.yml
  tests/integration/targets/azure_rm_privateendpoint/tasks/main.yml
Labels: ready_for_review

#594 New modules for webapp network access restrictions
  plugins/modules/azure_rm_webappaccessrestriction.py
  plugins/modules/azure_rm_webappaccessrestriction_info.py
  pr-pipelines.yml
  tests/integration/targets/azure_rm_webappaccessrestriction/aliases
  tests/integration/targets/azure_rm_webappaccessrestriction/meta/main.yml
  tests/integration/targets/azure_rm_webappaccessrestriction/tasks/main.yml
Labels: ready_for_review, new_module_pr, medium_priority

#590 New modules for webapp vnet connection
  plugins/module_utils/azure_rm_common.py
  plugins/modules/azure_rm_webappvnetconnection.py
  plugins/modules/azure_rm_webappvnetconnection_info.py
  pr-pipelines.yml
  tests/integration/targets/azure_rm_webappvnetconnection/aliases
  tests/integration/targets/azure_rm_webappvnetconnection/meta/main.yml
  tests/integration/targets/azure_rm_webappvnetconnection/tasks/main.yml
Labels: ready_for_review, new_module_pr, medium_priority

#606 BUG FIX: Get latest VM image version
  plugins/modules/azure_rm_virtualmachine.py
Labels: ready_for_review

#608 Small update for ansible-collections
  plugins/modules/azure_rm_virtualmachine.py
  plugins/modules/azure_rm_virtualmachinescaleset.py
  requirements-azure.txt
  tests/integration/targets/azure_rm_aks/tasks/main.yml
Labels: ready_for_review, medium_priority

#607 Bump version to v1.9.0
  CHANGELOG.md
  galaxy.yml
Labels: ready_for_review

#605 VirtualMachineSize facts module
  plugins/modules/azure_rm_virtualmachinesize_info.py
  pr-pipelines.yml
  tests/integration/targets/azure_rm_virtualmachinesize_info/aliases
  tests/integration/targets/azure_rm_virtualmachinesize_info/meta/main.yml
  tests/integration/targets/azure_rm_virtualmachinesize_info/tasks/main.yml
Labels: ready_for_review, new_module_pr, medium_priority

#617 Azure rm virtualmachineimage info latest
  plugins/modules/azure_rm_virtualmachineimage_info.py
  tests/integration/targets/azure_rm_virtualmachineimage_info/tasks/main.yml
Labels: enhancement, ready_for_review, medium_priority

#622 azure_rm_virtualmachine: suppress no_log warning on ssh_password_enabled parameter
  plugins/modules/azure_rm_virtualmachine.py
Labels: enhancement, ready_for_review, medium_priority
