Repository ansible-collections/azure, pull requests merged in 2021-02, with the labels that each got.

#414 Update azure_rm_adserviceprincipal examples
  plugins/modules/azure_rm_adserviceprincipal.py
Labels: ready_for_review

#405 Add new module to get available upgrade versions for an AKS cluster
  plugins/modules/azure_rm_aksupgrade_info.py
  tests/integration/targets/azure_rm_aks/tasks/main.yml
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.11.txt
Labels: medium_priority, new_module_pr, ready_for_review

#415 Improve the documentation of tags
  plugins/doc_fragments/azure_tags.py
Labels: ready_for_review

#427 fixed SyntaxWarning
  plugins/modules/azure_rm_registrationassignment.py
Labels: medium_priority, ready_for_review

#426 change description for access policies return value
  plugins/modules/azure_rm_keyvault_info.py
Labels: documentation-pr, low_priority, ready_for_review
