Repository ansible-collections/azure, pull requests merged in 2021-12, with the labels that each got.

#660 feat: Add expiry information for keyvaultsecrets
  plugins/modules/azure_rm_keyvaultsecret.py
  tests/integration/targets/azure_rm_keyvaultsecret/tasks/main.yml
Labels: ready_for_review, medium_priority, new_featrue

#657 Verify that the VM is created after it is created
  plugins/modules/azure_rm_virtualmachine_info.py
  tests/integration/targets/azure_rm_gallery/tasks/main.yml
  tests/integration/targets/azure_rm_virtualmachine/tasks/azure_test_deallocate.yml
  tests/integration/targets/azure_rm_virtualmachine/tasks/azure_test_dual_nic.yml
  tests/integration/targets/azure_rm_virtualmachine/tasks/azure_test_ephemeral_os.yml
  tests/integration/targets/azure_rm_virtualmachine/tasks/azure_test_public_ip.yml
  tests/integration/targets/azure_rm_virtualmachinescaleset/tasks/main.yml
  tests/integration/targets/inventory_azure/playbooks/setup.yml
  tests/integration/targets/inventory_azure/playbooks/test_inventory.yml
Labels: hold

#674 Correct doc for azure_rm_appgateway state
  plugins/modules/azure_rm_appgateway.py
Labels: documentation-pr, ready_for_review, medium_priority

#685 Add advanced routing/redirect support for application gateway
  plugins/modules/azure_rm_appgateway.py
  tests/integration/targets/azure_rm_appgateway/tasks/main.yml
Labels: ready_for_review, medium_priority

#611 Add new parameter proximity_placement_group
  plugins/modules/azure_rm_virtualmachine.py
  plugins/modules/azure_rm_virtualmachine_info.py
  tests/integration/targets/azure_rm_virtualmachine/tasks/azure_test_ephemeral_os.yml
Labels: ready_for_review, medium_priority, new_featrue

#589 Added Metadata support to azure_rm_dnsrecordset.py
  plugins/modules/azure_rm_dnsrecordset.py
  plugins/modules/azure_rm_dnsrecordset_info.py
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.11.txt
  tests/sanity/ignore-2.12.txt
  tests/sanity/ignore-2.9.txt
Labels: ready_for_review, medium_priority, new_featrue

#597 Add azure_rm_virtualhub*.py
  plugins/modules/azure_rm_virtualhub.py
  plugins/modules/azure_rm_virtualhub_info.py
  pr-pipelines.yml
  tests/integration/targets/azure_rm_virtualhub/aliases
  tests/integration/targets/azure_rm_virtualhub/meta/main.yml
  tests/integration/targets/azure_rm_virtualhub/tasks/main.yml
Labels: ready_for_review, new_module_pr, medium_priority

#682 Add managed disk ID to returned facts for data disks for azure_rm_virtualmachine_info
  plugins/modules/azure_rm_virtualmachine_info.py
Labels: ready_for_review, medium_priority

#673 Application gateway start/stop ability and info module
  plugins/modules/azure_rm_appgateway.py
  plugins/modules/azure_rm_appgateway_info.py
  tests/integration/targets/azure_rm_appgateway/tasks/main.yml
Labels: ready_for_review, medium_priority, new_featrue

#651 Add new feature for azure_rm_aks
  plugins/modules/azure_rm_aks.py
  tests/integration/targets/azure_rm_aks/tasks/minimal-cluster.yml
Labels: ready_for_review, medium_priority

#709 Correct cosmosdb info module when loading by resource group
  plugins/modules/azure_rm_cosmosdbaccount_info.py
  tests/integration/targets/azure_rm_cosmosdbaccount/tasks/main.yml
Labels: ready_for_review, medium_priority

#704 New Module : azure_rm_hostgroup
  plugins/modules/azure_rm_hostgroup.py
  plugins/modules/azure_rm_hostgroup_info.py
  pr-pipelines.yml
  tests/integration/targets/azure_rm_hostgroup/aliases
  tests/integration/targets/azure_rm_hostgroup/meta/main.yml
  tests/integration/targets/azure_rm_hostgroup/tasks/main.yml
Labels: ready_for_review, new_module_pr, medium_priority

#689 Add module for private endpoint DNS zone groups
  plugins/modules/azure_rm_privateendpoint.py
  plugins/modules/azure_rm_privateendpointdnszonegroup.py
  plugins/modules/azure_rm_privateendpointdnszonegroup_info.py
  pr-pipelines.yml
  tests/integration/targets/azure_rm_privateendpointdnszonegroup/aliases
  tests/integration/targets/azure_rm_privateendpointdnszonegroup/meta/main.yml
  tests/integration/targets/azure_rm_privateendpointdnszonegroup/tasks/main.yml
Labels: ready_for_review, new_module_pr, medium_priority

#701 Add new monitor diagnostic setting modules
  plugins/module_utils/azure_rm_common.py
  plugins/module_utils/azure_rm_common_ext.py
  plugins/modules/azure_rm_autoscale.py
  plugins/modules/azure_rm_autoscale_info.py
  plugins/modules/azure_rm_monitordiagnosticsetting.py
  plugins/modules/azure_rm_monitordiagnosticsetting_info.py
  plugins/modules/azure_rm_monitorlogprofile.py
  pr-pipelines.yml
  requirements-azure.txt
  tests/integration/targets/azure_rm_monitordiagnosticsetting/aliases
  tests/integration/targets/azure_rm_monitordiagnosticsetting/meta/main.yml
  tests/integration/targets/azure_rm_monitordiagnosticsetting/tasks/main.yml
  tests/integration/targets/azure_rm_monitorlogprofile/tasks/main.yml
Labels: ready_for_review, new_module_pr, medium_priority
