Repository ansible-collections/azure, pull requests merged in 2022-11, with the labels that each got.

#936 New module to create/update/delete/attach multiple disks
  meta/runtime.yml
  plugins/module_utils/azure_rm_common.py
  plugins/modules/azure_rm_multiplemanageddisks.py
  pr-pipelines.yml
  tests/integration/targets/azure_rm_multiplemanageddisks/aliases
  tests/integration/targets/azure_rm_multiplemanageddisks/defaults/main.yml
  tests/integration/targets/azure_rm_multiplemanageddisks/meta/main.yml
  tests/integration/targets/azure_rm_multiplemanageddisks/tasks/main.yml
  tests/integration/targets/azure_rm_multiplemanageddisks/tasks/test_async.yml
  tests/integration/targets/azure_rm_multiplemanageddisks/tasks/test_shared.yml
  tests/integration/targets/azure_rm_multiplemanageddisks/templates/disk_config.j2
Labels: new_module_pr, medium_priority, work in

#943 Upgrade azure-mgmt-apimanagement to 3.0.0
  requirements-azure.txt
Labels: ready_for_review, medium_priority

#979 Update azure_rm_openshiftmanagedcluster.py
  plugins/modules/azure_rm_openshiftmanagedcluster.py
Labels: ready_for_review, medium_priority

#986 Fix Ansible azure_rm_deployment module returns error but deployment i…
  plugins/modules/azure_rm_deployment.py
Labels: ready_for_review, medium_priority

#975 support for environment variable ANSIBLE_AZURE_VM_RESOURCE_GROUPS
  plugins/inventory/azure_rm.py
Labels: ready_for_review, inventory, medium_priority

#984 Ensure trailing slash on base_url
  plugins/module_utils/azure_rm_common.py
Labels: ready_for_review, medium_priority, work in
