Repository ansible-collections/azure, pull requests merged in 2022-08, with the labels that each got.

#922 Add new module `azure_rm_account_info` to get facts for current logged in user
  plugins/modules/azure_rm_account_info.py
  tests/integration/targets/azure_rm_account_info/aliases
  tests/integration/targets/azure_rm_account_info/meta/main.yml
  tests/integration/targets/azure_rm_account_info/tasks/main.yml
Labels: ready_for_review, new_module_pr, medium_priority

#925 Add missing parameters
  plugins/modules/azure_rm_manageddisk.py
Labels: ready_for_review, medium_priority

#930 Adding missing functionality to azure_rm_keyvaultkey
  plugins/modules/azure_rm_keyvaultkey.py
  tests/integration/targets/azure_rm_keyvaultkey/tasks/main.yml
Labels: ready_for_review, medium_priority, new_featrue

#931 Add missing account type of Standard_GZRS and Standard_RAGZRS
  plugins/modules/azure_rm_storageaccount.py
Labels: ready_for_review, medium_priority

#933 Add new parameters to azure_rm_virtualmachine
  plugins/modules/azure_rm_virtualmachine.py
Labels: ready_for_review, medium_priority

#937 Add new parameter to azure_rm_storageaccount
  plugins/modules/azure_rm_storageaccount.py
  plugins/modules/azure_rm_storageaccount_info.py
  tests/integration/targets/azure_rm_storageaccount/tasks/main.yml
Labels: ready_for_review, medium_priority

#894 Fix azurerm MSI authentication with other Azure Cloud
  plugins/module_utils/azure_rm_common.py
Labels: ready_for_review, medium_priority

#946 Fix a sanity error
  plugins/module_utils/azure_rm_common.py
Labels: ready_for_review, medium_priority

#945 Upgrade azure-mgmt-cdn to 11.0.0
  plugins/modules/azure_rm_cdnendpoint.py
  plugins/modules/azure_rm_cdnendpoint_info.py
  plugins/modules/azure_rm_cdnprofile.py
  plugins/modules/azure_rm_cdnprofile_info.py
  requirements-azure.txt
Labels: ready_for_review, medium_priority

#939 Add vhub connection module
  plugins/modules/azure_rm_virtualhubconnection.py
  plugins/modules/azure_rm_virtualhubconnection_info.py
  pr-pipelines.yml
  tests/integration/targets/azure_rm_virtualhubconnection/aliases
  tests/integration/targets/azure_rm_virtualhubconnection/meta/main.yml
  tests/integration/targets/azure_rm_virtualhubconnection/tasks/main.yml
Labels: ready_for_review, new_module_pr, medium_priority

#948 Upgrade azure-mgmt-managedservices to 6.0.0
  plugins/modules/azure_rm_registrationassignment.py
  plugins/modules/azure_rm_registrationassignment_info.py
  plugins/modules/azure_rm_registrationdefinition.py
  plugins/modules/azure_rm_registrationdefinition_info.py
  requirements-azure.txt
  tests/integration/targets/azure_rm_registrationdefinition/tasks/main.yml
Labels: ready_for_review, medium_priority

#951 Upgrade hdinsight dependence to 9.0.0
  plugins/modules/azure_rm_hdinsightcluster.py
  plugins/modules/azure_rm_hdinsightcluster_info.py
  requirements-azure.txt
Labels: ready_for_review, medium_priority

#955 Upgrade azure-mgmt-authorizaiton to 2.0.0
  plugins/module_utils/azure_rm_common.py
  plugins/modules/azure_rm_roleassignment.py
  plugins/modules/azure_rm_roleassignment_info.py
  plugins/modules/azure_rm_roledefinition.py
  plugins/modules/azure_rm_roledefinition_info.py
  requirements-azure.txt
Labels: ready_for_review, medium_priority

#952 Upgrade azure-mgmt-cosmosdb to 6.4.0
  plugins/modules/azure_rm_cosmosdbaccount.py
  plugins/modules/azure_rm_cosmosdbaccount_info.py
  requirements-azure.txt
  tests/integration/targets/azure_rm_cosmosdbaccount/tasks/main.yml
Labels: ready_for_review, medium_priority

#962 Correct firewall action examples
  plugins/modules/azure_rm_azurefirewall.py
Labels: documentation-pr, ready_for_review

#964 Update azure_rm_webappaccessrestriction test case
  plugins/modules/azure_rm_webappaccessrestriction.py
  tests/integration/targets/azure_rm_webappaccessrestriction/tasks/main.yml
Labels: ready_for_review, medium_priority
