Repository ansible-collections/azure, pull requests merged in 2022-12, with the labels that each got.

#1012 Docs: typo in os_disk_size_gb description
  plugins/modules/azure_rm_virtualmachine.py
Labels: documentation-pr, ready_for_review, medium_priority

#990 Add features to azure_rm_appgateway
  .gitignore
  plugins/modules/azure_rm_appgateway.py
  tests/integration/targets/azure_rm_appgateway/files/cert3b64.txt
  tests/integration/targets/azure_rm_appgateway/tasks/main.yml
Labels: ready_for_review, medium_priority, new_featrue

#1038 Format the md5 value returned by azure_rm_storageblob.py
  plugins/modules/azure_rm_storageblob.py
Labels: ready_for_review, medium_priority

#1027 Add a module to create Elastic Pool
  plugins/modules/azure_rm_sqlelasticpool.py
  plugins/modules/azure_rm_sqlelasticpool_info.py
  tests/integration/targets/azure_rm_sqlserver/tasks/main.yml
Labels: ready_for_review, new_module_pr, medium_priority
