Repository ansible-collections/azure, pull requests merged in 2022-07, with the labels that each got.

#908 Fix the azure_rm_publicaddress module small bug
  plugins/modules/azure_rm_publicipaddress.py
Labels: ready_for_review

#907 Update azure-mgmt-core to v1.3.0
  requirements-azure.txt
Labels: ready_for_review, medium_priority

#910 Added prompt to install virtual environment in README. md
  README.md
Labels: ready_for_review, medium_priority

#896 Upgrade azure-mgmt-search to 8.0.0
  plugins/module_utils/azure_rm_common.py
  plugins/modules/azure_rm_cognitivesearch.py
  plugins/modules/azure_rm_cognitivesearch_info.py
  requirements-azure.txt
  tests/integration/targets/azure_rm_cognitivesearch/tasks/main.yml
Labels: ready_for_review, medium_priority

#913 After deleting storageshare, pause it for 3 minutes
  tests/integration/targets/azure_rm_storageshare/tasks/main.yml
Labels: ready_for_review, high_priority

#909 Add multi task support to attach manageddisk on VM
  plugins/modules/azure_rm_manageddisk.py
Labels: ready_for_review

#854 Fixes required for use with multiple Cloud Environments
  plugins/module_utils/azure_rm_common.py
  plugins/modules/azure_rm_keyvaultkey.py
  plugins/modules/azure_rm_keyvaultkey_info.py
  plugins/modules/azure_rm_keyvaultsecret.py
  plugins/modules/azure_rm_keyvaultsecret_info.py
Labels: ready_for_review, medium_priority

#880 Upgrade azure-mgmt-privatedns to 1.0.0
  plugins/module_utils/azure_rm_common.py
  plugins/modules/azure_rm_privatednsrecordset.py
  plugins/modules/azure_rm_privatednsrecordset_info.py
  plugins/modules/azure_rm_privatednszone.py
  plugins/modules/azure_rm_privatednszone_info.py
  plugins/modules/azure_rm_privatednszonelink.py
  plugins/modules/azure_rm_privatednszonelink_info.py
  requirements-azure.txt
Labels: ready_for_review, medium_priority

#874 Adding an all group for module_defaults
  meta/runtime.yml
Labels: ready_for_review, high_priority

#881 Upgrade azure-mgmt-containerservice to 20.0.0
  plugins/module_utils/azure_rm_common.py
  plugins/modules/azure_rm_aks.py
  plugins/modules/azure_rm_aks_info.py
  plugins/modules/azure_rm_aksupgrade_info.py
  requirements-azure.txt
Labels: ready_for_review, medium_priority

#882 Upgrade azure-mgmt-containerinstance to 9.0.0
  plugins/module_utils/azure_rm_common.py
  plugins/modules/azure_rm_containerinstance.py
  plugins/modules/azure_rm_containerinstance_info.py
  requirements-azure.txt
Labels: ready_for_review, medium_priority

#884 Upgrade azure-mgmt-rdbms to 10.0.0
  plugins/module_utils/azure_rm_common.py
  plugins/modules/azure_rm_mariadbconfiguration.py
  plugins/modules/azure_rm_mariadbconfiguration_info.py
  plugins/modules/azure_rm_mariadbdatabase.py
  plugins/modules/azure_rm_mariadbdatabase_info.py
  plugins/modules/azure_rm_mariadbfirewallrule.py
  plugins/modules/azure_rm_mariadbfirewallrule_info.py
  plugins/modules/azure_rm_mariadbserver.py
  plugins/modules/azure_rm_mariadbserver_info.py
  plugins/modules/azure_rm_mysqlconfiguration.py
  plugins/modules/azure_rm_mysqlconfiguration_info.py
  plugins/modules/azure_rm_mysqldatabase.py
  plugins/modules/azure_rm_mysqldatabase_info.py
  plugins/modules/azure_rm_mysqlfirewallrule.py
  plugins/modules/azure_rm_mysqlfirewallrule_info.py
  plugins/modules/azure_rm_mysqlserver.py
  plugins/modules/azure_rm_mysqlserver_info.py
  plugins/modules/azure_rm_postgresqlconfiguration.py
  plugins/modules/azure_rm_postgresqlconfiguration_info.py
  plugins/modules/azure_rm_postgresqldatabase.py
  plugins/modules/azure_rm_postgresqldatabase_info.py
  plugins/modules/azure_rm_postgresqlfirewallrule.py
  plugins/modules/azure_rm_postgresqlfirewallrule_info.py
  plugins/modules/azure_rm_postgresqlserver.py
  plugins/modules/azure_rm_postgresqlserver_info.py
  requirements-azure.txt
  tests/integration/targets/azure_rm_mariadbserver/tasks/main.yml
  tests/integration/targets/azure_rm_mysqlserver/tasks/main.yml
  tests/integration/targets/azure_rm_postgresqlserver/tasks/main.yml
Labels: ready_for_review, medium_priority

#886 Upgrade azure-mgmt-trafficmanager to 1.0.0
  plugins/module_utils/azure_rm_common.py
  plugins/modules/azure_rm_trafficmanager.py
  plugins/modules/azure_rm_trafficmanagerendpoint.py
  plugins/modules/azure_rm_trafficmanagerendpoint_info.py
  plugins/modules/azure_rm_trafficmanagerprofile.py
  plugins/modules/azure_rm_trafficmanagerprofile_info.py
  requirements-azure.txt
Labels: ready_for_review, medium_priority

#889 Upgrade azure-mgmt-servicebus to 7.1.0
  plugins/module_utils/azure_rm_common.py
  plugins/modules/azure_rm_servicebus.py
  plugins/modules/azure_rm_servicebus_info.py
  plugins/modules/azure_rm_servicebusqueue.py
  plugins/modules/azure_rm_servicebussaspolicy.py
  plugins/modules/azure_rm_servicebustopic.py
  plugins/modules/azure_rm_servicebustopicsubscription.py
  requirements-azure.txt
Labels: ready_for_review

#892 Upgrade azure-mgmt-iothub to 2.2.0
  plugins/module_utils/azure_rm_common.py
  plugins/modules/azure_rm_iothub.py
  plugins/modules/azure_rm_iothub_info.py
  plugins/modules/azure_rm_iothubconsumergroup.py
  requirements-azure.txt
Labels: ready_for_review

#898 Upgrade azure-mgmt-datalake-store to 1.0.0
  plugins/module_utils/azure_rm_common.py
  plugins/modules/azure_rm_datalakestore.py
  plugins/modules/azure_rm_datalakestore_info.py
  requirements-azure.txt
Labels: ready_for_review, medium_priority

#895 Upgrade azure-mgmt-recoveryservice relate dependence
  plugins/module_utils/azure_rm_common.py
  plugins/modules/azure_rm_backupazurevm.py
  plugins/modules/azure_rm_backupazurevm_info.py
  plugins/modules/azure_rm_backuppolicy.py
  plugins/modules/azure_rm_backuppolicy_info.py
  plugins/modules/azure_rm_recoveryservicesvault.py
  plugins/modules/azure_rm_recoveryservicesvault_info.py
  plugins/modules/azure_rm_vmbackuppolicy.py
  plugins/modules/azure_rm_vmbackuppolicy_info.py
  requirements-azure.txt
Labels: ready_for_review, medium_priority

#900 Upgrade azure-mgmt-eventhubs to 10.1.0
  plugins/module_utils/azure_rm_common.py
  plugins/modules/azure_rm_eventhub.py
  plugins/modules/azure_rm_eventhub_info.py
  requirements-azure.txt
Labels: ready_for_review, medium_priority

#899 Upgrade azure-mgmt-notificationhubs to 8.0.0
  plugins/module_utils/azure_rm_common.py
  plugins/modules/azure_rm_notificationhub.py
  plugins/modules/azure_rm_notificationhub_info.py
  requirements-azure.txt
Labels: ready_for_review, medium_priority

#904 Replace config with _config in azure_rm_common.py to support azure-mgmt-network latest version
  plugins/module_utils/azure_rm_common.py
  tests/integration/targets/azure_rm_privateendpoint/tasks/main.yml
Labels: question, ready_for_review, medium_priority

#906 Expose soft_delete_retention_in_days in Azure Key Vault module
  plugins/modules/azure_rm_keyvault.py
  plugins/modules/azure_rm_keyvault_info.py
  requirements-azure.txt
  tests/integration/targets/azure_rm_keyvault/tasks/main.yml
Labels: ready_for_review, medium_priority

#912 Fix the authorized_ip_ranges parameter being None
  plugins/modules/azure_rm_aks.py
Labels: ready_for_review, medium_priority

#921 Vpngw generation add
  CHANGELOG.md
  plugins/module_utils/azure_rm_common.py
  plugins/modules/azure_rm_virtualnetworkgateway.py
  tests/integration/targets/azure_rm_virtualnetworkgateway/tasks/main.yml
Labels: ready_for_review, medium_priority

#915 Remove started default parameters
  plugins/modules/azure_rm_virtualmachine.py
  tests/integration/targets/azure_rm_virtualmachine/tasks/azure_test_deallocate.yml
Labels: ready_for_review, medium_priority
