Repository ansible-collections/azure, pull requests merged in 2022-06, with the labels that each got.

#868 For Pipeline test fail
  tests/integration/targets/azure_rm_cognitivesearch/tasks/main.yml
  tests/integration/targets/azure_rm_iothub/tasks/main.yml
Labels: ready_for_review, high_priority

#870 Added MSI support for the Track2 SDK
  plugins/module_utils/azure_rm_common.py
Labels: ready_for_review, medium_priority

#859 Bump version to v1.13.0
  CHANGELOG.md
  galaxy.yml
Labels: ready_for_review

#872 Fix azure_rm_keyvault_info 'Resource' object has no attribute 'properties'
  plugins/modules/azure_rm_keyvault_info.py
Labels: ready_for_review, medium_priority

#705 New Module : azure_rm_firewallpolicy
  plugins/modules/azure_rm_firewallpolicy.py
  plugins/modules/azure_rm_firewallpolicy_info.py
  pr-pipelines.yml
  tests/integration/targets/azure_rm_firewallpolicy/aliases
  tests/integration/targets/azure_rm_firewallpolicy/meta/main.yml
  tests/integration/targets/azure_rm_firewallpolicy/tasks/main.yml
Labels: ready_for_review, new_module_pr, medium_priority

#830 Azure container registry tags
  plugins/module_utils/azure_rm_common.py
  plugins/modules/azure_rm_containerregistry.py
  plugins/modules/azure_rm_containerregistry_info.py
  plugins/modules/azure_rm_containerregistryreplication.py
  plugins/modules/azure_rm_containerregistryreplication_info.py
  plugins/modules/azure_rm_containerregistrytag.py
  plugins/modules/azure_rm_containerregistrytag_info.py
  plugins/modules/azure_rm_containerregistrywebhook.py
  plugins/modules/azure_rm_containerregistrywebhook_info.py
  pr-pipelines.yml
  requirements-azure.txt
  sanity-requirements-azure.txt
  tests/integration/targets/azure_rm_containerregistrytag/aliases
  tests/integration/targets/azure_rm_containerregistrytag/meta/main.yml
  tests/integration/targets/azure_rm_containerregistrytag/tasks/main.yml
Labels: ready_for_review, new_module_pr, medium_priority

#744 Add disable_outbound_snat configuration to azure_rm_loadbalancer module
  plugins/modules/azure_rm_loadbalancer.py
  tests/integration/targets/azure_rm_loadbalancer/tasks/main.yml
Labels: enhancement, ready_for_review, medium_priority, new_featrue

#865 Changed aad_profile.admin_group_object_ids to take a list of string
  plugins/modules/azure_rm_aks.py
Labels: ready_for_review, medium_priority

#855 Add support for ZRS disks in virtualdisk and manageddisk modules
  plugins/modules/azure_rm_manageddisk.py
  plugins/modules/azure_rm_virtualmachine.py
  tests/integration/targets/azure_rm_manageddisk/tasks/main.yml
  tests/integration/targets/azure_rm_virtualmachine/inventory.yml
  tests/integration/targets/azure_rm_virtualmachine/main.yml
  tests/integration/targets/azure_rm_virtualmachine/tasks/azure_test_minimal_manageddisk.yml
Labels: enhancement, ready_for_review, medium_priority

#833 Update Storage dependencies
  plugins/module_utils/azure_rm_common.py
  plugins/modules/azure_rm_storageaccount.py
  plugins/modules/azure_rm_storageblob.py
  plugins/modules/azure_rm_virtualmachine.py
  requirements-azure.txt
  tests/integration/targets/azure_rm_storageaccount/tasks/main.yml
  tests/integration/targets/azure_rm_storageblob/aliases
  tests/integration/targets/azure_rm_storageblob/tasks/main.yml
Labels: enhancement, ready_for_review, medium_priority

#878 Configure static website on storage account
  plugins/modules/azure_rm_storageaccount.py
  plugins/modules/azure_rm_storageaccount_info.py
  tests/integration/targets/azure_rm_storageaccount/tasks/main.yml
Labels: ready_for_review, medium_priority

#876 If the disk exists, obtain unconfigured parameters
  plugins/modules/azure_rm_manageddisk.py
Labels: ready_for_review, medium_priority

#857 Fixing issue #856 with deployment info for a resource group and adding supporting test
  plugins/modules/azure_rm_deployment_info.py
  tests/integration/targets/azure_rm_deployment/tasks/main.yml
Labels: ready_for_review, medium_priority

#849 Update azure.mgmt.web
  plugins/module_utils/azure_rm_common.py
  plugins/modules/azure_rm_appserviceplan.py
  plugins/modules/azure_rm_appserviceplan_info.py
  plugins/modules/azure_rm_functionapp.py
  plugins/modules/azure_rm_functionapp_info.py
  plugins/modules/azure_rm_webapp.py
  plugins/modules/azure_rm_webapp_info.py
  plugins/modules/azure_rm_webappaccessrestriction.py
  plugins/modules/azure_rm_webappaccessrestriction_info.py
  plugins/modules/azure_rm_webappslot.py
  plugins/modules/azure_rm_webappvnetconnection.py
  requirements-azure.txt
  tests/integration/targets/azure_rm_webapp/tasks/main.yml
Labels: enhancement, ready_for_review, medium_priority

#858 Add some module relate with private link service
  plugins/modules/azure_rm_privateendpointconnection.py
  plugins/modules/azure_rm_privateendpointconnection_info.py
  plugins/modules/azure_rm_privatelinkservice.py
  plugins/modules/azure_rm_privatelinkservice_info.py
  pr-pipelines.yml
  tests/integration/targets/azure_rm_privatelinkservice/aliases
  tests/integration/targets/azure_rm_privatelinkservice/meta/main.yml
  tests/integration/targets/azure_rm_privatelinkservice/tasks/main.yml
Labels: ready_for_review, new_module_pr, medium_priority

#860 Add new module for Azure NAT gateway
  plugins/modules/azure_rm_natgateway.py
  plugins/modules/azure_rm_natgateway_info.py
  plugins/modules/azure_rm_subnet.py
  plugins/modules/azure_rm_subnet_info.py
  pr-pipelines.yml
  tests/integration/targets/azure_rm_natgateway/aliases
  tests/integration/targets/azure_rm_natgateway/meta/main.yml
  tests/integration/targets/azure_rm_natgateway/tasks/main.yml
Labels: ready_for_review, new_module_pr, medium_priority

#873 Add azure_rm_bastionhost module
  plugins/modules/azure_rm_bastionhost.py
  plugins/modules/azure_rm_bastionhost_info.py
  pr-pipelines.yml
  tests/integration/targets/azure_rm_bastionhost/aliases
  tests/integration/targets/azure_rm_bastionhost/meta/main.yml
  tests/integration/targets/azure_rm_bastionhost/tasks/main.yml
Labels: ready_for_review, new_module_pr, medium_priority

#875 Update storage account to allow configuration of public network access
  plugins/modules/azure_rm_storageaccount.py
  plugins/modules/azure_rm_storageaccount_info.py
  tests/integration/targets/azure_rm_storageaccount/tasks/main.yml
Labels: ready_for_review, new_featrue

#877 Add required option when importing a disk image
  plugins/modules/azure_rm_manageddisk.py
Labels: ready_for_review, medium_priority

#879 Upgrade azure-mgmt-dns to 8.0.0
  plugins/module_utils/azure_rm_common.py
  plugins/modules/azure_rm_dnsrecordset.py
  plugins/modules/azure_rm_dnsrecordset_info.py
  plugins/modules/azure_rm_dnszone.py
  plugins/modules/azure_rm_dnszone_info.py
  requirements-azure.txt
  tests/integration/targets/azure_rm_dnszone/tasks/main.yml
Labels: ready_for_review, medium_priority
