Repository ansible-collections/azure, pull requests merged in 2022-01, with the labels that each got.

#718 Avoid the case where server returns None
  plugins/modules/azure_rm_notificationhub.py
  plugins/modules/azure_rm_notificationhub_info.py
  tests/integration/targets/azure_rm_notificationhub/tasks/main.yml
Labels: ready_for_review, medium_priority

#610 common: Handle exception raised while loading profile
  plugins/module_utils/azure_rm_common.py
Labels: ready_for_review, medium_priority

#716 Clarify doc for installing collection and dependencies
  README.md
Labels: documentation-pr, ready_for_review

#641 azure_rm_deployment : fixed tags related bug
  plugins/modules/azure_rm_deployment.py
Labels: ready_for_review, medium_priority

#603 Azure storage file share module
  plugins/modules/azure_rm_storageshare.py
  plugins/modules/azure_rm_storageshare_info.py
  pr-pipelines.yml
  tests/integration/targets/azure_rm_storageshare/aliases
  tests/integration/targets/azure_rm_storageshare/meta/main.yml
  tests/integration/targets/azure_rm_storageshare/tasks/main.yml
Labels: ready_for_review, new_module_pr, medium_priority

#727 Dissociate routetable from subnet
  plugins/modules/azure_rm_subnet.py
  tests/integration/targets/azure_rm_cosmosdbaccount/tasks/main.yml
  tests/integration/targets/azure_rm_subnet/tasks/main.yml
Labels: ready_for_review, medium_priority

#726 Align `azure_rm_securitygroup_info` return to match `azure_rm_securitygroup`
  plugins/modules/azure_rm_securitygroup.py
  plugins/modules/azure_rm_securitygroup_info.py
  tests/integration/targets/azure_rm_securitygroup/tasks/main.yml
Labels: ready_for_review, medium_priority

#676 Update CLI authorization mode in SDK Track2
  plugins/module_utils/azure_rm_common.py
Labels: ready_for_review, high_priority
