Repository ansible-collections/azure, pull requests merged in 2022-05, with the labels that each got.

#829 Add zones feature to azure_rm_publicipaddres module
  plugins/modules/azure_rm_publicipaddress.py
  plugins/modules/azure_rm_publicipaddress_info.py
  pr-pipelines.yml
  tests/integration/targets/azure_rm_publicipaddress/tasks/main.yml
Labels: ready_for_review, medium_priority, new_featrue

#832 Add hyper_v_generation feature to azure_rm_image module
  plugins/lookup/azure_keyvault_secret.py
  plugins/modules/azure_rm_image.py
  plugins/modules/azure_rm_image_info.py
  tests/integration/targets/azure_rm_image/tasks/main.yml
  tests/integration/targets/azure_rm_virtualmachine/tasks/azure_test_deallocate.yml
  tests/integration/targets/azure_rm_virtualmachine/tasks/azure_test_dual_nic.yml
  tests/integration/targets/azure_rm_virtualmachine/tasks/azure_test_no_public_ip.yml
  tests/integration/targets/azure_rm_virtualmachine/tasks/azure_test_public_ip.yml
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.11.txt
  tests/sanity/ignore-2.12.txt
  tests/sanity/ignore-2.13.txt
  tests/sanity/ignore-2.14.txt
  tests/sanity/ignore-2.9.txt
Labels: ready_for_review, medium_priority, new_featrue

#846 Correct documentation of return attribute for azure_rm_webapp
  plugins/modules/azure_rm_webapp.py
Labels: documentation-pr, ready_for_review, medium_priority, work in

#840 Add new module azure_rm_datafacotry
  plugins/module_utils/azure_rm_common.py
  plugins/modules/azure_rm_datafactory.py
  plugins/modules/azure_rm_datafactory_info.py
  plugins/modules/azure_rm_sqlserver.py
  pr-pipelines.yml
  requirements-azure.txt
  tests/integration/targets/azure_rm_datafactory/aliases
  tests/integration/targets/azure_rm_datafactory/meta/main.yml
  tests/integration/targets/azure_rm_datafactory/tasks/main.yml
Labels: ready_for_review, new_module_pr, medium_priority

#853 When zones is null, there is no need to compare.
  plugins/modules/azure_rm_virtualmachine.py
Labels: ready_for_review, medium_priority

#851 Update vmss parameters default value
  plugins/modules/azure_rm_virtualmachinescaleset.py
  tests/integration/targets/azure_rm_virtualmachinescaleset/tasks/main.yml
Labels: enhancement, ready_for_review, medium_priority
