Repository ansible-collections/azure, pull requests merged in 2022-02, with the labels that each got.

#613 Fixed mismatch assignment error
  plugins/modules/azure_rm_roleassignment.py
Labels: ready_for_review, medium_priority

#735 Add private_dns_zone_id for azure_rm_privateendpointdnszonegroup
  plugins/modules/azure_rm_privateendpointdnszonegroup.py
Labels: enhancement, ready_for_review, medium_priority, new_featrue

#580 Ignore comparing protected_settings
  plugins/modules/azure_rm_virtualmachine.py
  plugins/modules/azure_rm_virtualmachineextension.py
  plugins/modules/azure_rm_virtualmachineextension_info.py
  plugins/modules/azure_rm_virtualmachinescaleset.py
  tests/integration/targets/azure_rm_virtualmachineextension/files/test-protected-settings.json
  tests/integration/targets/azure_rm_virtualmachineextension/files/test-public-settings.json
  tests/integration/targets/azure_rm_virtualmachineextension/tasks/main.yml
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.11.txt
  tests/sanity/ignore-2.12.txt
  tests/sanity/ignore-2.13.txt
  tests/sanity/ignore-2.9.txt
Labels: enhancement, ready_for_review, medium_priority

#736 delete unnecessary backtick in readme
  README.md
Labels: documentation-pr, ready_for_review, medium_priority

#627 azure_rm_availabilityset: fix checkmode support
  plugins/modules/azure_rm_availabilityset.py
  tests/integration/targets/azure_rm_availabilityset/tasks/main.yml
Labels: ready_for_review, medium_priority

#654 Add new paramter to enable AAD profile
  plugins/modules/azure_rm_aks.py
  tests/integration/targets/azure_rm_aks/tasks/minimal-cluster.yml
Labels: ready_for_review, medium_priority, new_featrue

#624 Fix azure_rm_manageddisk caching comparison
  plugins/modules/azure_rm_manageddisk.py
Labels: ready_for_review, medium_priority

#752 #738 add mandatory field when updating IPAddress
  plugins/modules/azure_rm_publicipaddress.py
Labels: enhancement, ready_for_review, medium_priority

#751 Remove unused and deprecated VERSION import
  plugins/module_utils/azure_rm_common.py
Labels: ready_for_review, medium_priority

#729 Upgrade azure-mgmt-network to 19.1.0
  plugins/module_utils/azure_rm_common.py
  plugins/modules/azure_rm_appgateway.py
  plugins/modules/azure_rm_applicationsecuritygroup.py
  plugins/modules/azure_rm_applicationsecuritygroup_info.py
  plugins/modules/azure_rm_ddosprotectionplan.py
  plugins/modules/azure_rm_ddosprotectionplan_info.py
  plugins/modules/azure_rm_expressroute.py
  plugins/modules/azure_rm_expressroute_info.py
  plugins/modules/azure_rm_ipgroup.py
  plugins/modules/azure_rm_ipgroup_info.py
  plugins/modules/azure_rm_loadbalancer.py
  plugins/modules/azure_rm_loadbalancer_info.py
  plugins/modules/azure_rm_networkinterface.py
  plugins/modules/azure_rm_networkinterface_info.py
  plugins/modules/azure_rm_privateendpoint.py
  plugins/modules/azure_rm_privateendpoint_info.py
  plugins/modules/azure_rm_privateendpointdnszonegroup.py
  plugins/modules/azure_rm_privateendpointdnszonegroup_info.py
  plugins/modules/azure_rm_publicipaddress.py
  plugins/modules/azure_rm_publicipaddress_info.py
  plugins/modules/azure_rm_rediscache.py
  plugins/modules/azure_rm_route.py
  plugins/modules/azure_rm_route_info.py
  plugins/modules/azure_rm_routetable.py
  plugins/modules/azure_rm_routetable_info.py
  plugins/modules/azure_rm_securitygroup.py
  plugins/modules/azure_rm_securitygroup_info.py
  plugins/modules/azure_rm_subnet.py
  plugins/modules/azure_rm_subnet_info.py
  plugins/modules/azure_rm_virtualhub.py
  plugins/modules/azure_rm_virtualhub_info.py
  plugins/modules/azure_rm_virtualmachine.py
  plugins/modules/azure_rm_virtualmachinescaleset.py
  plugins/modules/azure_rm_virtualnetwork.py
  plugins/modules/azure_rm_virtualnetwork_info.py
  plugins/modules/azure_rm_virtualnetworkgateway.py
  plugins/modules/azure_rm_virtualnetworkpeering.py
  plugins/modules/azure_rm_virtualnetworkpeering_info.py
  plugins/modules/azure_rm_virtualwan.py
  plugins/modules/azure_rm_virtualwan_info.py
  plugins/modules/azure_rm_vpnsite.py
  plugins/modules/azure_rm_vpnsite_info.py
  plugins/modules/azure_rm_vpnsitelink_info.py
  requirements-azure.txt
  tests/integration/targets/azure_rm_virtualnetworkgateway/tasks/main.yml
  tests/integration/targets/azure_rm_virtualwan/tasks/main.yml
Labels: ready_for_review, medium_priority

#623 azure_rm_sqldatabase: parse datetime module arguments
  plugins/modules/azure_rm_sqldatabase.py
  plugins/modules/azure_rm_sqldatabase_info.py
  tests/integration/targets/azure_rm_sqlserver/tasks/main.yml
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.11.txt
  tests/sanity/ignore-2.12.txt
  tests/utils/ado/ado.sh
Labels: ready_for_review, medium_priority

#770 Conditionally call non MSI auth when interacting with keyvault
  plugins/modules/azure_rm_keyvaultkey.py
  plugins/modules/azure_rm_keyvaultkey_info.py
  plugins/modules/azure_rm_keyvaultsecret.py
  plugins/modules/azure_rm_keyvaultsecret_info.py
Labels: ready_for_review, medium_priority
