Repository ansible-collections/azure, pull requests merged in 2022-10, with the labels that each got.

#998 Add new parameter is_hns_enabled to azure_rm_storageaccount.py
  plugins/modules/azure_rm_storageaccount.py
  plugins/modules/azure_rm_storageaccount_info.py
  tests/integration/targets/azure_rm_storageaccount/tasks/main.yml
Labels: ready_for_review, medium_priority

#1001 Fix a bug in the scheduled task
  plugins/modules/azure_rm_keyvault.py
  plugins/modules/azure_rm_keyvault_info.py
  plugins/modules/azure_rm_keyvaultkey.py
  plugins/modules/azure_rm_keyvaultkey_info.py
  plugins/modules/azure_rm_keyvaultsecret.py
  plugins/modules/azure_rm_keyvaultsecret_info.py
  plugins/modules/azure_rm_virtualmachinescaleset.py
  requirements-azure.txt
  sanity-requirements-azure.txt
  tests/integration/targets/azure_rm_aksagentpool/tasks/main.yml
  tests/integration/targets/azure_rm_bastionhost/tasks/main.yml
Labels: medium_priority, work in

#902 [Feature] Enable certificate-based authentication with login with Service principal
  plugins/doc_fragments/azure.py
  plugins/module_utils/azure_rm_common.py
Labels: enhancement, ready_for_review, new_featrue

#1000 Bump version to v1.14.0
  CHANGELOG.md
  galaxy.yml
Labels: ready_for_review, medium_priority
