Repository ansible-collections/azure, pull requests merged in 2022-04, with the labels that each got.

#797 Add new module azure_rm_automationrunbook
  plugins/modules/azure_rm_automationrunbook.py
  plugins/modules/azure_rm_automationrunbook_info.py
  pr-pipelines.yml
  tests/integration/targets/azure_rm_automationrunbook/aliases
  tests/integration/targets/azure_rm_automationrunbook/meta/main.yml
  tests/integration/targets/azure_rm_automationrunbook/tasks/main.yml
Labels: ready_for_review, medium_priority

#804 Add license type for RHEL/SLES Azure Hybrid Benefit
  plugins/modules/azure_rm_virtualmachine.py
Labels: enhancement, ready_for_review, medium_priority

#814 Update the document to meet the change requirements of ansibe2.14
  plugins/doc_fragments/azure_rm.py
  plugins/modules/azure_rm_aks.py
  plugins/modules/azure_rm_cdnendpoint.py
  plugins/modules/azure_rm_datalakestore.py
  plugins/modules/azure_rm_dnszone.py
  plugins/modules/azure_rm_iothub.py
  plugins/modules/azure_rm_monitorlogprofile.py
  plugins/modules/azure_rm_mysqlserver.py
  plugins/modules/azure_rm_registrationdefinition.py
  plugins/modules/azure_rm_securitygroup.py
  plugins/modules/azure_rm_storageaccount.py
  plugins/modules/azure_rm_subscription_info.py
  plugins/modules/azure_rm_trafficmanagerendpoint.py
  plugins/modules/azure_rm_vpnsite.py
  plugins/modules/azure_rm_webapp.py
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.11.txt
  tests/sanity/ignore-2.12.txt
  tests/sanity/ignore-2.13.txt
Labels: ready_for_review

#817 Update azure_rm_appgateway_info to use track2 dependencies
  plugins/modules/azure_rm_appgateway_info.py
Labels: ready_for_review, high_priority

#767 766 fixing azure rm virtualmachine top issue
  plugins/modules/azure_rm_virtualmachine.py
  tests/integration/targets/azure_rm_virtualmachine/tasks/azure_test_image_latest.yml
  tests/integration/targets/azure_rm_virtualmachine/tasks/azure_test_image_specific.yml
Labels: ready_for_review, medium_priority

#816 Sanity tests: copy ignore-2.13.txt to ignore-2.14.txt
  tests/sanity/ignore-2.14.txt
Labels: ready_for_review, high_priority

#779 Upgrade azure-mgmt-compute to v26.1.0
  plugins/modules/azure_rm_virtualmachinescaleset.py
  plugins/modules/azure_rm_virtualmachinescaleset_info.py
  requirements-azure.txt
  tests/integration/targets/azure_rm_virtualmachinescaleset/tasks/main.yml
Labels: enhancement, ready_for_review, medium_priority

#819 Update azure_rm_subscription_info tags element type
  plugins/modules/azure_rm_subscription_info.py
Labels: ready_for_review, medium_priority

#755 Add azure_rm_openshiftmanagedcluster_info module
  plugins/modules/azure_rm_openshiftmanagedcluster_info.py
  tests/integration/targets/azure_rm_openshiftmanagedcluster/tasks/main.yml
Labels: ready_for_review, new_module_pr, medium_priority

#621 Fix os_type comparison in azure_rm_manageddisk with existing disk
  plugins/modules/azure_rm_manageddisk.py
Labels: ready_for_review, medium_priority

#680 Update Redis modules
  plugins/modules/azure_rm_rediscache.py
  plugins/modules/azure_rm_rediscache_info.py
  plugins/modules/azure_rm_rediscachefirewallrule.py
  requirements-azure.txt
  tests/integration/targets/azure_rm_rediscache/tasks/main.yml
Labels: enhancement, ready_for_review, medium_priority, new_featrue

#109 Keyvault Lookup Plugin Added
  plugins/lookup/azure_keyvault_secret.py
Labels: ready_for_review, medium_priority, plugin

#746 Persist SSL configuration for appgateway
  plugins/modules/azure_rm_appgateway.py
  plugins/modules/azure_rm_appgateway_info.py
  tests/integration/targets/azure_rm_appgateway/tasks/main.yml
Labels: enhancement, ready_for_review, medium_priority, new_featrue

#822 Fix azure_rm_publicipaddress documentation page throws error
  plugins/modules/azure_rm_publicipaddress.py
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.11.txt
  tests/sanity/ignore-2.12.txt
  tests/sanity/ignore-2.13.txt
  tests/sanity/ignore-2.14.txt
Labels: documentation-pr, ready_for_review, medium_priority

#763 Install collection to local directory during development
  .gitignore
  CONTRIBUTING.md
  ansible.cfg
  galaxy.yml
Labels: medium_priority, work in

#747 Add rewrite rule capability to appgateway module
  plugins/modules/azure_rm_appgateway.py
  plugins/modules/azure_rm_appgateway_info.py
  tests/integration/targets/azure_rm_appgateway/tasks/main.yml
Labels: enhancement, ready_for_review, medium_priority, new_featrue

#825 Fix Ansible dev version Sanity error in plugin file
  plugins/lookup/azure_keyvault_secret.py
  plugins/modules/azure_rm_rediscache.py
  tests/sanity/ignore-2.14.txt
Labels: ready_for_review, medium_priority

#681 SQL Database enhancements
  plugins/module_utils/azure_rm_common.py
  plugins/modules/azure_rm_sqldatabase.py
  plugins/modules/azure_rm_sqldatabase_info.py
  plugins/modules/azure_rm_sqlfirewallrule.py
  plugins/modules/azure_rm_sqlfirewallrule_info.py
  plugins/modules/azure_rm_sqlserver.py
  plugins/modules/azure_rm_sqlserver_info.py
  requirements-azure.txt
  tests/integration/targets/azure_rm_sqlserver/tasks/main.yml
Labels: enhancement, ready_for_review, medium_priority, new_featrue

#823 Improved keyvault interaction auth_source=cli logic
  plugins/modules/azure_rm_keyvaultkey.py
  plugins/modules/azure_rm_keyvaultkey_info.py
  plugins/modules/azure_rm_keyvaultsecret.py
  plugins/modules/azure_rm_keyvaultsecret_info.py
Labels: enhancement, ready_for_review, medium_priority

#675 CosmosDB enhancements
  plugins/modules/azure_rm_cosmosdbaccount.py
  plugins/modules/azure_rm_cosmosdbaccount_info.py
  requirements-azure.txt
  tests/integration/targets/azure_rm_cosmosdbaccount/tasks/main.yml
Labels: enhancement, ready_for_review, new_featrue
