Repository ansible-collections/azure, pull requests merged in 2022-03, with the labels that each got.

#772 Added the VM status detection mechanism
  plugins/modules/azure_rm_virtualmachine.py
  tests/integration/targets/azure_rm_containerinstance/tasks/main.yml
  tests/integration/targets/azure_rm_gallery/tasks/main.yml
  tests/integration/targets/inventory_azure/playbooks/vars.yml
Labels: ready_for_review, high_priority, medium_priority

#769 fix a typo error. related to #757
  plugins/module_utils/azure_rm_common.py
Labels: ready_for_review, medium_priority

#776 Update the backup region in the test case
  tests/integration/targets/azure_rm_cosmosdbaccount/tasks/main.yml
Labels: ready_for_review

#672 Ugrade azure-mgmt-compute SDK to track2
  plugins/module_utils/azure_rm_common.py
  plugins/modules/azure_rm_availabilityset.py
  plugins/modules/azure_rm_availabilityset_info.py
  plugins/modules/azure_rm_diskencryptionset.py
  plugins/modules/azure_rm_diskencryptionset_info.py
  plugins/modules/azure_rm_hostgroup.py
  plugins/modules/azure_rm_hostgroup_info.py
  plugins/modules/azure_rm_image.py
  plugins/modules/azure_rm_image_info.py
  plugins/modules/azure_rm_manageddisk.py
  plugins/modules/azure_rm_manageddisk_info.py
  plugins/modules/azure_rm_proximityplacementgroup.py
  plugins/modules/azure_rm_proximityplacementgroup_info.py
  plugins/modules/azure_rm_virtualmachine.py
  plugins/modules/azure_rm_virtualmachine_info.py
  plugins/modules/azure_rm_virtualmachineextension.py
  plugins/modules/azure_rm_virtualmachineextension_info.py
  plugins/modules/azure_rm_virtualmachineimage_info.py
  plugins/modules/azure_rm_virtualmachinescaleset.py
  plugins/modules/azure_rm_virtualmachinescaleset_info.py
  plugins/modules/azure_rm_virtualmachinescalesetextension.py
  plugins/modules/azure_rm_virtualmachinescalesetextension_info.py
  plugins/modules/azure_rm_virtualmachinescalesetinstance.py
  plugins/modules/azure_rm_virtualmachinescalesetinstance_info.py
  plugins/modules/azure_rm_virtualmachinesize_info.py
  requirements-azure.txt
Labels: enhancement, ready_for_review, medium_priority

#777 Upgrade azure-mgmt-storage to 19.0.0
  plugins/module_utils/azure_rm_common.py
  plugins/modules/azure_rm_storageaccount.py
  plugins/modules/azure_rm_storageaccount_info.py
  plugins/modules/azure_rm_storageshare.py
  plugins/modules/azure_rm_storageshare_info.py
  plugins/modules/azure_rm_virtualmachine.py
  requirements-azure.txt
  tests/integration/targets/azure_rm_storageaccount/tasks/main.yml
Labels: ready_for_review

#775 Update azure-cli-core to 2.34.0
  requirements-azure.txt
Labels: ready_for_review, medium_priority

#745 Fix VM info module for failed VM provisions
  plugins/modules/azure_rm_virtualmachine_info.py
Labels: enhancement, ready_for_review, medium_priority

#719 BugFix : Fixed documentation issue for azure_rm_loadbalancer_info
  plugins/modules/azure_rm_loadbalancer_info.py
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.11.txt
  tests/sanity/ignore-2.12.txt
  tests/sanity/ignore-2.13.txt
  tests/sanity/ignore-2.9.txt
Labels: documentation-pr, ready_for_review, medium_priority

#647 Update azure_rm_galleryimage.py to allow Hyper-V Generation
  plugins/modules/azure_rm_galleryimage.py
Labels: ready_for_review, medium_priority, new_featrue

#778 Fix ansible 2.13 sanity fail
  plugins/doc_fragments/azure_rm.py
  plugins/inventory/azure_rm.py
  tests/sanity/ignore-2.13.txt
Labels: ready_for_review, inventory

#733 Fixes for issue #732
  plugins/inventory/azure_rm.py
Labels: ready_for_review, medium_priority

#782 Bump version to v1.12.0
  CHANGELOG.md
  galaxy.yml
Labels: ready_for_review

#800 Fix forced update bug caused by azure_rm_loadbalancer obtaining subnet predefined value
  plugins/modules/azure_rm_loadbalancer.py
Labels: ready_for_review

#791 Upgrade azure-mgmt-automation to v1.0.0
  plugins/module_utils/azure_rm_common.py
  plugins/modules/azure_rm_automationaccount.py
  plugins/modules/azure_rm_automationaccount_info.py
  requirements-azure.txt
Labels: ready_for_review, medium_priority

#801 Add parameter zones to azure_rm_loadbalancer
  plugins/modules/azure_rm_loadbalancer.py
  plugins/modules/azure_rm_loadbalancer_info.py
  tests/integration/targets/azure_rm_loadbalancer/tasks/main.yml
Labels: ready_for_review, new_featrue
