Repository ansible-collections/azure, pull requests merged in 2023-01, with the labels that each got.

#1060 The default value is None if not configured
  plugins/modules/azure_rm_loadbalancer.py
Labels: ready_for_review, medium_priority

#1059 FIx typo and wrong indents in README
  README.md
Labels: documentation-pr, ready_for_review, medium_priority

#1065 Add compose support in inventory/azure_rm.py
  plugins/inventory/azure_rm.py
Labels: ready_for_review, medium_priority

#1064 azure_rm_securitygroup: improve idempotency for protocol
  plugins/modules/azure_rm_securitygroup.py
  tests/integration/targets/azure_rm_securitygroup/tasks/main.yml
Labels: ready_for_review, medium_priority

#1057 azure_rm_backupazurevm: add option for recovery point expiry time
  plugins/modules/azure_rm_backupazurevm.py
  tests/integration/targets/azure_rm_backupazurevm/tasks/main.yml
Labels: enhancement, ready_for_review, medium_priority

#1053 Add forgotten parameters to the test case
  plugins/modules/azure_rm_roleassignment.py
Labels: ready_for_review, medium_priority

#1058 azure_rm_privatednsrecordset: fix updating SOA record
  plugins/modules/azure_rm_privatednsrecordset.py
  tests/integration/targets/azure_rm_privatednsrecordset/tasks/main.yml
Labels: ready_for_review, medium_priority

#1052 azure_rm_dnsrecordset: fix updating SOA record
  plugins/modules/azure_rm_dnsrecordset.py
  tests/integration/targets/azure_rm_dnsrecordset/tasks/main.yml
Labels: ready_for_review, medium_priority

#1042 Keep action_groups and modules list consistent
  meta/runtime.yml
Labels: documentation-pr, ready_for_review, medium_priority

#1025 Add synchronizing of VNet peering when sync level is `LocalNotInSync`
  plugins/modules/azure_rm_virtualnetworkpeering.py
Labels: ready_for_review, medium_priority

#960 Upgrade azure-mgmt-resource to 21.1.0
  plugins/module_utils/azure_rm_common.py
  plugins/modules/azure_rm_deployment.py
  plugins/modules/azure_rm_deployment_info.py
  plugins/modules/azure_rm_lock.py
  plugins/modules/azure_rm_resourcegroup.py
  plugins/modules/azure_rm_resourcegroup_info.py
  plugins/modules/azure_rm_subscription_info.py
  plugins/modules/azure_rm_virtualmachine.py
  requirements-azure.txt
Labels: ready_for_review, medium_priority

#1039 Add azure_rm_sqlmanagedinstance module
  meta/runtime.yml
  plugins/modules/azure_rm_sqlmanagedinstance.py
  plugins/modules/azure_rm_sqlmanagedinstance_info.py
  pr-pipelines.yml
  tests/integration/targets/azure_rm_sqlmanagedinstance/aliases
  tests/integration/targets/azure_rm_sqlmanagedinstance/meta/main.yml
  tests/integration/targets/azure_rm_sqlmanagedinstance/tasks/main.yml
Labels: ready_for_review, new_module_pr, medium_priority

#1018 Make batch_upload honour "force" attribute in azure_rm_storageblob
  plugins/modules/azure_rm_storageblob.py
Labels: ready_for_review, medium_priority

#1036 Add flow_timeout_in_minutes to azure_rm_virtualnetwork
  plugins/modules/azure_rm_virtualnetwork.py
  plugins/modules/azure_rm_virtualnetwork_info.py
  tests/integration/targets/azure_rm_virtualnetwork/tasks/main.yml
Labels: ready_for_review, medium_priority
