Repository ansible-collections/azure, pull requests merged in 2023-07, with the labels that each got.

#1207 Fix setting of encryption at host for VMs
  plugins/modules/azure_rm_virtualmachine.py
Labels: ready_for_review, high_priority, medium_priority

#1205 Refs #1033 fix security profile for azure_rm_virtualmachine_info
  plugins/modules/azure_rm_virtualmachine_info.py
Labels: ready_for_review, high_priority

#1206 allow to set boot diagnostics storage account to managed
  plugins/modules/azure_rm_virtualmachine.py
Labels: question, ready_for_review, medium_priority

#1221 Add creation timestamp to hostvars
  plugins/inventory/azure_rm.py
Labels: ready_for_review, inventory, medium_priority

#1203 Improve Docs In `azure_rm_virtualnetwork`
  plugins/modules/azure_rm_virtualnetwork.py
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.11.txt
  tests/sanity/ignore-2.12.txt
  tests/sanity/ignore-2.13.txt
  tests/sanity/ignore-2.14.txt
Labels: documentation-pr, ready_for_review, medium_priority

#1216 Add new parameters to storageshare
  plugins/modules/azure_rm_storageshare.py
Labels: enhancement, ready_for_review, medium_priority

#1211 Add an example on how to add a domain to hostname for dynamic inventory
  plugins/inventory/azure_rm.py
Labels: ready_for_review, inventory
