Repository ansible-collections/azure, pull requests merged in 2023-08, with the labels that each got.

#1239 Migrate ADAL to MSAL
  plugins/module_utils/azure_rm_common.py
  requirements-azure.txt
Labels: enhancement, ready_for_review, high_priority, dependencies

#1202 Upgrade azure mgmt batch 17.0.0
  plugins/modules/azure_rm_batchaccount.py
  plugins/modules/azure_rm_batchaccount_info.py
  requirements-azure.txt
  tests/integration/targets/azure_rm_batchaccount/tasks/main.yml
Labels: enhancement, ready_for_review, medium_priority

#1229 Fix azure_rm_aks_info.py to list all manged cluster bug
  plugins/modules/azure_rm_aks_info.py
Labels: ready_for_review, medium_priority

#1175 removed subscription_id from azure_keyvault_secret lookup when using az cli auth
  plugins/lookup/azure_keyvault_secret.py
Labels: ready_for_review, medium_priority
