Repository ansible-collections/azure, pull requests merged in 2023-06, with the labels that each got.

#1172 Bump verison to v1.16.0
  CHANGELOG.md
  galaxy.yml
Labels: ready_for_review, medium_priority

#1180 Fix version_added in azure_rm_virtualmachine
  plugins/modules/azure_rm_virtualmachine.py
Labels: ready_for_review, medium_priority

#1189 Fix doc link in README
  README.md
Labels: documentation-pr, ready_for_review

#1188 Keep action_groups and modules list consistent for 1.15.0 and 1.16.0
  meta/runtime.yml
Labels: documentation-pr, ready_for_review, medium_priority

#1177 azure_rm_virtualmachine: better support for User Assigned and System Assigned identities
  plugins/modules/azure_rm_virtualmachine.py
  tests/integration/targets/azure_rm_virtualmachine/inventory.yml
  tests/integration/targets/azure_rm_virtualmachine/tasks/azure_test_vm_identity.yml
Labels: ready_for_review, medium_priority, new_featrue

#1186 Add option to force poweroff for VM
  plugins/modules/azure_rm_virtualmachine.py
Labels: ready_for_review, medium_priority

#1187 source_account_id should be storage_account_id
  plugins/modules/azure_rm_manageddisk.py
  plugins/modules/azure_rm_multiplemanageddisks.py
Labels: ready_for_review, medium_priority

#1198 Update azure keyvault to 4.2.0
  plugins/lookup/azure_keyvault_secret.py
  plugins/modules/azure_rm_keyvaultkey.py
  plugins/modules/azure_rm_keyvaultkey_info.py
  plugins/modules/azure_rm_keyvaultsecret.py
  plugins/modules/azure_rm_keyvaultsecret_info.py
  requirements-azure.txt
Labels: ready_for_review, medium_priority
