Repository ansible-collections/azure, pull requests merged in 2023-12, with the labels that each got.

#1344 Fix dynamic VM fetch failure when I(batch_fetch=true)
  plugins/inventory/azure_rm.py
Labels: ready_for_review, medium_priority

#1347 Support the include_host_filters
  plugins/doc_fragments/azure_rm.py
  plugins/inventory/azure_rm.py
Labels: ready_for_review, inventory, medium_priority

#1353 Added option for disabling MSI autodiscover feature in azure_keyvault_secret lookup plugin
  plugins/lookup/azure_keyvault_secret.py
Labels: ready_for_review, medium_priority

#1354 Adjust test cases to fix resource interuse issues
  plugins/modules/azure_rm_virtualmachine.py
  plugins/modules/azure_rm_virtualmachinescaleset.py
  tests/integration/targets/azure_rm_cdnprofile/tasks/main.yml
  tests/integration/targets/azure_rm_datalakestore/tasks/main.yml
  tests/integration/targets/azure_rm_registrationassignment/tasks/main.yml
  tests/integration/targets/azure_rm_registrationdefinition/tasks/main.yml
  tests/integration/targets/azure_rm_securitygroup/tasks/main.yml
  tests/integration/targets/azure_rm_trafficmanagerprofile/tasks/main.yml
  tests/integration/targets/azure_rm_virtualmachinescaleset/tasks/main.yml
  tests/integration/targets/inventory_azure/playbooks/setup.yml
  tests/integration/targets/inventory_azure/playbooks/test_inventory.yml
Labels: ready_for_review, high_priority

#1364 Compatible with two methods to obtaining azlogin credentials
  plugins/module_utils/azure_rm_common.py
Labels: ready_for_review, medium_priority

#1367 docs: Fixed azure_rm inventory markup
  plugins/doc_fragments/azure_rm.py
Labels: documentation-pr, ready_for_review, inventory

#1369 Fix function parameter passing error
  plugins/modules/azure_rm_adapplication.py
Labels: ready_for_review, medium_priority

#1214 Change the dynamically obtained public IP address to a list
  plugins/inventory/azure_rm.py
Labels: ready_for_review, medium_priority

#1362 Bump version to v2.1.0
  CHANGELOG.md
  galaxy.yml
Labels: ready_for_review, medium_priority

#1379 Restore the return of 'public_ipv4_address' and fix the bug that the VM does not have a public IP address
  plugins/inventory/azure_rm.py
Labels: ready_for_review, inventory, high_priority

#1374 Remove unneed waits in test cases
  plugins/modules/azure_rm_mysqldatabase.py
  plugins/modules/azure_rm_mysqldatabase_info.py
  tests/integration/targets/azure_rm_gallery/tasks/main.yml
  tests/integration/targets/azure_rm_virtualmachine/tasks/azure_test_deallocate.yml
  tests/integration/targets/azure_rm_virtualmachine/tasks/azure_test_dual_nic.yml
  tests/integration/targets/azure_rm_virtualmachine/tasks/azure_test_ephemeral_os.yml
  tests/integration/targets/azure_rm_virtualmachine/tasks/azure_test_public_ip.yml
  tests/integration/targets/azure_rm_virtualmachinescaleset/tasks/main.yml
  tests/integration/targets/inventory_azure/playbooks/setup.yml
Labels: ready_for_review, medium_priority

#1381 Add upper letter protocol to security group
  plugins/modules/azure_rm_securitygroup.py
Labels: ready_for_review
