Repository ansible-collections/azure, pull requests merged in 2023-03, with the labels that each got.

#1096 azure_rm_securitygroup is changed without actual changes when only capitalization differs
  plugins/modules/azure_rm_multiplemanageddisks.py
  plugins/modules/azure_rm_securitygroup.py
  tests/integration/targets/azure_rm_multiplemanageddisks/aliases
  tests/integration/targets/azure_rm_multiplemanageddisks/defaults/main.yml
  tests/integration/targets/azure_rm_multiplemanageddisks/tasks/test_async.yml
  tests/integration/targets/azure_rm_multiplemanageddisks/tasks/test_shared.yml
  tests/integration/targets/azure_rm_multiplemanageddisks/templates/disk_config.j2
  tests/integration/targets/azure_rm_securitygroup/tasks/main.yml
Labels: ready_for_review, medium_priority

#1102 fix typo module names in EXAMPLES for azure_rm_privatelinkservice_info
  plugins/modules/azure_rm_privatelinkservice_info.py
Labels: documentation-pr, ready_for_review, medium_priority

#1109 Bump version to v1.15.0
  CHANGELOG.md
  galaxy.yml
Labels: ready_for_review, medium_priority

#1129 Fixed return values in azure_rm_loganalyticsworkspace test cases
  tests/integration/targets/azure_rm_loganalyticsworkspace/tasks/main.yml
Labels: ready_for_review, medium_priority

#1117 Upgrade azure-mgmt-managements to 1.0.0
  plugins/module_utils/azure_rm_common.py
  plugins/modules/azure_rm_managementgroup.py
  plugins/modules/azure_rm_managementgroup_info.py
  requirements-azure.txt
Labels: ready_for_review, medium_priority, dependencies

#1128 linux webapp support python (#1124)
  plugins/modules/azure_rm_webapp.py
Labels: ready_for_review, medium_priority

#1114 Support tags to azure_rm_servicebus.py
  plugins/modules/azure_rm_servicebus.py
  plugins/modules/azure_rm_servicebusqueue.py
  plugins/modules/azure_rm_servicebussaspolicy.py
  plugins/modules/azure_rm_servicebustopic.py
  plugins/modules/azure_rm_servicebustopicsubscription.py
  tests/integration/targets/azure_rm_servicebus/tasks/main.yml
Labels: ready_for_review, medium_priority

#1077 add description for include_vm_resource_groups of inventory
  plugins/doc_fragments/azure_rm.py
Labels: documentation-pr, ready_for_review, medium_priority

#1079 Fix azure_rm_webapp fails when state is 'absent'
  plugins/modules/azure_rm_webapp.py
Labels: ready_for_review

#1097 Support notes to azure_rm_lock.py
  plugins/modules/azure_rm_lock.py
Labels: enhancement, ready_for_review, medium_priority, new_featrue

#1037 Fix azure_rm_networkinterface.py idempotent fail
  plugins/modules/azure_rm_networkinterface.py
Labels: ready_for_review, medium_priority

#1082 Update documentation of `azure_rm_virtualnetwork` to reflect that the `dns_servers` limit on length is no longer 2.
  plugins/modules/azure_rm_virtualnetwork.py
Labels: documentation-pr, ready_for_review, medium_priority
