Repository ansible-collections/azure, pull requests merged in 2023-11, with the labels that each got.

#1308 Update azurefirewall info returns
  plugins/modules/azure_rm_azurefirewall_info.py
Labels: enhancement, ready_for_review, medium_priority

#1314 Add required description to document
  plugins/modules/azure_rm_cdnendpoint.py
  plugins/modules/azure_rm_functionapp.py
  plugins/modules/azure_rm_galleryimage.py
  plugins/modules/azure_rm_galleryimageversion.py
  plugins/modules/azure_rm_mysqlfirewallrule.py
  plugins/modules/azure_rm_networkinterface.py
  plugins/modules/azure_rm_servicebussaspolicy.py
  plugins/modules/azure_rm_virtualmachine.py
  plugins/modules/azure_rm_virtualmachinescaleset.py
Labels: ready_for_review

#1319 Delete unnecessary required sets
  plugins/modules/azure_rm_galleryimageversion.py
  plugins/modules/azure_rm_virtualnetworkgateway.py
Labels: ready_for_review, medium_priority

#1315 Add auth_mode to azure_rm_storageblob
  plugins/module_utils/azure_rm_common.py
  plugins/modules/azure_rm_storageblob.py
  tests/integration/targets/azure_rm_storageblob/tasks/main.yml
Labels: enhancement, ready_for_review, medium_priority, new_featrue

#1324 Fix caching choices
  plugins/modules/azure_rm_virtualmachine.py
Labels: ready_for_review, high_priority, medium_priority

#1311 Add encryption to azure_rm_galleryimageversion
  plugins/modules/azure_rm_galleryimageversion.py
  tests/integration/targets/azure_rm_gallery/lookup_plugins/azure_service_principal_attribute.py
  tests/integration/targets/azure_rm_gallery/tasks/main.yml
Labels: ready_for_review, medium_priority, new_featrue

#1310 Add features to azure_rm_galleryimage
  plugins/modules/azure_rm_galleryimage.py
  tests/integration/targets/azure_rm_gallery/tasks/main.yml
Labels: ready_for_review, medium_priority, new_featrue

#1305 Add ansible-core v2.16
  pr-pipelines.yml
  tests/sanity/ignore-2.16.txt
Labels: ready_for_review, medium_priority, work in

#1327 API Management - Bump APIM API version to 2022-08-01
  plugins/modules/azure_rm_apimanagement.py
  plugins/modules/azure_rm_apimanagement_info.py
  plugins/modules/azure_rm_apimanagementservice.py
  plugins/modules/azure_rm_apimanagementservice_info.py
Labels: ready_for_review

#1307 Add hasattr method to verify return value
  plugins/modules/azure_rm_apimanagement.py
  plugins/modules/azure_rm_apimanagementservice.py
  plugins/modules/azure_rm_azurefirewall.py
  plugins/modules/azure_rm_backupazurevm.py
  plugins/modules/azure_rm_backupazurevm_info.py
  plugins/modules/azure_rm_gallery.py
  plugins/modules/azure_rm_galleryimage.py
  plugins/modules/azure_rm_galleryimageversion.py
  plugins/modules/azure_rm_managementgroup.py
  plugins/modules/azure_rm_openshiftmanagedcluster.py
  plugins/modules/azure_rm_recoveryservicesvault.py
  plugins/modules/azure_rm_recoveryservicesvault_info.py
  plugins/modules/azure_rm_resource.py
  plugins/modules/azure_rm_vmbackuppolicy.py
  plugins/modules/azure_rm_vmbackuppolicy_info.py
Labels: enhancement, ready_for_review

#1325 Migrate ADGraph to MSGraph
  plugins/module_utils/azure_rm_common.py
  plugins/modules/azure_rm_account_info.py
  plugins/modules/azure_rm_adapplication.py
  plugins/modules/azure_rm_adapplication_info.py
  plugins/modules/azure_rm_adgroup.py
  plugins/modules/azure_rm_adgroup_info.py
  plugins/modules/azure_rm_adpassword.py
  plugins/modules/azure_rm_adpassword_info.py
  plugins/modules/azure_rm_adserviceprincipal.py
  plugins/modules/azure_rm_adserviceprincipal_info.py
  plugins/modules/azure_rm_aduser.py
  plugins/modules/azure_rm_aduser_info.py
  requirements-azure.txt
  tests/utils/ado/ado.sh
Labels: ready_for_review

#1289 Add vm_agent_version to output of azure_rm_virtualmachine_info
  plugins/modules/azure_rm_virtualmachine_info.py
Labels: enhancement, ready_for_review, medium_priority

#1306 Add os_disk_encryption_set to azure_rm_virtualmachine
  .gitignore
  plugins/modules/azure_rm_virtualmachine.py
  tests/integration/targets/azure_rm_virtualmachine/inventory.yml
  tests/integration/targets/azure_rm_virtualmachine/lookup_plugins/azure_service_principal_attribute.py
  tests/integration/targets/azure_rm_virtualmachine/tasks/azure_test_encrypted.yml
  tests/integration/targets/azure_rm_virtualmachine/tasks/setup_des.yml
Labels: ready_for_review, medium_priority, new_featrue

#1309 Add disk_encryption_set for data disks in azure_rm_virtualmachine
  plugins/modules/azure_rm_virtualmachine.py
Labels: enhancement, ready_for_review, medium_priority

#1326 Move azure_service_principal_attribute.py to azure-collecitons lookup file
  plugins/lookup/azure_service_principal_attribute.py
  tests/integration/targets/azure_rm_diskencryptionset/tasks/main.yml
  tests/integration/targets/azure_rm_gallery/lookup_plugins/azure_service_principal_attribute.py
  tests/integration/targets/azure_rm_gallery/tasks/main.yml
  tests/integration/targets/azure_rm_keyvault/lookup_plugins/azure_service_principal_attribute.py
  tests/integration/targets/azure_rm_keyvault/tasks/main.yml
  tests/integration/targets/azure_rm_keyvaultkey/lookup_plugins/azure_service_principal_attribute.py
  tests/integration/targets/azure_rm_keyvaultkey/tasks/main.yml
  tests/integration/targets/azure_rm_keyvaultsecret/lookup_plugins/azure_service_principal_attribute.py
  tests/integration/targets/azure_rm_keyvaultsecret/tasks/main.yml
  tests/integration/targets/azure_rm_virtualmachine/tasks/azure_test_public_ip.yml
Labels: ready_for_review, medium_priority

#1318 Add azure_rm_accesstoken_info module
  plugins/modules/azure_rm_accesstoken_info.py
  tests/integration/targets/azure_rm_accesstoken_info/aliases
  tests/integration/targets/azure_rm_accesstoken_info/meta/main.yml
  tests/integration/targets/azure_rm_accesstoken_info/tasks/main.yml
Labels: ready_for_review, new_module_pr, medium_priority

#1278 Fix getting alias parameters fail on azure_rm_iotdevice.py
  plugins/modules/azure_rm_iotdevice.py
  plugins/modules/azure_rm_iotdevicemodule.py
Labels: ready_for_review, medium_priority

#1238 [New module] - Add openshiftmanagedcluster_kubeconfig_info module
  plugins/modules/azure_rm_openshiftmanagedclusterkubeconfig_info.py
  tests/integration/targets/azure_rm_openshiftmanagedcluster/tasks/main.yml
Labels: ready_for_review, new_module_pr, medium_priority

#1329 Support to update proximity_placement_group parameters
  plugins/modules/azure_rm_virtualmachine.py
Labels: ready_for_review, medium_priority

#1340 Fix the az login login to obtain the token error
  plugins/module_utils/azure_rm_common.py
  plugins/modules/azure_rm_adapplication.py
  plugins/modules/azure_rm_adapplication_info.py
  plugins/modules/azure_rm_adgroup.py
  plugins/modules/azure_rm_adgroup_info.py
  plugins/modules/azure_rm_adpassword.py
  plugins/modules/azure_rm_adpassword_info.py
  plugins/modules/azure_rm_adserviceprincipal.py
  plugins/modules/azure_rm_adserviceprincipal_info.py
  plugins/modules/azure_rm_aduser.py
  plugins/modules/azure_rm_aduser_info.py
Labels: ready_for_review, medium_priority

#1190 Support azure_rm_sshpublickey module to managed VM public keys
  plugins/modules/azure_rm_sshpublickey.py
  plugins/modules/azure_rm_sshpublickey_info.py
  pr-pipelines.yml
  tests/integration/targets/azure_rm_sshpublickey/aliases
  tests/integration/targets/azure_rm_sshpublickey/meta/main.yml
  tests/integration/targets/azure_rm_sshpublickey/tasks/main.yml
Labels: ready_for_review, medium_priority

#1201 Support unmount disk to VMs that not belong to the same resource group
  plugins/modules/azure_rm_manageddisk.py
Labels: ready_for_review, medium_priority

#1210 Add large_file_shares_state to azure_rm_storageaccount
  plugins/modules/azure_rm_storageaccount.py
  plugins/modules/azure_rm_storageaccount_info.py
  tests/integration/targets/azure_rm_storageaccount/tasks/main.yml
Labels: enhancement, ready_for_review, medium_priority

#1341 Fix failure on response with not json body
  plugins/modules/azure_rm_resource.py
Labels: ready_for_review, medium_priority

#1231 Fix azure_rm_deployment deletes the whole resource group in state absent
  plugins/modules/azure_rm_deployment.py
Labels: ready_for_review, medium_priority
