Repository ansible-collections/azure, pull requests merged in 2023-04, with the labels that each got.

#1132 Remove references to Redis 4 and support upgrading to Redis 6
  plugins/modules/azure_rm_rediscache.py
  plugins/modules/azure_rm_rediscache_info.py
  tests/integration/targets/azure_rm_rediscache/tasks/main.yml
Labels: enhancement, ready_for_review, medium_priority

#958 Upgrade azure-mgmt-devtestlabs to 9.0.0
  plugins/modules/azure_rm_devtestlab.py
  plugins/modules/azure_rm_devtestlab_info.py
  plugins/modules/azure_rm_devtestlabarmtemplate_info.py
  plugins/modules/azure_rm_devtestlabartifact_info.py
  plugins/modules/azure_rm_devtestlabartifactsource.py
  plugins/modules/azure_rm_devtestlabartifactsource_info.py
  plugins/modules/azure_rm_devtestlabcustomimage.py
  plugins/modules/azure_rm_devtestlabcustomimage_info.py
  plugins/modules/azure_rm_devtestlabenvironment.py
  plugins/modules/azure_rm_devtestlabenvironment_info.py
  plugins/modules/azure_rm_devtestlabpolicy.py
  plugins/modules/azure_rm_devtestlabpolicy_info.py
  plugins/modules/azure_rm_devtestlabschedule.py
  plugins/modules/azure_rm_devtestlabschedule_info.py
  plugins/modules/azure_rm_devtestlabvirtualmachine.py
  plugins/modules/azure_rm_devtestlabvirtualmachine_info.py
  plugins/modules/azure_rm_devtestlabvirtualnetwork.py
  plugins/modules/azure_rm_devtestlabvirtualnetwork_info.py
  pr-pipelines.yml
  requirements-azure.txt
  tests/integration/targets/azure_rm_devtestlab/aliases
  tests/integration/targets/azure_rm_devtestlab/meta/main.yml
  tests/integration/targets/azure_rm_devtestlab/tasks/main.yml
Labels: ready_for_review, medium_priority

#940 Upgrade azure-mgmt-marketplaceordering to 1.1.0
  plugins/module_utils/azure_rm_common.py
  plugins/modules/azure_rm_virtualmachine.py
  plugins/modules/azure_rm_virtualmachinescaleset.py
  requirements-azure.txt
Labels: ready_for_review, medium_priority

#1087 Update documentation in azure_rm_virtualnetwork_info and include a small change to match other patterns for getting network info.
  plugins/modules/azure_rm_virtualnetwork_info.py
Labels: documentation-pr, ready_for_review, medium_priority

#1085 Add `peering_sync_level` to return values of in `azure_rm_virtualnetworkpeering_info`
  plugins/modules/azure_rm_virtualnetworkpeering_info.py
Labels: documentation-pr, ready_for_review, medium_priority

#1090 Add subnet_ids to azure_rm_containerinstance.py
  plugins/modules/azure_rm_containerinstance.py
  plugins/modules/azure_rm_containerinstance_info.py
  tests/integration/targets/azure_rm_containerinstance/tasks/main.yml
Labels: ready_for_review, medium_priority

#1092 Add max_message_size_in_kilobytes to azure_rm_servicebusqueue.py
  plugins/modules/azure_rm_servicebusqueue.py
  plugins/modules/azure_rm_servicebustopic.py
  tests/integration/targets/azure_rm_servicebus/tasks/main.yml
Labels: ready_for_review, medium_priority

#1135 Add incremental to azure_rm_snapshot
  plugins/modules/azure_rm_snapshot.py
  tests/integration/targets/azure_rm_gallery/tasks/main.yml
Labels: ready_for_review, medium_priority, new_featrue

#1136 Add the type of managed_disk_type
  plugins/modules/azure_rm_virtualmachine.py
  plugins/modules/azure_rm_virtualmachinescaleset.py
Labels: ready_for_review, medium_priority
