Repository ansible-collections/azure, pull requests merged in 2024-05, with the labels that each got.

#1552 Rename dependent package file and delete azure suffix
  CONTRIBUTING.md
  README.md
  meta/execution-environment.yml
  plugins/doc_fragments/azure.py
  requirements.txt
  sanity-requirements.txt
  tests/utils/ado/ado.sh
Labels: ready_for_review, medium_priority

#1554 Fixed an issue where custom classes are inconsistent with Python SDK properties
  plugins/module_utils/azure_rm_common.py
Labels: ready_for_review, medium_priority

#1553 Keep action_groups and modules list consistent
  meta/runtime.yml
Labels: ready_for_review, medium_priority

#1550 Fixed spelling in azure_rm_rediscache_info.py
  plugins/modules/azure_rm_rediscache_info.py
Labels: documentation-pr, ready_for_review, medium_priority

#1547 Expand Inventory filter integration tests
  tests/integration/targets/inventory_azure/playbooks/setup.yml
  tests/integration/targets/inventory_azure/playbooks/teardown.yml
  tests/integration/targets/inventory_azure/playbooks/test_inventory_filter.yml
  tests/integration/targets/inventory_azure/playbooks/vars.yml
  tests/integration/targets/inventory_azure/runme.sh
  tests/integration/targets/inventory_azure/templates/filter.yml
Labels: enhancement, ready_for_review, medium_priority

#1538 Add support site_auth_settings to azure_rm_webapp.py
  plugins/modules/azure_rm_webapp.py
  plugins/modules/azure_rm_webapp_info.py
  tests/integration/targets/azure_rm_webapp/tasks/main.yml
Labels: ready_for_review, medium_priority, new_feature

#1545 Fix for inventory host processing
  plugins/inventory/azure_rm.py
Labels: ready_for_review, medium_priority

#1536 Support to manage storageaccount management policy
  plugins/modules/azure_rm_storageaccountmanagementpolicy.py
  plugins/modules/azure_rm_storageaccountmanagementpolicy_info.py
  pr-pipelines.yml
  tests/integration/targets/azure_rm_storageaccountmanagementpolicy/aliases
  tests/integration/targets/azure_rm_storageaccountmanagementpolicy/meta/main.yml
  tests/integration/targets/azure_rm_storageaccountmanagementpolicy/tasks/main.yml
Labels: ready_for_review, new_module_pr, medium_priority

#1525 Add support to managed virtual netowrk gateway nat rule
  plugins/modules/azure_rm_virtualnetworkgatewaynatrule.py
  plugins/modules/azure_rm_virtualnetworkgatewaynatrule_info.py
  pr-pipelines.yml
  tests/integration/targets/azure_rm_virtualnetworkgatewaynatrule/aliases
  tests/integration/targets/azure_rm_virtualnetworkgatewaynatrule/meta/main.yml
  tests/integration/targets/azure_rm_virtualnetworkgatewaynatrule/tasks/main.yml
Labels: ready_for_review, new_module_pr, medium_priority

#1541 Update azure_rm_accesstoken parameter is_ad_resource=True
  plugins/modules/azure_rm_accesstoken_info.py
Labels: ready_for_review, medium_priority

#1543 Add UserAssigned Identity to aks module
  plugins/modules/azure_rm_aks.py
  tests/integration/targets/azure_rm_aks/tasks/main.yml
  tests/integration/targets/azure_rm_aks/tasks/minimal-cluster.yml
Labels: ready_for_review, medium_priority, new_feature

#1523 Add support to managed local network gateway
  plugins/modules/azure_rm_localnetworkgateway.py
  plugins/modules/azure_rm_localnetworkgateway_info.py
  pr-pipelines.yml
  tests/integration/targets/azure_rm_localnetworkgateway/aliases
  tests/integration/targets/azure_rm_localnetworkgateway/meta/main.yml
  tests/integration/targets/azure_rm_localnetworkgateway/tasks/main.yml
Labels: ready_for_review, new_module_pr, medium_priority

#1551 Symlink requirements-azure.txt from tests/integration
  tests/integration/requirements.txt
Labels: ready_for_review, medium_priority

#1537 Add managedNATGateway/userAssignedNATGateway to outbound_type property of the azure_rm_aks module
  plugins/modules/azure_rm_aks.py
Labels: ready_for_review, medium_priority

#1548 Add new modules to managed SQL managed database retention policy
  plugins/modules/azure_rm_sqlmidatabase.py
  plugins/modules/azure_rm_sqlmidatabase_info.py
  plugins/modules/azure_rm_sqlmidblongtermretentionpolicy.py
  plugins/modules/azure_rm_sqlmidblongtermretentionpolicy_info.py
  plugins/modules/azure_rm_sqlmidbshorttermretentionpolicy.py
  plugins/modules/azure_rm_sqlmidbshorttermretentionpolicy_info.py
  pr-pipelines.yml
  tests/integration/targets/azure_rm_sqlmanageddatabase/aliases
  tests/integration/targets/azure_rm_sqlmanageddatabase/meta/main.yml
  tests/integration/targets/azure_rm_sqlmanageddatabase/tasks/main.yml
Labels: ready_for_review, new_module_pr

#1558 Support more parameters to azure_rm_webappaccessrestriction.py's ip_security_restrictions
  plugins/modules/azure_rm_webappaccessrestriction.py
  plugins/modules/azure_rm_webappaccessrestriction_info.py
  tests/integration/targets/azure_rm_webappaccessrestriction/tasks/main.yml
Labels: ready_for_review, medium_priority, new_feature

#1530 Support to update functionality in the module azure_rm_adgroup.py
  plugins/modules/azure_rm_adgroup.py
Labels: ready_for_review, medium_priority

#1567 Delete the imported logging module
  plugins/modules/azure_rm_postgresqlflexiblefirewallrule.py
  plugins/modules/azure_rm_webapp.py
Labels: ready_for_review, high_priority

#1508 remove functionality which should have been removed for Ansible 2.9
  plugins/modules/azure_rm_loadbalancer.py
  plugins/modules/azure_rm_networkinterface.py
  tests/integration/targets/azure_rm_image/tasks/main.yml
  tests/integration/targets/azure_rm_loadbalancer/tasks/main.yml
  tests/integration/targets/azure_rm_networkinterface/tasks/main.yml
  tests/integration/targets/azure_rm_virtualmachine/tasks/azure_test_public_ip.yml
  tests/integration/targets/azure_rm_virtualmachineextension/tasks/main.yml
  tests/integration/targets/azure_rm_virtualmachinescaleset/tasks/main.yml
Labels: question, ready_for_review, medium_priority

#1546 Add vmskus module - list available skus
  plugins/modules/azure_rm_vmsku_info.py
  requirements.txt
  tests/integration/targets/azure_rm_virtualmachine/inventory.yml
  tests/integration/targets/azure_rm_virtualmachine/tasks/azure_test_skus.yml
Labels: ready_for_review, new_module_pr, medium_priority

#1430 Add support to attach existing managed data disks at VM creation
  plugins/modules/azure_rm_virtualmachine.py
Labels: enhancement, ready_for_review, medium_priority

#1507 allow service principals and nested groups to be returned in membership attributes
  plugins/modules/azure_rm_adgroup.py
  plugins/modules/azure_rm_adgroup_info.py
Labels: question, ready_for_review, medium_priority

#1480 Fix optional_claims handling for azure_rm_adapplication
  plugins/modules/azure_rm_adapplication.py
  plugins/modules/azure_rm_adapplication_info.py
  tests/integration/targets/azure_rm_adapplication/tasks/main.yml
Labels: enhancement, ready_for_review, medium_priority, new_feature

#1563 Fix LocalNetworkGateway Documentation mistakes
  plugins/modules/azure_rm_localnetworkgateway.py
  plugins/modules/azure_rm_localnetworkgateway_info.py
Labels: documentation-pr, ready_for_review, medium_priority

#1565 Create _own_nsg_ tag only if created_nsg is true
  plugins/modules/azure_rm_virtualmachine.py
Labels: ready_for_review, medium_priority

#1564 Fix: Authentication Issue: azure.azcollection.azure_rm_storageblob Fails with Disabled Shared Keys
  plugins/module_utils/azure_rm_common.py
Labels: question, ready_for_review, medium_priority

#1529 Fixed an issue where obtaining flexible VMSS instances failed
  plugins/modules/azure_rm_virtualmachinescalesetinstance.py
  plugins/modules/azure_rm_virtualmachinescalesetinstance_info.py
Labels: ready_for_review, medium_priority

#1477 Add more parameters to azure_rm_aksagentpool.py
  plugins/modules/azure_rm_aksagentpool.py
  plugins/modules/azure_rm_aksagentpool_info.py
  tests/integration/targets/azure_rm_aksagentpool/tasks/main.yml
Labels: ready_for_review, medium_priority

#1574 Update storageaccount blob test case
  tests/integration/targets/azure_rm_storageblob/tasks/main.yml
Labels: ready_for_review

#1570 Disable pipeline test case
  tests/integration/targets/azure_rm_cosmosdbaccount/tasks/main.yml
  tests/integration/targets/azure_rm_expressroute/tasks/main.yml
  tests/integration/targets/azure_rm_mariadbserver/aliases
  tests/integration/targets/azure_rm_mysqlserver/aliases
  tests/integration/targets/azure_rm_privatelinkservice/tasks/main.yml
Labels: ready_for_review, medium_priority

#1571 Bump version to v2.4.0
  CHANGELOG.md
  galaxy.yml
Labels: ready_for_review
