Repository ansible-collections/azure, pull requests merged in 2024-09, with the labels that each got.

#1696 `azure_rm_eventhub` - Add managed identity support to eventhub module
  plugins/modules/azure_rm_eventhub.py
  plugins/modules/azure_rm_eventhub_info.py
  tests/integration/targets/azure_rm_eventhub/tasks/main.yml
  tests/integration/targets/azure_rm_eventhub/tasks/managedidentity.yml
Labels: ready_for_review, medium_priority

#1699 Use the password plug-in to generate a login key
  plugins/modules/azure_rm_appgateway.py
  plugins/modules/azure_rm_devtestlabvirtualmachine.py
  plugins/modules/azure_rm_hdinsightcluster.py
  plugins/modules/azure_rm_mariadbserver.py
  plugins/modules/azure_rm_mysqlserver.py
  plugins/modules/azure_rm_postgresqlflexibleserver.py
  plugins/modules/azure_rm_postgresqlserver.py
  plugins/modules/azure_rm_sqlmanagedinstance.py
  plugins/modules/azure_rm_sqlserver.py
  plugins/modules/azure_rm_webapp.py
  tests/integration/targets/azure_rm_adapplication/tasks/main.yml
  tests/integration/targets/azure_rm_appgateway/tasks/main.yml
  tests/integration/targets/azure_rm_deployment/tasks/main.yml
  tests/integration/targets/azure_rm_devtestlab/tasks/main.yml
  tests/integration/targets/azure_rm_hdinsightcluster/tasks/main.yml
  tests/integration/targets/azure_rm_mariadbserver/tasks/main.yml
  tests/integration/targets/azure_rm_multiplemanageddisks/tasks/main.yml
  tests/integration/targets/azure_rm_multiplemanageddisks/tasks/test_async.yml
  tests/integration/targets/azure_rm_multiplemanageddisks/tasks/test_shared.yml
  tests/integration/targets/azure_rm_mysqlserver/tasks/main.yml
  tests/integration/targets/azure_rm_postgresqlflexibleserver/tasks/main.yml
  tests/integration/targets/azure_rm_postgresqlserver/tasks/main.yml
  tests/integration/targets/azure_rm_privateendpoint/tasks/main.yml
  tests/integration/targets/azure_rm_privateendpointdnszonegroup/tasks/main.yml
  tests/integration/targets/azure_rm_sqlmanageddatabase/tasks/main.yml
  tests/integration/targets/azure_rm_sqlmanagedinstance/tasks/main.yml
  tests/integration/targets/azure_rm_sqlserver/tasks/main.yml
  tests/integration/targets/azure_rm_virtualmachine/tasks/azure_test_minimal.yml
  tests/integration/targets/azure_rm_virtualmachine/tasks/azure_test_public_ip.yml
Labels: ready_for_review, medium_priority

#1704 Set the value of open port
  tests/integration/targets/azure_rm_gallery/tasks/main.yml
  tests/integration/targets/azure_rm_image/tasks/main.yml
  tests/integration/targets/azure_rm_multiplemanageddisks/tasks/test_async.yml
  tests/integration/targets/azure_rm_multiplemanageddisks/tasks/test_shared.yml
  tests/integration/targets/azure_rm_networkinterface/tasks/main.yml
  tests/integration/targets/azure_rm_virtualmachine/tasks/azure_test_deallocate.yml
  tests/integration/targets/azure_rm_virtualmachine/tasks/azure_test_dual_nic.yml
  tests/integration/targets/azure_rm_virtualmachine/tasks/azure_test_encrypted.yml
  tests/integration/targets/azure_rm_virtualmachine/tasks/azure_test_ephemeral_os.yml
  tests/integration/targets/azure_rm_virtualmachine/tasks/azure_test_image_latest.yml
  tests/integration/targets/azure_rm_virtualmachine/tasks/azure_test_image_specific.yml
  tests/integration/targets/azure_rm_virtualmachine/tasks/azure_test_minimal.yml
  tests/integration/targets/azure_rm_virtualmachine/tasks/azure_test_minimal_manageddisk.yml
  tests/integration/targets/azure_rm_virtualmachine/tasks/azure_test_no_nsg.yml
  tests/integration/targets/azure_rm_virtualmachine/tasks/azure_test_no_public_ip.yml
  tests/integration/targets/azure_rm_virtualmachine/tasks/azure_test_public_ip.yml
  tests/integration/targets/azure_rm_virtualmachine/tasks/azure_test_skus.yml
  tests/integration/targets/azure_rm_virtualmachine/tasks/azure_test_spot.yml
  tests/integration/targets/azure_rm_virtualmachine/tasks/azure_test_vm_identity.yml
  tests/integration/targets/azure_rm_virtualmachineextension/tasks/main.yml
  tests/integration/targets/azure_rm_virtualmachinescaleset/tasks/main.yml
  tests/integration/targets/inventory_azure/playbooks/setup.yml
Labels: ready_for_review, high_priority

#1709 Upgrade dependency package to lasted
  plugins/module_utils/azure_rm_common.py
  plugins/modules/azure_rm_containerregistryreplication.py
  plugins/modules/azure_rm_containerregistrywebhook.py
  requirements.txt
Labels: ready_for_review, medium_priority, dependencies

#1714 Update `azure_rm_sqlelasticpool` test case
  tests/integration/targets/azure_rm_sqlserver/tasks/main.yml
Labels: ready_for_review, high_priority

#1711 `azure_rm_networkinterface` Fixes errors for application security groups under different subscription ids
  plugins/modules/azure_rm_networkinterface.py
Labels: ready_for_review, high_priority

#1700 Upgrade azure-mgmt-compute to v33.0.0
  plugins/module_utils/azure_rm_common.py
  plugins/modules/azure_rm_image.py
  plugins/modules/azure_rm_manageddisk.py
  plugins/modules/azure_rm_manageddisk_info.py
  plugins/modules/azure_rm_multiplemanageddisks.py
  plugins/modules/azure_rm_virtualmachine.py
  plugins/modules/azure_rm_virtualmachinescalesetinstance.py
  plugins/modules/azure_rm_virtualmachinescalesetinstance_info.py
  requirements.txt
Labels: ready_for_review, medium_priority, dependencies

#1697 Upgrade azure-mgmt-network-to-v26.0.0
  plugins/module_utils/azure_rm_common.py
  plugins/modules/azure_rm_appgateway.py
  requirements.txt
  tests/integration/targets/azure_rm_appgateway/tasks/main.yml
  tests/integration/targets/azure_rm_networkinterface/tasks/main.yml
Labels: ready_for_review, medium_priority, dependencies

#1683 Add Identity Management to log_analytics
  plugins/modules/azure_rm_loganalyticsworkspace.py
  requirements.txt
  tests/integration/targets/azure_rm_loganalyticsworkspace/tasks/main.yml
Labels: enhancement, ready_for_review

#1706 Upgrade azure-mgmt-notificationhubs and azure-mgmt-eventhub to lastest
  plugins/module_utils/azure_rm_common.py
  requirements.txt
Labels: ready_for_review, medium_priority, dependencies

#1703 Update some dependency packages
  requirements.txt
Labels: ready_for_review, medium_priority, dependencies

#1707 Update some dependency packages -- 02
  plugins/module_utils/azure_rm_common.py
  plugins/modules/azure_rm_rediscache.py
  plugins/modules/azure_rm_rediscache_info.py
  plugins/modules/azure_rm_rediscachefirewallrule.py
  plugins/modules/azure_rm_servicebus.py
  plugins/modules/azure_rm_servicebus_info.py
  requirements.txt
  tests/integration/targets/azure_rm_cognitivesearch/tasks/main.yml
Labels: ready_for_review, dependencies

#1718 Add tags to parameter agent_pools
  plugins/modules/azure_rm_aks.py
Labels: ready_for_review, medium_priority, new_feature

#1712 Update all packages to the latest version
  plugins/module_utils/azure_rm_common.py
  plugins/modules/azure_rm_keyvault.py
  plugins/modules/azure_rm_keyvault_info.py
  plugins/modules/azure_rm_registrationassignment.py
  plugins/modules/azure_rm_registrationassignment_info.py
  plugins/modules/azure_rm_registrationdefinition.py
  plugins/modules/azure_rm_registrationdefinition_info.py
  plugins/modules/azure_rm_roledefinition.py
  plugins/modules/azure_rm_roledefinition_info.py
  requirements.txt
Labels: ready_for_review, medium_priority, dependencies

#1694 fix: keeping action_groups and modules list on version 2.7.0
  meta/runtime.yml
Labels: ready_for_review

#1693 fix version_added for 2.7.0
  plugins/modules/azure_rm_afdendpoint.py
  plugins/modules/azure_rm_afdendpoint_info.py
  plugins/modules/azure_rm_appgateway.py
  plugins/modules/azure_rm_batchaccount.py
  plugins/modules/azure_rm_iothub.py
  plugins/modules/azure_rm_openshiftmanagedclusterversion_info.py
Labels: ready_for_review

#1691 `azure_rm_openshiftcluster` Remove vm_size choices
  plugins/modules/azure_rm_openshiftmanagedcluster.py
Labels: ready_for_review

#1660 `azure_rm_publicipaddress` Add the `reverse_fqdn`
  plugins/modules/azure_rm_publicipaddress.py
  plugins/modules/azure_rm_publicipaddress_info.py
  tests/integration/targets/azure_rm_publicipaddress/tasks/main.yml
Labels: ready_for_review, medium_priority

#1659 `azure_rm_snapshot_info` - Add support for list snapshot instance
  meta/runtime.yml
  plugins/modules/azure_rm_snapshot_info.py
  pr-pipelines.yml
  tests/integration/targets/azure_rm_gallery/tasks/main.yml
Labels: ready_for_review, new_module_pr

#1633 `azure_rm_sqlmanagedinstance` - Add support for Managed User Identities to sqlManagedInstance
  plugins/modules/azure_rm_sqlmanagedinstance.py
  tests/integration/targets/azure_rm_sqlmanagedinstance/tasks/main.yml
  tests/integration/targets/azure_rm_sqlmanagedinstance/tasks/managedidentity.yml
Labels: ready_for_review, medium_priority, new_feature

#1674 `azure_rm_virtualmachine_info` - Return identity
  plugins/modules/azure_rm_virtualmachine_info.py
Labels: enhancement, ready_for_review, medium_priority

#1627 `azure_rm_virtualnetworkgatewayconnection` , `azure_rm_virtualnetworkgatewayconnection_info` - Support to managed virtual network gateway connection's resource
  meta/runtime.yml
  plugins/modules/azure_rm_virtualnetworkgatewayconnection.py
  plugins/modules/azure_rm_virtualnetworkgatewayconnection_info.py
  pr-pipelines.yml
  tests/integration/targets/azure_rm_virtualnetworkgatewayconnection/aliases
  tests/integration/targets/azure_rm_virtualnetworkgatewayconnection/meta/main.yml
  tests/integration/targets/azure_rm_virtualnetworkgatewayconnection/tasks/main.yml
Labels: ready_for_review, new_module_pr, medium_priority

#1723 Upgrade azure-mgmt-notificationhub api version to v2023-09-01
  plugins/module_utils/azure_rm_common.py
Labels: ready_for_review, dependencies

#1586 Support managed flexible server
  meta/runtime.yml
  plugins/module_utils/azure_rm_common.py
  plugins/modules/azure_rm_mysqlflexibleconfiguration.py
  plugins/modules/azure_rm_mysqlflexibleconfiguration_info.py
  plugins/modules/azure_rm_mysqlflexibledatabase.py
  plugins/modules/azure_rm_mysqlflexibledatabase_info.py
  plugins/modules/azure_rm_mysqlflexiblefirewallrule.py
  plugins/modules/azure_rm_mysqlflexiblefirewallrule_info.py
  plugins/modules/azure_rm_mysqlflexibleserver.py
  plugins/modules/azure_rm_mysqlflexibleserver_info.py
  pr-pipelines.yml
  tests/integration/targets/azure_rm_mysqlflexibleserver/aliases
  tests/integration/targets/azure_rm_mysqlflexibleserver/meta/main.yml
  tests/integration/targets/azure_rm_mysqlflexibleserver/tasks/main.yml
Labels: ready_for_review, new_module_pr

#1724 Managed identity cleanup
  plugins/doc_fragments/azure_identity_multiple_user.py
  plugins/doc_fragments/azure_identity_single.py
  plugins/module_utils/azure_rm_common_ext.py
  plugins/modules/azure_rm_appgateway.py
  plugins/modules/azure_rm_batchaccount.py
  plugins/modules/azure_rm_containerinstance.py
  plugins/modules/azure_rm_containerregistry.py
  plugins/modules/azure_rm_cosmosdbaccount.py
  plugins/modules/azure_rm_functionapp.py
  plugins/modules/azure_rm_iothub.py
  plugins/modules/azure_rm_postgresqlflexibleserver.py
  plugins/modules/azure_rm_recoveryservicesvault.py
  plugins/modules/azure_rm_rediscache.py
  plugins/modules/azure_rm_servicebus.py
  plugins/modules/azure_rm_sqlmanagedinstance.py
  plugins/modules/azure_rm_sqlserver.py
  plugins/modules/azure_rm_storageaccount.py
  plugins/modules/azure_rm_virtualmachinescaleset.py
  plugins/modules/azure_rm_webapp.py
  tests/integration/targets/azure_rm_appgateway/aliases
  tests/integration/targets/azure_rm_appgateway/tasks/main.yml
  tests/integration/targets/azure_rm_batchaccount/aliases
  tests/integration/targets/azure_rm_batchaccount/tasks/main.yml
  tests/integration/targets/azure_rm_cdnprofile/aliases
  tests/integration/targets/azure_rm_cdnprofile/tasks/main.yml
  tests/integration/targets/azure_rm_containerinstance/aliases
  tests/integration/targets/azure_rm_containerinstance/tasks/main.yml
  tests/integration/targets/azure_rm_containerregistry/aliases
  tests/integration/targets/azure_rm_containerregistry/tasks/main.yml
  tests/integration/targets/azure_rm_cosmosdbaccount/aliases
  tests/integration/targets/azure_rm_cosmosdbaccount/tasks/main.yml
  tests/integration/targets/azure_rm_diskencryptionset/aliases
  tests/integration/targets/azure_rm_diskencryptionset/tasks/main.yml
  tests/integration/targets/azure_rm_eventhub/aliases
  tests/integration/targets/azure_rm_eventhub/tasks/main.yml
  tests/integration/targets/azure_rm_eventhub/tasks/managedidentity.yml
  tests/integration/targets/azure_rm_functionapp/aliases
  tests/integration/targets/azure_rm_functionapp/tasks/main.yml
  tests/integration/targets/azure_rm_iothub/aliases
  tests/integration/targets/azure_rm_iothub/tasks/main.yml
  tests/integration/targets/azure_rm_postgresqlflexibleserver/aliases
  tests/integration/targets/azure_rm_postgresqlflexibleserver/tasks/main.yml
  tests/integration/targets/azure_rm_recoveryservicesvault/aliases
  tests/integration/targets/azure_rm_recoveryservicesvault/tasks/main.yml
  tests/integration/targets/azure_rm_rediscache/aliases
  tests/integration/targets/azure_rm_rediscache/tasks/main.yml
  tests/integration/targets/azure_rm_servicebus/aliases
  tests/integration/targets/azure_rm_servicebus/tasks/main.yml
  tests/integration/targets/azure_rm_sqlmanagedinstance/aliases
  tests/integration/targets/azure_rm_sqlmanagedinstance/tasks/main.yml
  tests/integration/targets/azure_rm_sqlserver/aliases
  tests/integration/targets/azure_rm_sqlserver/tasks/main.yml
  tests/integration/targets/azure_rm_storageaccount/aliases
  tests/integration/targets/azure_rm_storageaccount/tasks/main.yml
  tests/integration/targets/azure_rm_virtualmachinescaleset/aliases
  tests/integration/targets/azure_rm_virtualmachinescaleset/tasks/main.yml
  tests/integration/targets/azure_rm_webapp/aliases
  tests/integration/targets/azure_rm_webapp/tasks/main.yml
  tests/integration_common_tasks/managed_identity.yml
Labels: ready_for_review, high_priority

#1719 ACA-1842: VM Image SKUs support in Ansible collection for Azure module creation
  plugins/modules/azure_rm_imagesku_info.py
  tests/integration/targets/azure_rm_virtualmachine/inventory.yml
  tests/integration/targets/azure_rm_virtualmachine/tasks/azure_test_image_skus.yml
Labels: ready_for_review, new_module_pr, medium_priority

#1730 Fixed bugs caused by indent
  plugins/modules/azure_rm_aks.py
Labels: ready_for_review, medium_priority

#1732 Update azure_rm_virtualmachinescalesetinstance.py's document
  plugins/modules/azure_rm_virtualmachinescalesetinstance.py
Labels: documentation-pr, ready_for_review, medium_priority
