Repository ansible-collections/azure, pull requests merged in 2024-04, with the labels that each got.

#1520 Fix azure_rm_cognitivesearch.py test failed
  plugins/modules/azure_rm_cognitivesearch.py
  tests/integration/targets/azure_rm_cognitivesearch/tasks/main.yml
  tests/integration/targets/azure_rm_eventhub/tasks/main.yml
Labels: ready_for_review

#1518 Support on_premises_extension_attributes to azure_rm_aduser
  plugins/modules/azure_rm_aduser.py
  plugins/modules/azure_rm_aduser_info.py
  tests/integration/targets/azure_rm_aduser/tasks/main.yml
Labels: ready_for_review, medium_priority

#1517 Add parameter 'cloud_type' to azure_keyvault_secret.py
  plugins/lookup/azure_keyvault_secret.py
Labels: enhancement, ready_for_review, medium_priority

#1528 Add user assigned identity ability to postgresqlFlexServer
  plugins/module_utils/azure_rm_common.py
  plugins/modules/azure_rm_postgresqlflexibleserver.py
  plugins/modules/azure_rm_postgresqlflexibleserver_info.py
  requirements-azure.txt
  tests/integration/targets/azure_rm_postgresqlflexibleserver/tasks/main.yml
Labels: ready_for_review, medium_priority, new_feature
