Repository ansible-collections/azure, pull requests merged in 2024-11, with the labels that each got.

#1754 Deprecate azure_rm_adapplication's 'available_to_other_tenants'
  plugins/modules/azure_rm_adapplication.py
  plugins/modules/azure_rm_adapplication_info.py
Labels: ready_for_review

#1756 Fixes bugs caused by version changes
  plugins/modules/azure_rm_manageddisk.py
Labels: ready_for_review, high_priority

#1752 Fix Flexible vmss issue + added VMSS RG env var
  plugins/inventory/azure_rm.py
Labels: ready_for_review, medium_priority

#1737 `azure_rm_keyvault` Add support for `enable_rbac_authorization`
  plugins/modules/azure_rm_keyvault.py
  plugins/modules/azure_rm_keyvault_info.py
Labels: ready_for_review, medium_priority, new_feature

#1736 Add support for `is_authentication_with_ssh_key`
  plugins/modules/azure_rm_devtestlabvirtualmachine.py
  plugins/modules/azure_rm_devtestlabvirtualmachine_info.py
Labels: enhancement, ready_for_review, medium_priority, new_feature

#1738 Add support netowrk_acls to azure_rm_keyvault.py
  plugins/modules/azure_rm_keyvault.py
  plugins/modules/azure_rm_keyvault_info.py
  tests/integration/targets/azure_rm_keyvault/tasks/main.yml
Labels: enhancement, ready_for_review, medium_priority, new_feature

#1740 Add support windows_profile to azure_rm_aks.py
  plugins/modules/azure_rm_aks.py
  plugins/modules/azure_rm_aksagentpool.py
  plugins/modules/azure_rm_aksagentpool_info.py
Labels: ready_for_review, medium_priority, new_feature

#1743 Add support metric_namespace to azure_rm_autoscale.py
  plugins/modules/azure_rm_autoscale.py
  plugins/modules/azure_rm_autoscale_info.py
  tests/integration/targets/azure_rm_autoscale/tasks/main.yml
Labels: ready_for_review, medium_priority, new_feature

#1745 Add support manual_private_link_service_connections to azure_rm_privateendpoint.py
  plugins/modules/azure_rm_privateendpoint.py
  plugins/modules/azure_rm_privateendpoint_info.py
  tests/integration/targets/azure_rm_privateendpoint/tasks/main.yml
Labels: ready_for_review, medium_priority, new_feature

#1761 Disable the role assignment use case due to permission restrictions
  tests/integration/targets/azure_rm_roleassignment/tasks/main.yml
  tests/integration/targets/azure_rm_storageblob/tasks/main.yml
Labels: ready_for_review, medium_priority

#1763 Add aliase for azure_rm_iothub.py's container parameters
  plugins/modules/azure_rm_iothub.py
Labels: enhancement, ready_for_review, medium_priority

#1753 Add support to managed batch account relate resource
  meta/runtime.yml
  plugins/module_utils/azure_rm_common.py
  plugins/modules/azure_rm_batchaccount.py
  plugins/modules/azure_rm_batchaccount_info.py
  plugins/modules/azure_rm_batchaccountapplication.py
  plugins/modules/azure_rm_batchaccountapplication_info.py
  plugins/modules/azure_rm_batchaccountapplicationpackage.py
  plugins/modules/azure_rm_batchaccountapplicationpackage_info.py
  plugins/modules/azure_rm_batchaccountpool.py
  plugins/modules/azure_rm_batchaccountpool_info.py
  pr-pipelines.yml
  tests/integration/targets/azure_rm_batchaccount/tasks/main.yml
Labels: ready_for_review, new_module_pr, medium_priority

#1764 `azure_rm_storageblob` - Add support `standard_blob_tier`
  meta/runtime.yml
  plugins/modules/azure_rm_storageblob.py
  plugins/modules/azure_rm_storageblob_info.py
  tests/integration/targets/azure_rm_storageblob/tasks/main.yml
Labels: ready_for_review, new_module_pr, medium_priority, new_feature

#1759 Support for creating VMS through community images
  plugins/modules/azure_rm_virtualmachine.py
  plugins/modules/azure_rm_virtualmachine_info.py
  plugins/modules/azure_rm_virtualmachinescaleset.py
  plugins/modules/azure_rm_virtualmachinescaleset_info.py
Labels: ready_for_review, medium_priority, new_feature

#1769 Upgrade azure-mgmt-network to v28.0.0
  requirements.txt
Labels: ready_for_review, high_priority
