Repository ansible-collections/azure, pull requests merged in 2024-06, with the labels that each got.

#1566 Managed Identity support for webapp module
  plugins/module_utils/azure_rm_common_ext.py
  plugins/modules/azure_rm_postgresqlflexibleserver.py
  plugins/modules/azure_rm_webapp.py
  plugins/modules/azure_rm_webapp_info.py
  tests/integration/targets/azure_rm_webapp/tasks/main.yml
Labels: question, ready_for_review, medium_priority

#1557 New Resource `azure_rm_capacityreservationgroup` , `azure_rm_capacityreservationgroup_info`- Support to manage capacity reservation group
  meta/runtime.yml
  plugins/modules/azure_rm_capacityreservationgroup.py
  plugins/modules/azure_rm_capacityreservationgroup_info.py
  plugins/modules/azure_rm_virtualmachine.py
  plugins/modules/azure_rm_virtualmachine_info.py
  pr-pipelines.yml
  tests/integration/targets/azure_rm_capacityreservationgroup/aliases
  tests/integration/targets/azure_rm_capacityreservationgroup/meta/main.yml
  tests/integration/targets/azure_rm_capacityreservationgroup/tasks/main.yml
Labels: ready_for_review, new_module_pr, medium_priority

#1466 Allow creating gallery image versions from storage accounts
  plugins/modules/azure_rm_galleryimageversion.py
  tests/integration/targets/azure_rm_gallery/tasks/main.yml
Labels: question, ready_for_review, medium_priority

#1581 Container instance identity
  plugins/modules/azure_rm_containerinstance.py
  plugins/modules/azure_rm_containerinstance_info.py
  tests/integration/targets/azure_rm_containerinstance/tasks/main.yml
Labels: enhancement, ready_for_review, medium_priority

#1583 Add support `allow_shared_key_access` to azure_rm_storageaccount.py
  plugins/modules/azure_rm_storageaccount.py
  plugins/modules/azure_rm_storageaccount_info.py
  tests/integration/targets/azure_rm_storageaccount/tasks/main.yml
Labels: enhancement, ready_for_review, medium_priority

#1585 Add identity support to vmss module
  plugins/modules/azure_rm_virtualmachinescaleset.py
  plugins/modules/azure_rm_virtualmachinescaleset_info.py
  tests/integration/targets/azure_rm_virtualmachinescaleset/tasks/main.yml
Labels: ready_for_review, medium_priority, new_feature

#1576 New Resource - `azure_rm_networkwatcher`, `azure_rm_networkwatcher_info`, `azure_rm_networkflowlogs`, `azure_rm_networkflowlogs_info`Support manage network watcher
  meta/runtime.yml
  plugins/modules/azure_rm_networkflowlog.py
  plugins/modules/azure_rm_networkflowlog_info.py
  plugins/modules/azure_rm_networkwatcher.py
  plugins/modules/azure_rm_networkwatcher_info.py
  pr-pipelines.yml
  tests/integration/targets/azure_rm_networkwatcher/aliases
  tests/integration/targets/azure_rm_networkwatcher/meta/main.yml
  tests/integration/targets/azure_rm_networkwatcher/tasks/main.yml
Labels: ready_for_review, medium_priority

#1593 Update azure-cli-core to 2.61.0
  requirements.txt
Labels: question, ready_for_review, medium_priority

#1609 Limit azure-iot-hub to x86_64 platforms
  requirements.txt
Labels: ready_for_review, medium_priority

#1610 Bump version to v2.5.0
  CHANGELOG.md
  galaxy.yml
Labels: ready_for_review

#1613 Documentation: misleading `*_host_filter` example
  plugins/inventory/azure_rm.py
Labels: documentation-pr, ready_for_review
