Repository ansible-collections/azure, pull requests merged in 2024-02, with the labels that each got.

#1425 Fix test for azure_rm_adapplication module
  tests/integration/targets/azure_rm_adapplication/tasks/main.yml
Labels: ready_for_review, medium_priority

#1426 Update the adgroup test cases
  tests/integration/targets/azure_rm_adgroup/tasks/main.yml
Labels: ready_for_review, medium_priority

#1373 Adding tags to the azure_rm_appgateway module.
  plugins/modules/azure_rm_appgateway.py
Labels: question, ready_for_review, medium_priority

#1462 Return the subnet ID in azure_rm_networkinterface_info.py
  plugins/modules/azure_rm_networkinterface_info.py
Labels: enhancement, ready_for_review, medium_priority

#1470 Add port and match to azure_rm_appgateway.py's probes
  plugins/modules/azure_rm_appgateway.py
Labels: ready_for_review, medium_priority, new_featrue

#1467 Fix unsuppoeted header in `azure_rm_adgroup`
  plugins/modules/azure_rm_adgroup.py
Labels: ready_for_review, medium_priority

#1469 Support for azure-mgmt-recoveryservicesbackup v4.0+
  plugins/module_utils/azure_rm_common.py
Labels: enhancement, ready_for_review, medium_priority

#1468 Documentation typo fixes + typo fix in code
  plugins/modules/azure_rm_aks.py
  plugins/modules/azure_rm_keyvaultkey_info.py
  plugins/modules/azure_rm_sqlmanagedinstance.py
  plugins/modules/azure_rm_sqlmanagedinstance_info.py
  plugins/modules/azure_rm_virtualmachine.py
  tests/integration/targets/azure_rm_apimanagement/tasks/main.yml
Labels: documentation-pr, ready_for_review, medium_priority

#1449 Removing leftover storage account from test
  tests/integration/targets/azure_rm_storageaccount/tasks/main.yml
Labels: ready_for_review, medium_priority

#1456 Add allow_preview parameter to azure_rm_aksversion_info
  plugins/modules/azure_rm_aksversion_info.py
Labels: enhancement, ready_for_review, medium_priority, new_featrue

#1448 Parse paginated replies for listing all users/groups
  plugins/modules/azure_rm_adgroup_info.py
  plugins/modules/azure_rm_aduser_info.py
Labels: enhancement, ready_for_review, medium_priority

#1442 Add support for disable_instance_discovery
  plugins/doc_fragments/azure.py
  plugins/module_utils/azure_rm_common.py
Labels: question, ready_for_review, medium_priority

#1446 Allow for template expressions in some parameters
  plugins/inventory/azure_rm.py
Labels: ready_for_review, medium_priority

#1436 Check the azure_rm_galleryimageversion return value
  plugins/modules/azure_rm_galleryimageversion_info.py
Labels: ready_for_review, medium_priority
