Repository ansible-collections/azure, pull requests merged in 2024-03, with the labels that each got.

#1492 Support 'description' to azure_rm_adgroup
  plugins/modules/azure_rm_adgroup.py
  plugins/modules/azure_rm_adgroup_info.py
  tests/integration/targets/azure_rm_adgroup/tasks/main.yml
Labels: enhancement, ready_for_review, medium_priority

#1495 Support to create Web App with Java11/Java17/Java21
  plugins/modules/azure_rm_webapp.py
  tests/integration/targets/azure_rm_webapp/tasks/main.yml
Labels: enhancement, ready_for_review, medium_priority

#1494 Support spa_redirect_urls and public_client_redirect_urls
  plugins/modules/azure_rm_adapplication.py
  plugins/modules/azure_rm_adapplication_info.py
Labels: ready_for_review, medium_priority, new_featrue

#1493 galleryimage: Support gallery image definitions for Arm64
  plugins/modules/azure_rm_galleryimage.py
Labels: ready_for_review, medium_priority, new_featrue

#1489 Support to recover/purge delete secret
  plugins/modules/azure_rm_keyvaultkey.py
  plugins/modules/azure_rm_keyvaultkey_info.py
  plugins/modules/azure_rm_keyvaultsecret.py
  plugins/modules/azure_rm_keyvaultsecret_info.py
Labels: ready_for_review, medium_priority

#1487 Support to list the vaults in same resource group
  plugins/modules/azure_rm_recoveryservicesvault_info.py
Labels: ready_for_review

#1498 add tags option to azure_rm_resource_info module
  plugins/modules/azure_rm_resource_info.py
Labels: question, ready_for_review, medium_priority

#1503 Fixed an error in formatting the return value
  plugins/modules/azure_rm_servicebus_info.py
Labels: ready_for_review, medium_priority

#1439 Ensure enable_http2 works when targeting existing Application Gateways
  plugins/modules/azure_rm_appgateway.py
Labels: ready_for_review, medium_priority

#1501 The Azure Data Lake Store has retired to disable azure_rm_datalakestore testing
  plugins/modules/azure_rm_datalakestore.py
  plugins/modules/azure_rm_datalakestore_info.py
  tests/integration/targets/azure_rm_datalakestore/aliases
Labels: ready_for_review, medium_priority

#1483 Detects the return value and returns None if the return value is empty
  plugins/modules/azure_rm_gallery_info.py
Labels: ready_for_review, medium_priority

#1484 Support to obtain Azure Kubernetes Service Credentials
  plugins/modules/azure_rm_akscredentials_info.py
  tests/integration/targets/azure_rm_aksagentpool/tasks/main.yml
Labels: ready_for_review, medium_priority

#1504 Support company_name to azure_rm_aduser
  plugins/modules/azure_rm_aduser.py
  plugins/modules/azure_rm_aduser_info.py
Labels: enhancement, ready_for_review, medium_priority

#1497 Support to manage pod identities in managed Kubernetes cluster
  plugins/modules/azure_rm_aks.py
Labels: ready_for_review, medium_priority, new_feature

#1482 Fix listing all service principals
  plugins/modules/azure_rm_adserviceprincipal_info.py
Labels: enhancement, ready_for_review, medium_priority

#713 Respect AZURE_CLIENT_ID, ANSIBLE_AZURE_AUTH_SOURCE on inventory plugin
  plugins/doc_fragments/azure.py
  plugins/inventory/azure_rm.py
  plugins/module_utils/azure_rm_common.py
Labels: enhancement, ready_for_review, inventory, medium_priority

#1510 Modify the default value of is_ad_resource in azure_rm_account_info.py to True
  plugins/modules/azure_rm_account_info.py
Labels: ready_for_review

#1435 Support to swap OS disk
  plugins/modules/azure_rm_virtualmachine.py
Labels: ready_for_review, medium_priority, new_feature

#1516 Bump version to v2.3.0
  CHANGELOG.md
  galaxy.yml
Labels: ready_for_review
