Repository ansible-collections/azure, pull requests merged in 2024-10, with the labels that each got.

#1620 Add support to Azure StackHCI vms in the inventory plugin
  plugins/doc_fragments/azure_rm.py
  plugins/inventory/azure_rm.py
Labels: question, ready_for_review, medium_priority

#1733 Upgrade azure-mgmt-recoveryservicesbackup to v9.1.0
  plugins/module_utils/azure_rm_common.py
  requirements.txt
Labels: ready_for_review, medium_priority

#1741 Add new parameters support to azure_rm_manageddisk
  plugins/module_utils/azure_rm_common.py
  plugins/modules/azure_rm_manageddisk.py
  plugins/modules/azure_rm_manageddisk_info.py
  tests/integration/targets/azure_rm_manageddisk/tasks/main.yml
Labels: ready_for_review, medium_priority, new_feature

#1748 Fixed a bug where the pipeline test failed
  plugins/module_utils/azure_rm_common.py
  plugins/modules/azure_rm_multiplemanageddisks.py
  tests/integration/targets/azure_rm_virtualnetworkgatewaynatrule/tasks/main.yml
Labels: ready_for_review, high_priority

#1744 Add support disable local accounts
  plugins/module_utils/azure_rm_common.py
  plugins/modules/azure_rm_aks.py
  plugins/modules/azure_rm_aksagentpool.py
  plugins/modules/azure_rm_aksagentpool_info.py
  requirements.txt
  tests/integration/targets/azure_rm_aks/tasks/main.yml
  tests/integration/targets/azure_rm_aks/tasks/minimal-cluster.yml
  tests/integration/targets/azure_rm_aksagentpool/tasks/main.yml
Labels: ready_for_review, medium_priority, new_feature

#1749 Bump version to v3.0.0
  CHANGELOG.md
  galaxy.yml
Labels: ready_for_review, medium_priority
