Repository ansible-collections/azure, pull requests merged in 2024-07, with the labels that each got.

#1569 Container registry identity
  plugins/modules/azure_rm_containerregistry.py
  plugins/modules/azure_rm_containerregistry_info.py
  tests/integration/targets/azure_rm_containerregistry/tasks/main.yml
Labels: ready_for_review, medium_priority, new_feature

#1588 Update azure_rm_cdnprofile to include the Standard and Premium Frontdoor options
  plugins/modules/azure_rm_cdnprofile.py
  requirements.txt
Labels: question, ready_for_review, high_priority

#1376 `azure_rm_aduser` - Expose more `password_profile` options: `password_force_change` and `password_force_change_mfa`
  plugins/modules/azure_rm_aduser.py
Labels: question, ready_for_review, medium_priority

#1589 Add `azure_rm_afdendpoint` module to support Azure Front Door Standard and Premium
  meta/runtime.yml
  plugins/modules/azure_rm_afdendpoint.py
  plugins/modules/azure_rm_afdendpoint_info.py
  pr-pipelines.yml
  tests/integration/targets/azure_rm_afdendpoint/aliases
  tests/integration/targets/azure_rm_afdendpoint/meta/main.yml
  tests/integration/targets/azure_rm_afdendpoint/tasks/main.yml
Labels: ready_for_review, medium_priority

#1597 Update azure_rm_snapshot's api-version to 2022-03-02
  plugins/modules/azure_rm_snapshot.py
Labels: ready_for_review, medium_priority

#1598 Add identity management to app gateway module
  plugins/modules/azure_rm_appgateway.py
  tests/integration/targets/azure_rm_appgateway/tasks/main.yml
Labels: ready_for_review, medium_priority, work in

#1602 [New module] - Add azure_rm_openshiftmanagedclusterversion_info module
  plugins/modules/azure_rm_openshiftmanagedclusterversion_info.py
  tests/integration/targets/azure_rm_openshiftmanagedcluster/tasks/main.yml
Labels: ready_for_review, new_module_pr, medium_priority

#1605 Fix auth mode login for azure_rm_storageblob
  plugins/module_utils/azure_rm_common.py
Labels: ready_for_review, medium_priority

#1611 Add Managed Identity support to BatchAccount module
  plugins/module_utils/azure_rm_common_ext.py
  plugins/modules/azure_rm_batchaccount.py
  plugins/modules/azure_rm_batchaccount_info.py
  tests/integration/targets/azure_rm_batchaccount/tasks/main.yml
Labels: ready_for_review

#1615 Add Managed Identity to iothub
  plugins/module_utils/azure_rm_common.py
  plugins/modules/azure_rm_iothub.py
  plugins/modules/azure_rm_iothub_info.py
  tests/integration/targets/azure_rm_iothub/tasks/main.yml
Labels: ready_for_review, new_feature

#1560 Feature azure rm adapplication info diff
  plugins/modules/azure_rm_adapplication_info.py
  tests/integration/targets/azure_rm_adapplication/tasks/main.yml
Labels: question, ready_for_review, medium_priority

#1623 `azure_rm_aduser`, `azure_rm_aduser_info` - Add support for `mobile_phone`
  plugins/modules/azure_rm_aduser.py
  plugins/modules/azure_rm_aduser_info.py
  tests/integration/targets/azure_rm_aduser/tasks/main.yml
Labels: ready_for_review, medium_priority, new_feature

#1641 Enable azure_rm_iothub test case
  plugins/modules/azure_rm_iothub.py
  requirements.txt
  tests/integration/targets/azure_rm_iothub/aliases
Labels: ready_for_review, medium_priority

#1619 Fix errors in test cases
  requirements.txt
  tests/integration/targets/azure_rm_aks/tasks/main.yml
  tests/integration/targets/azure_rm_aks/tasks/minimal-cluster.yml
  tests/integration/targets/azure_rm_aksagentpool/tasks/main.yml
  tests/integration/targets/azure_rm_bastionhost/tasks/main.yml
  tests/integration/targets/azure_rm_containerinstance/tasks/main.yml
  tests/integration/targets/azure_rm_containerregistrytag/tasks/main.yml
  tests/integration/targets/azure_rm_cosmosdbaccount/tasks/main.yml
  tests/integration/targets/azure_rm_functionapp/tasks/main.yml
  tests/integration/targets/azure_rm_multiplemanageddisks/tasks/test_async.yml
  tests/integration/targets/azure_rm_multiplemanageddisks/tasks/test_shared.yml
  tests/integration/targets/azure_rm_registrationassignment/aliases
  tests/integration/targets/azure_rm_registrationdefinition/aliases
  tests/integration/targets/azure_rm_storageblob/tasks/main.yml
  tests/integration/targets/azure_rm_virtualmachine/tasks/azure_test_skus.yml
Labels: ready_for_review, new_module_pr, medium_priority

#1625 Wait 10 minutes to get the imageversion state
  plugins/modules/azure_rm_galleryimageversion.py
Labels: ready_for_review, medium_priority

#1638 `azure_rm_manageddisk_info` - Add `time_created` in return to module
  plugins/modules/azure_rm_manageddisk_info.py
Labels: ready_for_review, medium_priority, new_feature

#1632 Fixed errors caused by returning an empty dictionary
  plugins/modules/azure_rm_openshiftmanagedcluster_info.py
Labels: ready_for_review, medium_priority

#1637 Fix: Check for presence of key, not for presence of value.
  plugins/modules/azure_rm_galleryimageversion_info.py
Labels: ready_for_review, medium_priority

#1629 Update azure_rm_openshiftmanagedcluster.py
  plugins/modules/azure_rm_openshiftmanagedcluster.py
Labels: ready_for_review, medium_priority

#1631 Update azure_rm_openshiftmanagedclusterkubeconfig_info.py
  plugins/modules/azure_rm_openshiftmanagedclusterkubeconfig_info.py
Labels: ready_for_review, high_priority

#1639 Identity storageaccount
  plugins/module_utils/azure_rm_common_ext.py
  plugins/modules/azure_rm_storageaccount.py
  plugins/modules/azure_rm_storageaccount_info.py
  tests/integration/targets/azure_rm_iothub/tasks/main.yml
  tests/integration/targets/azure_rm_storageaccount/tasks/main.yml
Labels: ready_for_review, medium_priority

#1642 Add a resource group locate in westus2
  pr-pipelines.yml
  tests/integration/targets/azure_rm_webapp/tasks/main.yml
  tests/utils/ado/ado.sh
Labels: ready_for_review, high_priority
