Repository ansible-collections/azure, pull requests merged in 2024-12, with the labels that each got.

#1767 [Enhance] `azure_rm_dnsrecordset` - Add support for `target_resource`
  plugins/modules/azure_rm_dnsrecordset.py
  plugins/modules/azure_rm_dnsrecordset_info.py
  plugins/modules/azure_rm_publicipaddress.py
  tests/integration/targets/azure_rm_dnsrecordset/tasks/main.yml
Labels: ready_for_review, medium_priority, new_feature

#1774 `azure_rm_loadbalancecer` - Add support `enable_tcp_reset` to `load_balancing_rules`
  plugins/modules/azure_rm_loadbalancer.py
  tests/integration/targets/azure_rm_loadbalancer/tasks/main.yml
Labels: ready_for_review, medium_priority, new_feature

#1771 `azure_rm_privateendpoint` Add support for `application_security_groups`,`custom_dns_configs`,`custom_network_interface_name`,`ip_configurations`
  plugins/modules/azure_rm_privateendpoint.py
  plugins/modules/azure_rm_privateendpoint_info.py
  tests/integration/targets/azure_rm_privateendpoint/tasks/main.yml
Labels: ready_for_review, medium_priority, new_feature

#1770 Change the NIC info returned by the VM is dynamically obtained
  plugins/inventory/azure_rm.py
Labels: ready_for_review, inventory, medium_priority

#1782 `azure_rm_manageddisk` - Add support `public_network_access` and `network_access_policy`
  plugins/modules/azure_rm_manageddisk.py
  plugins/modules/azure_rm_manageddisk_info.py
  tests/integration/targets/azure_rm_manageddisk/tasks/main.yml
Labels: ready_for_review, medium_priority, new_feature

#1785 Lookup: Include key vault URL to error messages
  plugins/lookup/azure_keyvault_secret.py
Labels: enhancement, ready_for_review, medium_priority

#1783 [New Module]`azure_rm_applicationfirewallpolicy` and `azure_rm_applicationfirewallpolicy_info` Add support app firewall policy
  meta/runtime.yml
  plugins/modules/azure_rm_applicationfirewallpolicy.py
  plugins/modules/azure_rm_applicationfirewallpolicy_info.py
  pr-pipelines.yml
  tests/integration/targets/azure_rm_applicationfirewallpolicy/aliases
  tests/integration/targets/azure_rm_applicationfirewallpolicy/meta/main.yml
  tests/integration/targets/azure_rm_applicationfirewallpolicy/tasks/main.yml
Labels: ready_for_review, new_module_pr

#1790 `azure_rm_iotdevice` - Add support for `device_scope`
  plugins/modules/azure_rm_iotdevice.py
Labels: ready_for_review, medium_priority, new_feature

#1787 `azure_rm_manageddisk_info`, `azure_rm_manageddisk` - Add support for display/modification of disk performance `tier`
  plugins/modules/azure_rm_manageddisk.py
  plugins/modules/azure_rm_manageddisk_info.py
Labels: ready_for_review, medium_priority, new_feature

#1789 Update `azure_rm_cdnprofile` test case
  plugins/modules/azure_rm_cdnprofile.py
  tests/integration/targets/azure_rm_cdnprofile/tasks/main.yml
Labels: ready_for_review, medium_priority

#1792 `azure_rm_webapp` - Add support for updating `startup_file`
  plugins/modules/azure_rm_webapp.py
Labels: enhancement, ready_for_review, medium_priority

#1735 Builds on HCI inventory and adds ARC support as well
  plugins/action/azure_rm_arcssh.py
  plugins/doc_fragments/azure_rm.py
  plugins/inventory/azure_rm.py
  plugins/modules/azure_rm_arcssh.py
  plugins/plugin_utils/connectivity_utils.py
  plugins/plugin_utils/constants.py
  plugins/plugin_utils/file_utils.py
  plugins/plugin_utils/ssh_info.py
  requirements.txt
Labels: ready_for_review, inventory, new_feature

#1725 Update `azure_rm_appgateway` to support setting WAF policy
  plugins/modules/azure_rm_appgateway.py
  tests/integration/targets/azure_rm_appgateway/tasks/main.yml
Labels: enhancement, question, ready_for_review, medium_priority, breaking-change
