Repository ansible-collections/azure, pull requests merged in 2024-01, with the labels that each got.

#1401 Change available to other tenants type
  plugins/modules/azure_rm_adapplication.py
  plugins/modules/azure_rm_adapplication_info.py
  tests/integration/targets/azure_rm_adapplication/tasks/main.yml
Labels: ready_for_review, medium_priority, breaking-change

#1409 Fix missing client_id in payload error when using only an Azure username and password
  plugins/module_utils/azure_rm_common.py
Labels: ready_for_review, high_priority

#1411 Add 'lincense_type' field to distinguish licence
  plugins/inventory/azure_rm.py
Labels: ready_for_review, medium_priority

#1406 Set ansible_host to the first public IP address, if no found, the first private IP will be set
  plugins/inventory/azure_rm.py
Labels: ready_for_review, medium_priority

#1395 Add missing Azure API Profiles to azure_rm_common.py
  plugins/module_utils/azure_rm_common.py
Labels: ready_for_review, medium_priority

#1407 Fixed a no-value error when mounted disk to a virtual machine
  plugins/modules/azure_rm_manageddisk.py
Labels: ready_for_review, medium_priority

#1410 Fixed the underscore replacing the hump in the returned value
  plugins/modules/azure_rm_virtualmachine.py
Labels: ready_for_review, medium_priority

#1412 Detect the VM's powerstate value and fix #1365
  plugins/modules/azure_rm_virtualmachine.py
Labels: enhancement, ready_for_review, medium_priority

#1393 Fix missing changes to delete track1 process
  plugins/module_utils/azure_rm_common.py
Labels: ready_for_review, medium_priority

#1392 Limit zones to a maximum of one element
  plugins/modules/azure_rm_virtualmachine.py
Labels: documentation-pr, ready_for_review, medium_priority

#1403 Add azure_rm_publicipprefix relate modules
  plugins/modules/azure_rm_publicipprefix.py
  plugins/modules/azure_rm_publicipprefix_info.py
  pr-pipelines.yml
  tests/integration/targets/azure_rm_publicipprefix/aliases
  tests/integration/targets/azure_rm_publicipprefix/meta/main.yml
  tests/integration/targets/azure_rm_publicipprefix/tasks/main.yml
Labels: ready_for_review, new_module_pr, medium_priority

#1346 Add parameters 'enable_nfs_v3' to azure_rm_storageaccount.py
  plugins/modules/azure_rm_storageaccount.py
  plugins/modules/azure_rm_storageaccount_info.py
Labels: ready_for_review, medium_priority

#1192 Add flexible servers to support managed post gresql flexible server
  plugins/module_utils/azure_rm_common.py
  plugins/modules/azure_rm_postgresqlflexibleconfiguration_info.py
  plugins/modules/azure_rm_postgresqlflexibledatabase.py
  plugins/modules/azure_rm_postgresqlflexibledatabase_info.py
  plugins/modules/azure_rm_postgresqlflexiblefirewallrule.py
  plugins/modules/azure_rm_postgresqlflexiblefirewallrule_info.py
  plugins/modules/azure_rm_postgresqlflexibleserver.py
  plugins/modules/azure_rm_postgresqlflexibleserver_info.py
  pr-pipelines.yml
  tests/integration/targets/azure_rm_postgresqlflexibleserver/aliases
  tests/integration/targets/azure_rm_postgresqlflexibleserver/meta/main.yml
  tests/integration/targets/azure_rm_postgresqlflexibleserver/tasks/main.yml
Labels: ready_for_review, new_module_pr, medium_priority

#1421 fix the client_id value
  plugins/module_utils/azure_rm_common.py
Labels: ready_for_review, medium_priority

#1388 Fix invalid ansiblemodule schema
  plugins/module_utils/azure_rm_common_rest.py
  plugins/modules/azure_rm_apimanagement.py
  plugins/modules/azure_rm_apimanagementservice.py
  plugins/modules/azure_rm_azurefirewall.py
  plugins/modules/azure_rm_batchaccount.py
  plugins/modules/azure_rm_dnsrecordset.py
  plugins/modules/azure_rm_gallery.py
  plugins/modules/azure_rm_galleryimage.py
  plugins/modules/azure_rm_galleryimageversion.py
  plugins/modules/azure_rm_managementgroup.py
  plugins/modules/azure_rm_openshiftmanagedcluster.py
  plugins/modules/azure_rm_privatednsrecordset.py
  plugins/modules/azure_rm_registrationassignment.py
  plugins/modules/azure_rm_registrationassignment_info.py
  plugins/modules/azure_rm_registrationdefinition.py
  plugins/modules/azure_rm_registrationdefinition_info.py
  plugins/modules/azure_rm_snapshot.py
  plugins/modules/azure_rm_virtualwan.py
  plugins/modules/azure_rm_vpnsite.py
  tests/integration/targets/azure_rm_bastionhost/tasks/main.yml
  tests/integration/targets/azure_rm_roleassignment/tasks/main.yml
  tests/sanity/ignore-2.13.txt
  tests/sanity/ignore-2.14.txt
  tests/sanity/ignore-2.15.txt
  tests/sanity/ignore-2.16.txt
  tests/utils/shippable/check_matrix.py
  tests/utils/shippable/timing.py
Labels: ready_for_review, medium_priority

#1422 Add subnet information to the inventory return value
  plugins/inventory/azure_rm.py
Labels: ready_for_review, inventory, medium_priority

#1414 Add Microsoft.ContainerService/managedClusters to subnet delegations
  plugins/modules/azure_rm_subnet.py
Labels: enhancement, ready_for_review, medium_priority

#1416 Fixed an issue where resource ID subscription_id was not used
  plugins/modules/azure_rm_networkinterface.py
Labels: ready_for_review, medium_priority

#1418 Update adgroup test cases to use object_id
  plugins/modules/azure_rm_adgroup.py
  tests/integration/targets/azure_rm_adgroup/tasks/main.yml
Labels: ready_for_review, medium_priority

#1420 Update azure_rm_adapplication to return all AD Applications. Enhancement to search for application by app_display_name
  plugins/modules/azure_rm_adapplication_info.py
  tests/integration/targets/azure_rm_adapplication/tasks/main.yml
Labels: ready_for_review, medium_priority
