Repository ansible-collections/azure, pull requests merged in 2024-08, with the labels that each got.

#1650 Add new choices for azure_rm_postgresqlflexibleserver.py's version
  plugins/modules/azure_rm_postgresqlflexibleserver.py
Labels: ready_for_review, medium_priority

#1649 Implement long running polling
  plugins/inventory/azure_rm.py
Labels: ready_for_review, medium_priority, work in

#1666 Updated azure_rm_manageddisk.py's method to update resources
  plugins/modules/azure_rm_manageddisk.py
Labels: enhancement, ready_for_review, medium_priority

#1643 Add Managed Identity support to servicebus
  plugins/modules/azure_rm_servicebus.py
  plugins/modules/azure_rm_servicebus_info.py
  tests/integration/targets/azure_rm_servicebus/tasks/main.yml
Labels: enhancement, ready_for_review

#1673 `azure_rm_virualnetwork_info` - List usage of the subnets within a virtual network
  plugins/modules/azure_rm_virtualnetwork_info.py
  tests/integration/targets/azure_rm_virtualnetwork/tasks/main.yml
Labels: ready_for_review, medium_priority

#1662 `azure_rm_virtualmachineextension` - Refs #1661 enable automatic update for vm extensions
  plugins/modules/azure_rm_virtualmachineextension.py
  plugins/modules/azure_rm_virtualmachineextension_info.py
Labels: ready_for_review, medium_priority, new_feature

#1652 `azure_rm_virtualnetwork` Fixed the bug that failed to detect IPV6
  plugins/modules/azure_rm_sqldatabase.py
  plugins/modules/azure_rm_storageblob.py
  plugins/modules/azure_rm_virtualnetwork.py
Labels: ready_for_review, medium_priority

#1654 `azure_rm_virtualmachinescaleset` - Fixed an issue where vmss tags could not be updated
  plugins/modules/azure_rm_virtualmachinescaleset.py
Labels: ready_for_review, medium_priority

#1668 `azure_rm_aksagentpool` , `azure_rm_aksagentpool_info` - Ignore the 'node_public_ip_prefix_id' compare when updating aks pool
  plugins/modules/azure_rm_aksagentpool.py
  plugins/modules/azure_rm_aksagentpool_info.py
Labels: ready_for_review, high_priority

#1651 Add Managed Identity support to Redis Cache
  plugins/modules/azure_rm_rediscache.py
  plugins/modules/azure_rm_rediscache_info.py
  requirements.txt
  tests/integration/targets/azure_rm_rediscache/tasks/main.yml
Labels: question, ready_for_review, new_feature

#1669 `azure_rm_virtualmachine` - Re-filter the latest image version to avoid problems the version '8.10' confuse high or low with '8.9'
  plugins/modules/azure_rm_virtualmachine.py
Labels: ready_for_review, medium_priority

#1677 `azure_rm_aks` - Upgrade azure-mgmt-containerservice to v31.0.0
  plugins/module_utils/azure_rm_common.py
  plugins/modules/azure_rm_aks.py
  requirements.txt
  tests/integration/targets/azure_rm_aks/tasks/minimal-cluster.yml
Labels: ready_for_review, medium_priority, new_feature

#1678 Managed Identity for StorageVault
  plugins/modules/azure_rm_recoveryservicesvault.py
  plugins/modules/azure_rm_recoveryservicesvault_info.py
  tests/integration/targets/azure_rm_recoveryservicesvault/tasks/main.yml
Labels: enhancement, ready_for_review, new_feature

#1679 `azure_rm_networkinterface` - Set parimary key when the ip_configuration length is greater than 2
  plugins/modules/azure_rm_networkinterface.py
  tests/integration/targets/azure_rm_networkinterface/tasks/main.yml
Labels: enhancement, ready_for_review, medium_priority

#1685 Add support 'node_taints' for azure_rm_aksagent.py
  plugins/modules/azure_rm_aksagentpool.py
  plugins/modules/azure_rm_aksagentpool_info.py
  tests/integration/targets/azure_rm_aksagentpool/tasks/main.yml
Labels: ready_for_review, medium_priority

#1682 `azure_rm_aks` - Add support for 'auto_upgrade_profile
  plugins/module_utils/azure_rm_common.py
  plugins/modules/azure_rm_aks.py
  tests/integration/targets/azure_rm_aks/tasks/minimal-cluster.yml
Labels: ready_for_review, medium_priority

#1676 `azure_rm_diskencryptionset` - Add managed identity support
  plugins/module_utils/azure_rm_common.py
  plugins/module_utils/azure_rm_common_ext.py
  plugins/modules/azure_rm_diskencryptionset.py
  plugins/modules/azure_rm_diskencryptionset_info.py
  tests/integration/targets/azure_rm_diskencryptionset/tasks/main.yml
  tests/integration/targets/azure_rm_diskencryptionset/tasks/managedidentity.yml
Labels: ready_for_review, medium_priority, new_feature

#1626 Update identity support in sqlserver
  plugins/modules/azure_rm_sqlserver.py
  plugins/modules/azure_rm_sqlserver_info.py
  tests/integration/targets/azure_rm_sqlserver/tasks/main.yml
Labels: ready_for_review, medium_priority, new_feature

#1688 Fixed load balancing idempotent failure
  plugins/modules/azure_rm_loadbalancer.py
Labels: ready_for_review, medium_priority

#1621 Add Managed Identity support to CdnProfile module
  plugins/doc_fragments/azure_identity_multiple.py
  plugins/modules/azure_rm_cdnprofile.py
  plugins/modules/azure_rm_cdnprofile_info.py
  tests/integration/targets/azure_rm_cdnprofile/tasks/main.yml
Labels: ready_for_review, medium_priority, new_feature

#1645 Add managed identity support to "azure_rm_cosmosdbaccount"
  plugins/modules/azure_rm_cosmosdbaccount.py
  plugins/modules/azure_rm_cosmosdbaccount_info.py
  requirements.txt
  tests/integration/targets/azure_rm_cosmosdbaccount/tasks/main.yml
Labels: ready_for_review, new_feature

#1689 Fixed a bug where identity was None and could not be dictionarized
  plugins/modules/azure_rm_cdnprofile.py
  plugins/modules/azure_rm_cdnprofile_info.py
  plugins/modules/azure_rm_diskencryptionset_info.py
Labels: ready_for_review, high_priority

#1686 Support to create secondary IP for NIC using azure_rm_networkinterface
  plugins/modules/azure_rm_networkinterface.py
  tests/integration/targets/azure_rm_networkinterface/tasks/main.yml
Labels: ready_for_review, high_priority, medium_priority

#1690 Add manage identity to functionapp module
  plugins/modules/azure_rm_functionapp.py
  tests/integration/targets/azure_rm_functionapp/tasks/main.yml
Labels: ready_for_review, medium_priority, new_feature
