Repository ansible-collections/azure, pull requests merged in 2025-02, with the labels that each got.

#1815 [Enhance] - `azure_rm_aduser_info` Add `surname` and `givenName` to user info output
  plugins/modules/azure_rm_aduser_info.py
Labels: question, ready_for_review, medium_priority

#1798 Distinguish between upload methods of type `blob` and `page`
  plugins/modules/azure_rm_storageblob.py
Labels: ready_for_review, high_priority, medium_priority

#1810 Remove unnecessary constraints
  plugins/modules/azure_rm_keyvaultsecret.py
Labels: ready_for_review, medium_priority, new_feature

#1818 Bump version to v3.2.0
  CHANGELOG.md
  galaxy.yml
Labels: ready_for_review

#1797 Add pipx alternative for deps installation
  README.md
Labels: enhancement, ready_for_review, medium_priority

#1802 [Enhance] `azure_rm_storageaccount`, `azure_rm_storageaccount_info` - Add support for `immutable_storage_with_versioning`
  plugins/modules/azure_rm_storageaccount.py
  plugins/modules/azure_rm_storageaccount_info.py
  tests/integration/targets/azure_rm_storageaccount/tasks/main.yml
Labels: ready_for_review, medium_priority, new_feature

#1803 Modify the random value of the azure_rm_dnsrecoredset test case
  tests/integration/targets/azure_rm_dnsrecordset/tasks/main.yml
Labels: ready_for_review, high_priority

#1800 [Enhance] - `azure_rm_trafficmanagerprofile`, `azure_rm_trafficmanagerprofile_info` - Add support for `custom_header`, `expected_status_code_ranges`, `max_return` and `allowed_endpoint_record_types`
  plugins/modules/azure_rm_trafficmanagerprofile.py
  plugins/modules/azure_rm_trafficmanagerprofile_info.py
  tests/integration/targets/azure_rm_trafficmanagerprofile/tasks/main.yml
Labels: ready_for_review, medium_priority, new_feature

#1807 `azure_rm_roleassignment` - Delete scope tail `/` when comparing scopes
  plugins/modules/azure_rm_roleassignment.py
Labels: ready_for_review, medium_priority

#1816 VirtualMachine update to allow creation from snapshot image
  plugins/modules/azure_rm_virtualmachine.py
  plugins/modules/azure_rm_virtualmachine_info.py
Labels: enhancement, ready_for_review, medium_priority

#1808 `azure_rm_manageddisk`, `azure_rm_virtualmachine_info` - Add support for `write_accelerator_enabled`
  plugins/modules/azure_rm_manageddisk.py
  plugins/modules/azure_rm_virtualmachine_info.py
Labels: ready_for_review, medium_priority

#1822 `azure_rm_virtualmachine_info` Add `maintenance_redeploy_status`
  plugins/modules/azure_rm_virtualmachine_info.py
Labels: enhancement, ready_for_review

#1826 `azure_rm_subnet_info` - Fix incorrect API call
  plugins/modules/azure_rm_subnet_info.py
Labels: ready_for_review, medium_priority

#1831 `azure_rm_diskaccess`, `azure_rm_diskaccess_info` - Add disk access managed module
  meta/runtime.yml
  plugins/modules/azure_rm_diskaccess.py
  plugins/modules/azure_rm_diskaccess_info.py
  plugins/modules/azure_rm_manageddisk.py
  plugins/modules/azure_rm_manageddisk_info.py
  pr-pipelines.yml
  tests/integration/targets/azure_rm_diskaccess/aliases
  tests/integration/targets/azure_rm_diskaccess/meta/main.yml
  tests/integration/targets/azure_rm_diskaccess/tasks/main.yml
  tests/integration/targets/azure_rm_manageddisk/tasks/main.yml
Labels: ready_for_review, new_module_pr, medium_priority, new_feature

#1827 Fix the compute API return value change bug
  plugins/modules/azure_rm_virtualmachine_info.py
Labels: enhancement, ready_for_review, medium_priority
