Repository ansible-collections/azure, pull requests merged in 2025-06, with the labels that each got.

#1954 Add python v3.12 and v3.13 to CI pipeline
  pr-pipelines.yml
Labels: ready_for_review

#1951 Separate the VM test into different region
  tests/integration/targets/azure_rm_automationaccount/aliases
  tests/integration/targets/azure_rm_automationrunbook/aliases
  tests/integration/targets/azure_rm_keyvault/aliases
  tests/integration/targets/azure_rm_keyvaultcertificate/aliases
  tests/integration/targets/azure_rm_keyvaultkey/aliases
  tests/integration/targets/azure_rm_keyvaultsecret/aliases
  tests/integration/targets/azure_rm_privateendpoint/tasks/main.yml
  tests/integration/targets/azure_rm_privateendpointdnszonegroup/tasks/main.yml
  tests/integration/targets/azure_rm_virtualmachine/tasks/azure_test_minimal_manageddisk.yml
  tests/integration/targets/azure_rm_virtualmachine/tasks/azure_test_vm_identity.yml
  tests/integration/targets/azure_rm_virtualnetworkgatewaynatrule/tasks/main.yml
  tests/integration/targets/inventory_azure/playbooks/setup.yml
  tests/integration/targets/inventory_azure/playbooks/teardown.yml
  tests/integration/targets/inventory_azure/playbooks/vars.yml
Labels: ready_for_review, medium_priority

#1957 Fix failure on response with bytes body
  plugins/modules/azure_rm_resource_info.py
Labels: enhancement, ready_for_review, medium_priority

#1717 Add HSM support to Key Vault
  meta/runtime.yml
  plugins/module_utils/security_domain_utils.py
  plugins/modules/azure_rm_keyvault.py
  plugins/modules/azure_rm_keyvault_info.py
  plugins/modules/azure_rm_keyvaultsecuritydomain.py
  requirements.txt
  tests/integration/targets/azure_rm_keyvault/aliases
  tests/integration/targets/azure_rm_keyvault/files/cert_0.cer
  tests/integration/targets/azure_rm_keyvault/files/cert_0.key
  tests/integration/targets/azure_rm_keyvault/files/cert_1.cer
  tests/integration/targets/azure_rm_keyvault/files/cert_1.key
  tests/integration/targets/azure_rm_keyvault/files/cert_2.cer
  tests/integration/targets/azure_rm_keyvault/files/cert_2.key
  tests/integration/targets/azure_rm_keyvault/tasks/main.yml
Labels: ready_for_review, new_feature

#1960 Update galaxy.yml to not bundle test credentials
  galaxy.yml
Labels: ready_for_review, high_priority

#1968 Bump vesion to v3.5.0
  CHANGELOG.md
  galaxy.yml
  plugins/modules/azure_rm_adserviceprincipal.py
Labels: ready_for_review, medium_priority

#1973 Fix the errors caused by repeate descriptions
  plugins/modules/azure_rm_adserviceprincipal.py
  tests/integration/targets/inventory_azure/playbooks/test_inventory_cache.yml
  tests/integration/targets/inventory_azure/playbooks/test_inventory_flush_part_1.yml
Labels: ready_for_review, high_priority

#1958 Fix virtualnetworkgatewayconnection module not working for IPSec tunnel
  plugins/modules/azure_rm_virtualnetworkgatewayconnection.py
  plugins/modules/azure_rm_virtualnetworkgatewayconnection_info.py
  tests/integration/targets/azure_rm_virtualnetworkgatewayconnection/tasks/main.yml
Labels: ready_for_review, medium_priority

#1966 Add support azure_rm_virtualnetworkgateway_info
  plugins/modules/azure_rm_virtualnetworkgateway_info.py
  tests/integration/targets/azure_rm_virtualnetworkgateway/tasks/main.yml
Labels: ready_for_review, new_module_pr, medium_priority

#1981 Support permanently deletes the specified vaults
  plugins/modules/azure_rm_keyvault.py
  tests/integration/targets/azure_rm_keyvault/tasks/main.yml
Labels: enhancement, ready_for_review, new_feature

#1983 Fix the function reference error of azure_rm_loganalyticsworkspace_info.py
  plugins/modules/azure_rm_loganalyticsworkspace_info.py
  tests/integration/targets/azure_rm_loganalyticsworkspace/tasks/main.yml
Labels: enhancement, ready_for_review, medium_priority
