Repository ansible-collections/azure, pull requests merged in 2025-07, with the labels that each got.

#1992 Ignore the disabled secret when obtain the secret info
  plugins/modules/azure_rm_keyvaultsecret_info.py
Labels: enhancement, ready_for_review, medium_priority

#1998 Add the required_by constraint condition
  plugins/modules/azure_rm_virtualmachine.py
  plugins/modules/azure_rm_virtualnetwork_info.py
Labels: ready_for_review

#1999 Disable all enabled intelligence packs after test
  tests/integration/targets/azure_rm_loganalyticsworkspace/tasks/main.yml
Labels: ready_for_review, medium_priority

#1994 Add support for generating inventory with a graph query
  plugins/doc_fragments/azure_kql.py
  plugins/inventory/azure_kql.py
  requirements.txt
  tests/integration/targets/inventory_azure/playbooks/create_inventory_config.yml
  tests/integration/targets/inventory_azure/playbooks/empty_inventory_config.yml
  tests/integration/targets/inventory_azure/playbooks/setup.yml
  tests/integration/targets/inventory_azure/playbooks/test_inventory_kql.yml
  tests/integration/targets/inventory_azure/runme.sh
  tests/integration/targets/inventory_azure/templates/kql.yml
Labels: question, ready_for_review

#2001 Support Priority Type Regular on azure_rm_virtualmachinescaleset Module
  plugins/modules/azure_rm_virtualmachinescaleset.py
Labels: ready_for_review, medium_priority

#2004 Fix ansible-lint check error
  tests/integration/targets/azure_rm_mariadbserver/tasks/main.yml
Labels: ready_for_review

#1962 Add support for resolution_policy
  plugins/modules/azure_rm_privatednszonelink.py
  plugins/modules/azure_rm_privatednszonelink_info.py
  requirements.txt
  tests/integration/targets/azure_rm_privatednszonelink/tasks/main.yml
Labels: ready_for_review, medium_priority

#2009 Add a filtering mechanism to obtain loganalystics under the resource group
  tests/integration/targets/azure_rm_loganalyticsworkspace/tasks/main.yml
Labels: ready_for_review

#2010 Fix the assertion errors in the test cases
  tests/integration/targets/azure_rm_cosmosdbaccount/tasks/main.yml
  tests/integration/targets/azure_rm_mariadbserver/tasks/main.yml
  tests/integration/targets/azure_rm_mysqlserver/tasks/main.yml
  tests/integration/targets/azure_rm_sqlserver/tasks/main.yml
  tests/integration/targets/azure_rm_storageblob/tasks/main.yml
Labels: ready_for_review

#1967 Import azure eda
  extensions/eda/README.md
  extensions/eda/plugins/event_source/azure_service_bus.py
  extensions/eda/plugins/event_source/schemas/azure_service_bus.json
  requirements.txt
  tests/unit/README.md
  tests/unit/event_source/test_azure_service_bus.py
  tests/unit/requirements.txt
Labels: ready_for_review, work in

#2018 Handle the azure_rm_sqlmanagedinstance.py LROPollery
  plugins/modules/azure_rm_sqlmanagedinstance.py
Labels: ready_for_review, medium_priority

#2021 Handle the azure_rm_virtualwan.py deletion of LROPollery results
  plugins/modules/azure_rm_virtualwan.py
Labels: ready_for_review, medium_priority

#2020 Handle the azure_rm_virtuahub.py deletion of LROPollery results
  plugins/modules/azure_rm_virtualhub.py
Labels: ready_for_review, medium_priority

#2023 Add support container registry token
  meta/runtime.yml
  plugins/modules/azure_rm_containerregistrytoken.py
  plugins/modules/azure_rm_containerregistrytoken_info.py
  plugins/modules/azure_rm_containerregistrytokenpassword.py
  pr-pipelines.yml
  tests/integration/targets/azure_rm_containerregistry/tasks/main.yml
Labels: ready_for_review, new_module_pr, medium_priority

#2016 Add metric alerts
  meta/runtime.yml
  plugins/module_utils/azure_rm_common.py
  plugins/modules/azure_rm_monitormetricalerts.py
  plugins/modules/azure_rm_monitormetricalerts_info.py
  pr-pipelines.yml
  tests/integration/targets/azure_rm_monitormetricalerts/aliases
  tests/integration/targets/azure_rm_monitormetricalerts/meta/main.yml
  tests/integration/targets/azure_rm_monitormetricalerts/tasks/main.yml
Labels: ready_for_review, new_module_pr, medium_priority

#1971 Add activity log alerts
  meta/runtime.yml
  plugins/module_utils/azure_rm_common.py
  plugins/module_utils/azure_rm_common_ext.py
  plugins/modules/azure_rm_monitoractivitylogalerts.py
  plugins/modules/azure_rm_monitoractivitylogalerts_info.py
  pr-pipelines.yml
  tests/integration/targets/azure_rm_monitoractivitylogalerts/aliases
  tests/integration/targets/azure_rm_monitoractivitylogalerts/meta/main.yml
  tests/integration/targets/azure_rm_monitoractivitylogalerts/tasks/main.yml
Labels: ready_for_review, medium_priority

#1996 Convert the certificate data of type bytearray to base64
  plugins/modules/azure_rm_keyvaultcertificate.py
  plugins/modules/azure_rm_keyvaultcertificate_info.py
Labels: enhancement, ready_for_review, medium_priority
