Repository ansible-collections/azure, pull requests merged in 2025-09, with the labels that each got.

#2047 Enable azure_rm_appgateway test
  tests/integration/targets/azure_rm_appgateway/aliases
  tests/integration/targets/azure_rm_appgateway/files/cert1.txt
  tests/integration/targets/azure_rm_appgateway/files/cert2.txt
  tests/integration/targets/azure_rm_appgateway/tasks/main.yml
Labels: enhancement, ready_for_review

#2048 Fix compare error where the returned ID is in uppercase
  plugins/modules/azure_rm_securitygroup.py
Labels: ready_for_review, high_priority

#2049 Add support for 'key_vault_properties' and 'encryption_identity'
  plugins/modules/azure_rm_storageaccount.py
  plugins/modules/azure_rm_storageaccount_info.py
  tests/integration/targets/azure_rm_storageaccount/tasks/main.yml
Labels: enhancement, ready_for_review, medium_priority, new_feature

#2046 [Infra]: update ado yamls to use pool-ubuntu-2404
  pr-pipelines.yml
Labels: ready_for_review

#2052 Update some test for new subscription
  tests/integration/targets/azure_rm_aks/tasks/main.yml
  tests/integration/targets/azure_rm_aksagentpool/tasks/main.yml
  tests/integration/targets/azure_rm_cosmosdbaccount/tasks/main.yml
  tests/integration/targets/azure_rm_expressroute/tasks/main.yml
  tests/integration/targets/azure_rm_multiplemanageddisks/defaults/main.yml
  tests/integration/targets/azure_rm_multiplemanageddisks/tasks/test_async.yml
  tests/integration/targets/azure_rm_multiplemanageddisks/tasks/test_shared.yml
  tests/integration/targets/azure_rm_mysqlflexibleserver/tasks/main.yml
  tests/integration/targets/azure_rm_snapshot/tasks/main.yml
  tests/integration/targets/azure_rm_virtualmachine/tasks/azure_test_deallocate.yml
  tests/integration/targets/azure_rm_virtualmachine/tasks/azure_test_encrypted.yml
  tests/integration/targets/azure_rm_virtualmachine/tasks/azure_test_image_skus.yml
  tests/integration/targets/azure_rm_virtualmachine/tasks/azure_test_minimal.yml
  tests/integration/targets/azure_rm_virtualmachine/tasks/azure_test_no_nsg.yml
  tests/integration/targets/azure_rm_virtualmachine/tasks/azure_test_skus.yml
  tests/integration/targets/azure_rm_virtualmachine/tasks/setup.yml
  tests/integration/targets/inventory_azure/playbooks/setup.yml
  tests/integration/targets/inventory_azure/playbooks/teardown.yml
  tests/integration/targets/inventory_azure/playbooks/vars.yml
Labels: ready_for_review

#2059 Add support for public_ip_prefix in azure_rm_publicipaddress
  plugins/modules/azure_rm_publicipaddress.py
  plugins/modules/azure_rm_publicipaddress_info.py
  tests/integration/targets/azure_rm_publicipaddress/tasks/main.yml
Labels: enhancement, ready_for_review, medium_priority, new_feature

#2058 Add modules for data collection endpoint and rule association
  meta/runtime.yml
  plugins/modules/azure_rm_monitordatacollectionendpoint.py
  plugins/modules/azure_rm_monitordatacollectionendpoint_info.py
  plugins/modules/azure_rm_monitordatacollectionruleassociation.py
  plugins/modules/azure_rm_monitordatacollectionruleassociation_info.py
  pr-pipelines.yml
  tests/integration/targets/azure_rm_loganalyticsworkspace/aliases
  tests/integration/targets/azure_rm_loganalyticsworkspace/tasks/main.yml
Labels: ready_for_review, new_module_pr, medium_priority

#2064 Add new feature and SEP relate module
  meta/runtime.yml
  plugins/modules/azure_rm_serviceendpointpolicy.py
  plugins/modules/azure_rm_serviceendpointpolicy_info.py
  plugins/modules/azure_rm_serviceendpointpolicydefinition.py
  plugins/modules/azure_rm_serviceendpointpolicydefinition_info.py
  plugins/modules/azure_rm_subnet.py
  plugins/modules/azure_rm_subnet_info.py
  pr-pipelines.yml
  tests/integration/targets/azure_rm_subnet/aliases
  tests/integration/targets/azure_rm_subnet/tasks/main.yml
Labels: ready_for_review, new_module_pr, medium_priority, new_feature

#2066 Modify azure_rm_virtualnetworkgatewaynatrule.py test group --- group13
  tests/integration/targets/azure_rm_virtualnetworkgatewaynatrule/aliases
Labels: ready_for_review, high_priority

#2068 Bump version to v3.9.0
  CHANGELOG.md
  galaxy.yml
Labels: ready_for_review
