Repository ansible-collections/azure, pull requests merged in 2025-03, with the labels that each got.

#1833 [Enhance] `azure_rm_manageddisk` and `azure_rm_manageddisk_info` - Add support for more parameters manageddisk
  plugins/modules/azure_rm_manageddisk.py
  plugins/modules/azure_rm_manageddisk_info.py
  tests/integration/targets/azure_rm_manageddisk/tasks/main.yml
Labels: enhancement, ready_for_review, medium_priority

#1835 Fixed an error caused by agent_pool.security_profile returning None
  plugins/modules/azure_rm_aks.py
Labels: ready_for_review, medium_priority

#1840 Do not compare the zone_redundant return value when idempotent testing
  plugins/modules/azure_rm_servicebus.py
  tests/integration/targets/azure_rm_servicebus/tasks/main.yml
Labels: ready_for_review, medium_priority

#1836 `azure_keyvault_secret` - Add support for `use_cli` , use CLI credential
  plugins/lookup/azure_keyvault_secret.py
Labels: enhancement, ready_for_review, medium_priority

#1837 Fixed an error caused by the user defining subscription_id in route_table
  plugins/module_utils/azure_rm_common.py
Labels: enhancement, ready_for_review, medium_priority

#1838 New modules - `azure_rm_resourcehealthstates_info`
  meta/runtime.yml
  plugins/module_utils/azure_rm_common.py
  plugins/modules/azure_rm_resourcehealthstates_info.py
  pr-pipelines.yml
  requirements.txt
  tests/integration/targets/azure_rm_resourcehealthstates/aliases
  tests/integration/targets/azure_rm_resourcehealthstates/meta/main.yml
  tests/integration/targets/azure_rm_resourcehealthstates/tasks/main.yml
Labels: ready_for_review, new_module_pr, medium_priority

#1841 Bump version to v3.3.0
  CHANGELOG.md
  galaxy.yml
Labels: ready_for_review, medium_priority

#1854 Change log v3.3.1
  CHANGELOG.md
  galaxy.yml
Labels: documentation-pr

#1865 [Documentation] Update Readme
  README.md
Labels: documentation-pr, ready_for_review, medium_priority

#1860 Gets the image return value during idempotent testing
  plugins/modules/azure_rm_manageddisk.py
  tests/integration/targets/azure_rm_manageddisk/tasks/main.yml
Labels: ready_for_review, medium_priority

#1851 Perfact the return value information
  plugins/modules/azure_rm_keyvaultsecret_info.py
Labels: enhancement, ready_for_review, medium_priority

#1852 Adding field notes to azure_rm_adapplication
  plugins/modules/azure_rm_adapplication.py
  plugins/modules/azure_rm_adapplication_info.py
Labels: ready_for_review, medium_priority

#1866 azure_rm_manageddisk Add a testcase for #1858 / #1860
  tests/integration/targets/azure_rm_manageddisk/tasks/main.yml
Labels: enhancement, ready_for_review, medium_priority

#1871 Update the azure_rm_servicebus.py module parameter Settings
  plugins/modules/azure_rm_servicebus.py
Labels: ready_for_review, medium_priority

#1847 `azure_rm_virtualmachine` - Add support for datadisk naming
  plugins/modules/azure_rm_virtualmachine.py
Labels: enhancement, ready_for_review, medium_priority

#1864 Show failure of idempotency in integration tests for #1859
  tests/integration/targets/azure_rm_roleassignment/tasks/main.yml
Labels: question, medium_priority, work in
