Repository ansible-collections/azure, pull requests merged in 2025-05, with the labels that each got.

#1902 [Enhance] `azure_rm_adserviceprincipal` Adding managed identity
  plugins/modules/azure_rm_adserviceprincipal.py
  plugins/modules/azure_rm_adserviceprincipal_info.py
Labels: ready_for_review, medium_priority

#1910 `azure_rm_virtualmachinescaleset` Add support for `application_security_groups` and `private_ip_address_version`
  plugins/modules/azure_rm_virtualmachinescaleset.py
  plugins/modules/azure_rm_virtualmachinescaleset_info.py
  tests/integration/targets/azure_rm_virtualmachinescaleset/tasks/main.yml
Labels: ready_for_review, medium_priority, new_feature

#1909 `azure_rm_virtualnetworkpeering` - Support virtual networks cross subscription
  plugins/modules/azure_rm_galleryimageversion.py
  plugins/modules/azure_rm_virtualnetworkpeering.py
Labels: ready_for_review, medium_priority

#1912 Support alternative MSGraph cloud endpoints
  plugins/module_utils/azure_rm_common.py
Labels: question, ready_for_review, medium_priority

#1918 Update `azure_rm` inventory API to new version
  plugins/inventory/azure_rm.py
Labels: ready_for_review, medium_priority

#1922 Indirect node count query file
  extensions/audit/README.MD
  extensions/audit/event_query.yml
Labels: ready_for_review, high_priority

#1933 Fix the error in the document description
  plugins/modules/azure_rm_privateendpoint_info.py
Labels: documentation-pr, ready_for_review, medium_priority

#1936 fix: Correct spelling for VM info property identity
  plugins/modules/azure_rm_virtualmachine_info.py
Labels: documentation-pr, ready_for_review

#1926 Add modules for recovery services vault config
  meta/runtime.yml
  plugins/modules/azure_rm_recoveryservicesvaultconfig.py
  plugins/modules/azure_rm_recoveryservicesvaultconfig_info.py
  tests/integration/targets/azure_rm_recoveryservicesvault/tasks/main.yml
Labels: ready_for_review, medium_priority

#1913 [Enhance] `plugins/modules/azure_rm_aksagentpool` - Support more agentpool parameters
  plugins/modules/azure_rm_aksagentpool.py
  plugins/modules/azure_rm_aksagentpool_info.py
Labels: ready_for_review, medium_priority

#1924 Add `addon.http_application_routing` to `azure_rm_aks` test and update tests
  tests/integration/targets/azure_rm_aks/tasks/main.yml
  tests/integration/targets/azure_rm_azurefirewall/tasks/main.yml
  tests/integration/targets/azure_rm_bastionhost/tasks/main.yml
  tests/integration/targets/azure_rm_dnsrecordset/tasks/main.yml
  tests/integration/targets/azure_rm_gallery/aliases
  tests/integration/targets/azure_rm_gallery/tasks/main.yml
  tests/integration/targets/azure_rm_image/aliases
  tests/integration/targets/azure_rm_multiplemanageddisks/aliases
  tests/integration/targets/azure_rm_multiplemanageddisks/tasks/main.yml
  tests/integration/targets/azure_rm_networkinterface/aliases
  tests/integration/targets/azure_rm_privatelinkservice/aliases
  tests/integration/targets/azure_rm_privatelinkservice/tasks/main.yml
  tests/integration/targets/azure_rm_publicipaddress/tasks/main.yml
  tests/integration/targets/azure_rm_snapshot/aliases
  tests/integration/targets/azure_rm_snapshot/tasks/main.yml
  tests/integration/targets/azure_rm_virtualmachineextension/aliases
  tests/integration/targets/azure_rm_virtualmachineextension/tasks/main.yml
  tests/integration/targets/azure_rm_virtualmachinescaleset/aliases
  tests/integration/targets/azure_rm_virtualmachinescaleset/tasks/main.yml
  tests/integration/targets/azure_rm_virtualnetworkgatewayconnection/tasks/main.yml
  tests/integration/targets/azure_rm_virtualnetworkgatewaynatrule/tasks/main.yml
  tests/integration/targets/azure_rm_webapp/tasks/main.yml
  tests/integration/targets/azure_rm_webappvnetconnection/tasks/main.yml
Labels: ready_for_review, medium_priority

#1939 [Bug Fix] `azure_rm_networkflowlog` - Fix the location bug of the default resource group of location
  plugins/modules/azure_rm_networkflowlog.py
Labels: ready_for_review, medium_priority

#1917 `azure_rm_networkinterface` integration tests for keeping public IPs on NIC updates
  tests/integration/targets/azure_rm_networkinterface/tasks/main.yml
Labels: question, ready_for_review, medium_priority

#1928 [Bug Fix] - `azure_rm_automationaccount_info` Fix the bug under all automated accounts under obtaining `subscription_id`
  plugins/modules/azure_rm_automationaccount_info.py
Labels: ready_for_review, medium_priority

#1935 [Bug Fix] Fix `azure_rm_gallery` `description setting` bug
  plugins/modules/azure_rm_gallery.py
  plugins/modules/azure_rm_gallery_info.py
Labels: ready_for_review, medium_priority

#1906 Migrate mysql flexible relate SDK to azure-mgmt-mysqlflexibleservers
  plugins/module_utils/azure_rm_common.py
  plugins/modules/azure_rm_mysqlflexibleconfiguration.py
  requirements.txt
Labels: ready_for_review, medium_priority

#1940 Update test cases to work under ansible-2.19 Group1
  plugins/inventory/azure_rm.py
  plugins/modules/azure_rm_keyvaultkey_info.py
  tests/integration/targets/azure_rm_keyvaultsecret/tasks/main.yml
  tests/integration/targets/azure_rm_privatednsrecordset/tasks/main.yml
Labels: enhancement, ready_for_review, medium_priority

#1944 Add ansible v2.17 and v2.18 for CI
  pr-pipelines.yml
  tests/integration/targets/azure_rm_appgateway/tasks/main.yml
  tests/integration/targets/azure_rm_natgateway/tasks/main.yml
  tests/integration/targets/azure_rm_servicebus/tasks/main.yml
Labels: ready_for_review, dependencies

#1942 Update test cases to work under ansible-2.19 Group9
  tests/integration/targets/azure_rm_keyvault/tasks/main.yml
  tests/integration/targets/azure_rm_mariadbserver/tasks/main.yml
  tests/integration/targets/azure_rm_sqlserver/tasks/main.yml
Labels: enhancement, ready_for_review, medium_priority

#1950 Bump version to v3.4.0
  CHANGELOG.md
  galaxy.yml
Labels: ready_for_review, medium_priority
