Repository ansible-collections/azure, pull requests merged in 2025-04, with the labels that each got.

#1877 Delete I(sku=basic) from the public IP address
  plugins/modules/azure_rm_publicipaddress.py
  plugins/modules/azure_rm_publicipaddress_info.py
  tests/integration/targets/azure_rm_dnsrecordset/tasks/main.yml
  tests/integration/targets/azure_rm_gallery/tasks/main.yml
  tests/integration/targets/azure_rm_image/tasks/main.yml
  tests/integration/targets/azure_rm_loadbalancer/tasks/main.yml
  tests/integration/targets/azure_rm_publicipaddress/tasks/main.yml
  tests/integration/targets/azure_rm_virtualmachine/tasks/azure_test_public_ip.yml
  tests/integration/targets/azure_rm_virtualmachineextension/tasks/main.yml
  tests/integration/targets/azure_rm_virtualnetworkgateway/tasks/main.yml
  tests/integration/targets/azure_rm_virtualnetworkgatewayconnection/aliases
Labels: ready_for_review, medium_priority, breaking-change

#1878 Decrease the timeout period in azure_rm.py
  plugins/inventory/azure_rm.py
Labels: enhancement, ready_for_review, medium_priority

#1879 Compatible os_type options case
  plugins/modules/azure_rm_aks.py
  plugins/modules/azure_rm_aksagentpool.py
  plugins/modules/azure_rm_containerinstance.py
  plugins/modules/azure_rm_devtestlabvirtualmachine.py
  plugins/modules/azure_rm_galleryimage.py
  plugins/modules/azure_rm_hdinsightcluster.py
  plugins/modules/azure_rm_image.py
  plugins/modules/azure_rm_manageddisk.py
  plugins/modules/azure_rm_multiplemanageddisks.py
  plugins/modules/azure_rm_networkinterface.py
  plugins/modules/azure_rm_snapshot.py
  plugins/modules/azure_rm_virtualmachine.py
  plugins/modules/azure_rm_virtualmachinescaleset.py
Labels: ready_for_review, medium_priority

#1881 Fix tags cannot be updated
  plugins/modules/azure_rm_networkinterface.py
Labels: enhancement, ready_for_review, medium_priority

#1890 Fix the idempotent issue of azure_rm_backuppolicy.py
  plugins/modules/azure_rm_backuppolicy.py
  plugins/modules/azure_rm_backuppolicy_info.py
Labels: enhancement, ready_for_review, high_priority

#1892 Support disk encryption set in azure_rm_virtualmachinescaleset
  plugins/modules/azure_rm_virtualmachinescaleset.py
  tests/integration/targets/azure_rm_virtualmachinescaleset/tasks/main.yml
  tests/integration/targets/azure_rm_virtualmachinescaleset/tasks/setup_des.yml
Labels: enhancement, ready_for_review, medium_priority

#1883 Add shared_gallery_image_id to image dict
  plugins/modules/azure_rm_virtualmachine.py
Labels: ready_for_review, medium_priority, new_feature

#1887 add enhanced backup policy to azure_rm_backuppolicy
  plugins/modules/azure_rm_backuppolicy.py
  tests/integration/targets/azure_rm_backuppolicy/tasks/main.yml
Labels: question, ready_for_review, medium_priority

#1845 Update the azure_rm_galleryimageversion dependency api version to v2023-07-03
  plugins/module_utils/azure_rm_common.py
  plugins/modules/azure_rm_galleryimageversion.py
  plugins/modules/azure_rm_galleryimageversion_info.py
  plugins/modules/azure_rm_virtualmachine.py
  tests/integration/targets/azure_rm_gallery/tasks/main.yml
  tests/integration/targets/azure_rm_snapshot/aliases
  tests/integration/targets/azure_rm_snapshot/meta/main.yml
  tests/integration/targets/azure_rm_snapshot/tasks/main.yml
Labels: ready_for_review, medium_priority

#1876 Migrate postgresql flexible relate SDK to azure-mgmt-postgresqlflexibleservers
  plugins/module_utils/azure_rm_common.py
  plugins/modules/azure_rm_postgresqlflexibleserver.py
  requirements.txt
Labels: enhancement, ready_for_review, medium_priority
